// @generated by `python -m utils.rust_env.columns --write` — DO NOT EDIT.
// Source of truth: `src/utils/rust_env/columns.py` (the columns) + `protocol.py` (ops, statuses,
// counters). Pinned by `src/utils/rust_env/columns_test.py` (routine).
#![allow(dead_code)]

/// FNV-1a-64 of `columns.schema_text()`; a front end compares it with its own table at load.
pub const SCHEMA_ID: &str = "629e03424189b266";

// ---- dims
pub const SIDES: usize = 2;
pub const ACT: usize = 11;
pub const SEED_WORDS: usize = 4;
pub const NCOUNTERS: usize = 11;
/// The encoder's row length — the port's own constant, never a literal here.
pub const OBS_DIM: usize = pokesim::encoder::OBS_DIM;

/// The startup declaration's keys (`protocol.SPEC_KEYS`): every one required, no other accepted.
pub const SPEC_KEYS: [&str; 10] = ["n", "threads", "format_id", "names", "teams", "decision_tense", "switch_freeze", "turn_limit", "refusal_budget", "bank_dir"];

// ---- ops (`core::dispatch`'s first argument)
pub mod op {
    /// start every env's episode from the staged `ep_team` / `ep_seed`; write every output column (lane 0)
    pub const RESET: u8 = b'R';
    /// feed `action` for every (env, side) with `need` = 1, run to the next caller decision; an env whose episode ended (or was quarantined) writes `done` and auto-resets from the staged inputs (lane 0)
    pub const STEP: u8 = b'S';
    /// Every op, for the front ends' tables.
    pub const ALL: [(u8, &str); 2] = [(RESET, "RESET"), (STEP, "STEP")];
}

// ---- statuses (`core::dispatch`'s result code)
pub mod status {
    /// the op completed; every output column is written
    pub const OK: i32 = 0;
    /// the core broke one of its own invariants (a `CoreError::Fault`): a BUG; the env's input log is banked — Python `CoreFault`
    pub const FAULT: i32 = 1;
    /// the caller sent input no battle can take (an illegal action, a team index out of range, a seed word >= 65536): `CoreError::Malformed` — Python `CallerError`
    pub const CALLER: i32 = 2;
    /// a panic inside the core, caught at the env; the env's input log is banked — Python `CorePanic`
    pub const PANIC: i32 = 3;
    /// the op broke the DECLARED LIFECYCLE (dispatch before freeze, a column set that differs from the frozen binding, an unknown opcode); counted in an `*_after_freeze` counter where it is one — Python `LifecycleViolation`
    pub const LIFECYCLE: i32 = 4;
    /// a quarantine would exceed the refusal budget declared at startup: a refusal STORM is systemic, never absorbed one battle at a time — Python `RefusalBudgetExceeded`
    pub const BUDGET: i32 = 5;
}

// ---- pool counters (indices into the `counters` column)
pub mod counter {
    /// ops dispatched (every status)
    pub const DISPATCHES: usize = 0;
    /// rows written (one per (env, side) with need = 1 after an op)
    pub const DECISIONS: usize = 1;
    /// episodes started (RESET + every auto-reset)
    pub const EPISODES_STARTED: usize = 2;
    /// episodes that ended by the battle's own end (not quarantine)
    pub const EPISODES_ENDED: usize = 3;
    /// battles QUARANTINED (a `CoreError::Refusal`: banked, done = 1, refused = 1)
    pub const REFUSALS: usize = 4;
    /// wall ns of the last dispatch INSIDE the core (the caller's wall minus it = transport)
    pub const CORE_NS_LAST: usize = 5;
    /// wall ns of every dispatch inside the core
    pub const CORE_NS_TOTAL: usize = 6;
    /// worker threads created after freeze
    pub const THREADS_SPAWNED_AFTER_FREEZE: usize = 7;
    /// envs added to the pool after freeze
    pub const ENVS_ADDED_AFTER_FREEZE: usize = 8;
    /// dispatches that named a column set other than the frozen binding (each one refused)
    pub const COLUMN_REBINDS_AFTER_FREEZE: usize = 9;
    /// refusal-bank reallocations after freeze (the bank's capacity = the refusal budget, reserved at startup)
    pub const BANK_GROWTH_AFTER_FREEZE: usize = 10;
    pub const NAMES: [&str; 11] = ["DISPATCHES", "DECISIONS", "EPISODES_STARTED", "EPISODES_ENDED", "REFUSALS", "CORE_NS_LAST", "CORE_NS_TOTAL", "THREADS_SPAWNED_AFTER_FREEZE", "ENVS_ADDED_AFTER_FREEZE", "COLUMN_REBINDS_AFTER_FREEZE", "BANK_GROWTH_AFTER_FREEZE"];
    /// The DECLARED-LIFECYCLE counters: each must stay 0 for the process's life.
    pub const AFTER_FREEZE: [usize; 4] = [THREADS_SPAWNED_AFTER_FREEZE, ENVS_ADDED_AFTER_FREEZE, COLUMN_REBINDS_AFTER_FREEZE, BANK_GROWTH_AFTER_FREEZE];
}

// ---- the columns
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Dtype { F32, U8, I32, U32, U64 }

impl Dtype {
    pub const fn size(self) -> usize {
        match self { Dtype::F32 | Dtype::I32 | Dtype::U32 => 4, Dtype::U8 => 1, Dtype::U64 => 8 }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Dir { In, Out }

/// One row of the table.
#[derive(Clone, Copy, Debug)]
pub struct ColSpec {
    pub name: &'static str,
    pub dtype: Dtype,
    pub dir: Dir,
    /// Its first dim is N (env i owns row i).
    pub per_env: bool,
    /// Elements per env row (per_env) or in the whole column (a pool column).
    pub row_elems: usize,
    pub owner: &'static str,
}

/// Column indices, in table order.
pub mod col {
    pub const ACTION: usize = 0;
    pub const EP_TEAM: usize = 1;
    pub const EP_SEED: usize = 2;
    pub const OBS: usize = 3;
    pub const MASK: usize = 4;
    pub const NEED: usize = 5;
    pub const REWARD: usize = 6;
    pub const DONE: usize = 7;
    pub const REFUSED: usize = 8;
    pub const EPISODE: usize = 9;
    pub const DEC_N: usize = 10;
    pub const TURN: usize = 11;
    pub const COUNTERS: usize = 12;
}

pub const N_COLUMNS: usize = 13;

pub const COLUMNS: [ColSpec; N_COLUMNS] = [
    // STEP: the action index (0..ACT) for every (env, side) with need = 1; ignored where need = 0
    ColSpec { name: "action", dtype: Dtype::I32, dir: Dir::In, per_env: true, row_elems: SIDES, owner: "0" },
    // the NEXT episode's teams, as indices into the team table declared at startup (p1, p2); read at RESET and at every auto-reset, so the caller keeps it staged for the episode after the current one
    ColSpec { name: "ep_team", dtype: Dtype::U32, dir: Dir::In, per_env: true, row_elems: SIDES, owner: "0" },
    // the NEXT episode's Showdown seed "a,b,c,d" (each word < 65536); read with ep_team
    ColSpec { name: "ep_seed", dtype: Dtype::U32, dir: Dir::In, per_env: true, row_elems: SEED_WORDS, owner: "0" },
    // the side's observation row (`BattleVersion::encode` on its PARSE chain — the row sim_bridge's __OBS__ ships); written iff need = 1, stale otherwise
    ColSpec { name: "obs", dtype: Dtype::F32, dir: Dir::Out, per_env: true, row_elems: SIDES * OBS_DIM, owner: "0" },
    // `present::mask` — the side's 11-dim legal-action mask; written iff need = 1
    ColSpec { name: "mask", dtype: Dtype::U8, dir: Dir::Out, per_env: true, row_elems: SIDES * ACT, owner: "0" },
    // 1 iff the caller must supply this side's action at the next STEP (a decision is open)
    ColSpec { name: "need", dtype: Dtype::U8, dir: Dir::Out, per_env: true, row_elems: SIDES, owner: "0" },
    // the win indicator from p1's view (+1 / -1 / 0 tie) of an episode that ENDED this op; 0 otherwise and 0 for a quarantined battle
    ColSpec { name: "reward", dtype: Dtype::F32, dir: Dir::Out, per_env: true, row_elems: 1, owner: "0" },
    // 1 iff an episode ended this op (its end, or a quarantine); the env has auto-reset, so obs / mask / need already describe the NEXT episode's first decision (EnvPool semantics)
    ColSpec { name: "done", dtype: Dtype::U8, dir: Dir::Out, per_env: true, row_elems: 1, owner: "0" },
    // 1 iff the episode that ended this op was QUARANTINED (a core refusal; its input log is banked)
    ColSpec { name: "refused", dtype: Dtype::U8, dir: Dir::Out, per_env: true, row_elems: 1, owner: "0" },
    // the env's 0-based episode ordinal of the battle obs / need describe (it moves on every start)
    ColSpec { name: "episode", dtype: Dtype::U32, dir: Dir::Out, per_env: true, row_elems: 1, owner: "0" },
    // the index of the side's open decision among its decisions in this battle — sim_bridge's __OBS__ `n`, the alignment key; valid iff need = 1
    ColSpec { name: "dec_n", dtype: Dtype::U32, dir: Dir::Out, per_env: true, row_elems: SIDES, owner: "0" },
    // the battle's turn after the op
    ColSpec { name: "turn", dtype: Dtype::U32, dir: Dir::Out, per_env: true, row_elems: 1, owner: "0" },
    // pool counters, indexed by `protocol.COUNTERS` (the `*_AFTER_FREEZE` ones must stay 0)
    ColSpec { name: "counters", dtype: Dtype::U64, dir: Dir::Out, per_env: false, row_elems: NCOUNTERS, owner: "0" },
];

/// Bytes of every column for a pool of `n` envs.
pub const fn col_bytes(n: usize) -> [usize; N_COLUMNS] {
    let mut out = [0usize; N_COLUMNS];
    let mut i = 0;
    while i < N_COLUMNS {
        let c = COLUMNS[i];
        out[i] = c.row_elems * c.dtype.size() * if c.per_env { n } else { 1 };
        i += 1;
    }
    out
}

/// The caller's column addresses, in table order (plain integers: `Send`, `Copy`, comparable —
/// the frozen binding is one of these). Only `core::pool` turns them back into slices.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ColAddrs(pub [usize; N_COLUMNS]);

/// One env's view of every PER-ENV column (inputs shared, outputs exclusive).
pub struct EnvCols<'a> {
    pub action: &'a [i32],
    pub ep_team: &'a [u32],
    pub ep_seed: &'a [u32],
    pub obs: &'a mut [f32],
    pub mask: &'a mut [u8],
    pub need: &'a mut [u8],
    pub reward: &'a mut [f32],
    pub done: &'a mut [u8],
    pub refused: &'a mut [u8],
    pub episode: &'a mut [u32],
    pub dec_n: &'a mut [u32],
    pub turn: &'a mut [u32],
}

impl ColAddrs {
    /// Env `i`'s rows.
    ///
    /// # Safety
    /// Every address holds its column for a pool of `n > i` envs, alive, aligned and unaliased by
    /// anything but other envs' rows for the duration of the borrow; distinct `i` give disjoint
    /// output slices.
    pub unsafe fn env<'a>(&self, i: usize) -> EnvCols<'a> {
        EnvCols {
            action: std::slice::from_raw_parts((self.0[0] as *const i32).add(i * COLUMNS[0].row_elems), COLUMNS[0].row_elems),
            ep_team: std::slice::from_raw_parts((self.0[1] as *const u32).add(i * COLUMNS[1].row_elems), COLUMNS[1].row_elems),
            ep_seed: std::slice::from_raw_parts((self.0[2] as *const u32).add(i * COLUMNS[2].row_elems), COLUMNS[2].row_elems),
            obs: std::slice::from_raw_parts_mut((self.0[3] as *mut f32).add(i * COLUMNS[3].row_elems), COLUMNS[3].row_elems),
            mask: std::slice::from_raw_parts_mut((self.0[4] as *mut u8).add(i * COLUMNS[4].row_elems), COLUMNS[4].row_elems),
            need: std::slice::from_raw_parts_mut((self.0[5] as *mut u8).add(i * COLUMNS[5].row_elems), COLUMNS[5].row_elems),
            reward: std::slice::from_raw_parts_mut((self.0[6] as *mut f32).add(i * COLUMNS[6].row_elems), COLUMNS[6].row_elems),
            done: std::slice::from_raw_parts_mut((self.0[7] as *mut u8).add(i * COLUMNS[7].row_elems), COLUMNS[7].row_elems),
            refused: std::slice::from_raw_parts_mut((self.0[8] as *mut u8).add(i * COLUMNS[8].row_elems), COLUMNS[8].row_elems),
            episode: std::slice::from_raw_parts_mut((self.0[9] as *mut u32).add(i * COLUMNS[9].row_elems), COLUMNS[9].row_elems),
            dec_n: std::slice::from_raw_parts_mut((self.0[10] as *mut u32).add(i * COLUMNS[10].row_elems), COLUMNS[10].row_elems),
            turn: std::slice::from_raw_parts_mut((self.0[11] as *mut u32).add(i * COLUMNS[11].row_elems), COLUMNS[11].row_elems),
        }
    }

    /// The pool column `counters`.
    ///
    /// # Safety
    /// As [`ColAddrs::env`], and no env borrow reaches this column.
    pub unsafe fn counters<'a>(&self) -> &'a mut [u64] {
        std::slice::from_raw_parts_mut(self.0[12] as *mut u64, COLUMNS[12].row_elems)
    }
}
