"""HodgeRank — splitting a win matrix into a transitive SPINE and a cyclic WIDTH.

WHY THIS EXISTS
---------------
``elo.py`` fits a scalar rating. A scalar rating is a *transitive* model by
construction: it asserts that the whole matrix is generated by one number per player.
Real strategy games are only mostly transitive — a stall team farms one archetype and
folds to another — so the fit leaves a residue, and a Bradley-Terry fit is structurally
blind to it (two snapshots with identical ELO can have a lopsided head-to-head).
``snapshot_ladder``'s ``fit_quality.mean_abs_err`` already NOTICES that residue, but it
reports it as one unitless number with no noise floor, so it cannot answer the only
question that matters: **is the non-transitivity real, or is it sampling noise on 100-game
edges?**

This module answers that. It decomposes the measured comparison graph into

    Y  =  (r_i - r_j)   +   R
    ─      ───────────       ─
  flow    TRANSITIVE       CYCLIC
          (the spine)      (the width)

and then measures the width against the noise floor its own game counts imply.

THE MATH (HodgeRank; Jiang-Lim-Yao-Ye 2011)
-------------------------------------------
Edges carry a **flow**. For a played pair (i, j) with ``n_ij`` games and empirical win
rate ``p_ij`` (Laplace-smoothed to ``(w+½)/(n+1)`` so a 100-0 record stays finite):

    Y_ij = logit(p_ij),      antisymmetric:  Y_ji = -Y_ij
    w_ij = n_ij · p_ij · (1-p_ij)        [the Fisher information of a logit]

``w_ij`` is the natural weight: ``Var(Y_ij) ≈ 1/w_ij``, so weighting by ``w`` puts every
edge on the same footing regardless of how many games it got or how lopsided it was.

**Transitive part** — weighted least squares for ratings ``r``:

    minimize  Σ_ij w_ij · (Y_ij - (r_i - r_j))²

whose normal equations are the weighted **graph Laplacian** solve ``L r = b``. This is
HodgeRank's *gradient* component. It is Bradley-Terry's quadratic cousin: same logit link,
but a Gaussian (least-squares) loss on the logits instead of the binomial likelihood, and
no prior. On dense, well-sampled data the two agree to a few ELO; they diverge exactly
where the likelihood curvature and the plug-in weight disagree — near-perfect edges, and
players whose edges are few. **Both are reported** so the difference is visible rather
than assumed away.

**Cyclic part** — the residual ``R_ij = Y_ij - (r_i - r_j)``. On a COMPLETE graph this is
the full curl+harmonic component of the Hodge decomposition. On an INCOMPLETE graph it is
"everything a rating cannot explain" — which may include curl, harmonic flow, *and*
whatever structure the missing edges would have resolved. That looser reading is the
honest one and is the one used here.

**Orthogonality.** The normal equations force ``Σ_j w_ij R_ij = 0`` at every node, so the
two parts are orthogonal in the ``w`` inner product and the energies add exactly:

    Σ w·Y²  =  Σ w·(r_i - r_j)²  +  Σ w·R²

(pinned by ``hodge_test.py``; it holds on any graph, and on a complete graph it is the
textbook Hodge split).

THE NOISE FLOOR (the part that makes this an instrument, not a number)
----------------------------------------------------------------------
A residual RMS of 0.4 logits means nothing on its own — 100-game edges have a logit SE of
~0.2 to ~1.0 all by themselves, and the least-squares fit *cannot* absorb it. Two nulls,
both reported:

* **plug-in / analytic** — under a pure-transitive truth with binomial noise,
  ``E[Σ_S w·R²] = Σ_S (1 - w_e·Reff_e)`` exactly, where ``Reff_e`` is the effective
  resistance of edge ``e`` in the ``w``-weighted graph (this is the per-edge form of
  ``E - V + C`` by Foster's theorem — see ``_null_moments``). A Satterthwaite-matched
  chi-square gives an analytic p-value with no bootstrap.
* **parametric bootstrap** — simulate games from the FITTED transitive model
  (``Binomial(n_ij, σ(r_i - r_j))``), re-run the entire pipeline including the smoothing
  and the re-weighting, and collect the null width distribution. This is the primary null
  because it goes through every step the observed number went through.

Reported: ``width_rms_excess = sqrt(max(0, raw² - null²))`` — the width that survives its
own noise floor — plus a p-value for "width > noise".

WIDTH SCOPE (why not every edge)
--------------------------------
A **pendant** edge — a player with exactly one measured opponent — has residual
*identically zero*, because that player's normal equation is that single edge. Including
such edges does not add information; it just inflates the denominator and deflates the
RMS toward zero. More generally, only edges lying on a measured triangle can express a
cycle. So the width statistics default to the **triangle-supported subgraph**
(``width_scope="triangles"``), and the caller may further restrict to edges incident to a
chosen player (``width_incident_to`` — the live metric uses this to mean "the trainee's
matchup deviation", not the static anchor's). The spine is always fit over ALL edges;
only the width CLAIM is scoped. ``n_triangles`` and the scope size are reported so a
width read can never be quoted without its support.

Units: 1 logit = ``ELO_PER_LOGIT`` = 400/ln(10) ≈ 173.72 ELO, the same convention
``elo.py`` uses (``P = σ(ΔELO · ln10/400)``).

numpy-only (like ``elo.py``) so it imports cleanly into the live eval callback.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field

import numpy as np

from agents.training import elo as elo_mod

# 1 logit of flow = this many ELO points (the inverse of elo._S).
ELO_PER_LOGIT = elo_mod.ELO_PER_DECADE / math.log(10.0)   # ≈ 173.7178

# Defaults for the significant-cycle filter. `EDGE_Z` is the literal "each edge's deviation
# clears its per-edge noise floor" (1 SE); `CYCLE_Z` is the joint test that the LOOP itself is
# not noise (the curl, at 95%). Both must pass — a triangle of three individually-noisy legs
# that happen to point round is not a finding.
EDGE_Z = 1.0
CYCLE_Z = 1.96
MAX_CYCLES = 20

DEFAULT_BOOTSTRAP = 200


def label(player_id: str) -> str:
    """Pretty name for a player key: ``snap:12000000`` → ``12.0M``, ``bot:staller`` → ``staller``."""
    if elo_mod.is_snapshot(player_id):
        return f"{elo_mod.snapshot_step(player_id) / 1e6:.1f}M"
    if player_id.startswith(elo_mod.BOT):
        return player_id[len(elo_mod.BOT):]
    return player_id


# ── results ───────────────────────────────────────────────────────────────────


@dataclass
class HodgeCycle:
    """One significant 3-cycle: ``players`` in beat-order (a > b > c > a)."""
    players: tuple[str, str, str]
    win_rates: tuple[float, float, float]   # p(a>b), p(b>c), p(c>a)
    games: tuple[int, int, int]
    curl: float           # Y_ab + Y_bc + Y_ca, logits (0 for a purely transitive triangle)
    curl_se: float
    curl_z: float

    @property
    def curl_elo(self) -> float:
        return self.curl * ELO_PER_LOGIT

    def describe(self) -> str:
        a, b, c = (label(p) for p in self.players)
        return (f"{a} > {b} > {c} > {a}   curl {self.curl:+.3f} logits "
                f"= {self.curl_elo:+.0f} ELO (z={self.curl_z:.1f})")

    def to_json(self) -> dict:
        return {
            "players": list(self.players),
            "labels": [label(p) for p in self.players],
            "win_rates": [round(p, 4) for p in self.win_rates],
            "games": list(self.games),
            "curl": round(self.curl, 4),
            "curl_elo": round(self.curl_elo, 1),
            "curl_z": round(self.curl_z, 2),
        }


@dataclass
class HodgeFit:
    """The decomposition of one comparison graph. Flows/ratings are in LOGITS; every
    ``*_elo`` companion is the same quantity times ``ELO_PER_LOGIT``."""
    players: list[str]
    ratings: dict[str, float]                     # logits, zero-mean gauge (per component)
    n_edges: int
    n_components: int
    n_triangles: int
    width_scope: str
    n_width_edges: int
    spine_spread: float
    width_rms_raw: float
    width_rms_null: float
    width_rms_null_plugin: float
    width_rms_excess: float
    p_value: float | None                          # bootstrap; None when bootstrap disabled
    p_value_plugin: float
    cyclic_energy_fraction: float
    cyclic_energy_fraction_excess: float
    energy_total: float
    energy_transitive: float
    energy_cyclic: float
    cycles: list[HodgeCycle] = field(default_factory=list)
    caveats: list[str] = field(default_factory=list)
    n_bootstrap: int = 0

    @property
    def n_players(self) -> int:
        return len(self.players)

    @property
    def ratings_elo(self) -> dict[str, float]:
        return {p: r * ELO_PER_LOGIT for p, r in self.ratings.items()}

    @property
    def spine_spread_elo(self) -> float:
        return self.spine_spread * ELO_PER_LOGIT

    @property
    def width_rms_raw_elo(self) -> float:
        return self.width_rms_raw * ELO_PER_LOGIT

    @property
    def width_rms_null_elo(self) -> float:
        return self.width_rms_null * ELO_PER_LOGIT

    @property
    def width_rms_excess_elo(self) -> float:
        return self.width_rms_excess * ELO_PER_LOGIT

    def aligned_elo(self, reference: dict[str, float]) -> dict[str, float]:
        """Hodge ratings shifted onto ``reference``'s offset (e.g. the anchored BT ladder).
        Only the OFFSET is free — the scale is pinned by ``ELO_PER_LOGIT`` — so this is a
        display convenience, and the residual spread after shifting IS the BT-vs-WLS
        disagreement. The offset is the MEDIAN difference, not the mean: the two estimators
        diverge most on near-perfect edges (``bot:random``), and a mean offset would let that
        one player's disagreement shift everyone else's."""
        mine = self.ratings_elo
        diffs = sorted(reference[p] - mine[p] for p in mine if p in reference)
        off = float(np.median(diffs)) if diffs else 0.0
        return {p: e + off for p, e in mine.items()}

    def to_json(self) -> dict:
        return {
            "n_players": self.n_players,
            "n_edges": self.n_edges,
            "n_components": self.n_components,
            "n_triangles": self.n_triangles,
            "width_scope": self.width_scope,
            "n_width_edges": self.n_width_edges,
            "n_bootstrap": self.n_bootstrap,
            "spine_spread": round(self.spine_spread, 4),
            "spine_spread_elo": round(self.spine_spread_elo, 1),
            "width_rms_raw": round(self.width_rms_raw, 4),
            "width_rms_raw_elo": round(self.width_rms_raw_elo, 1),
            "width_rms_null": round(self.width_rms_null, 4),
            "width_rms_null_elo": round(self.width_rms_null_elo, 1),
            "width_rms_null_plugin": round(self.width_rms_null_plugin, 4),
            "width_rms_excess": round(self.width_rms_excess, 4),
            "width_rms_excess_elo": round(self.width_rms_excess_elo, 1),
            "p_value": None if self.p_value is None else round(self.p_value, 4),
            "p_value_plugin": round(self.p_value_plugin, 4),
            "cyclic_energy_fraction": round(self.cyclic_energy_fraction, 4),
            "cyclic_energy_fraction_excess": round(self.cyclic_energy_fraction_excess, 4),
            "energy": {"total": round(self.energy_total, 4),
                       "transitive": round(self.energy_transitive, 4),
                       "cyclic": round(self.energy_cyclic, 4)},
            "ratings_elo": {p: round(e, 1) for p, e in sorted(
                self.ratings_elo.items(), key=lambda kv: -kv[1])},
            "cycles": [c.to_json() for c in self.cycles],
            "caveats": list(self.caveats),
        }


# ── the graph ─────────────────────────────────────────────────────────────────


def _build(results):
    """``[(name_a, name_b, wins_a, games), …]`` → interned arrays.

    Aggregation goes through ``elo._aggregate`` — the ONE place the pair-ordering /
    win-flipping convention lives — so the Hodge graph and the BT fit are guaranteed to see
    the same edges with the same orientation."""
    names, _idx, edges = elo_mod._aggregate(results)
    ei, ej, wins, games = [], [], [], []
    for (a, b), (w_lo, g) in sorted(edges.items()):
        if g <= 0:
            continue
        ei.append(a)
        ej.append(b)
        wins.append(w_lo)
        games.append(g)
    return (names,
            np.asarray(ei, dtype=np.int64), np.asarray(ej, dtype=np.int64),
            np.asarray(wins, dtype=np.float64), np.asarray(games, dtype=np.float64))


def _flows(wins_i: np.ndarray, games: np.ndarray):
    """(p, Y, w) for edges oriented i→j. ``p`` is Laplace-smoothed ``(w+½)/(n+1)`` so a
    perfect record gives a large-but-finite logit and a small-but-positive weight."""
    p = (wins_i + 0.5) / (games + 1.0)
    y = np.log(p / (1.0 - p))
    w = games * p * (1.0 - p)
    return p, y, w


def _laplacian_solve(ei, ej, w, y, n_players, l_pinv=None):
    """Weighted least squares for the ratings: the graph-Laplacian normal equations.

    Gauge: ``pinv`` returns the minimum-norm solution, i.e. zero-mean WITHIN each connected
    component (a disconnected graph has one free offset per component and no data to fix it —
    reported as ``n_components`` and a caveat, never silently averaged across)."""
    lap = np.zeros((n_players, n_players))
    np.add.at(lap, (ei, ei), w)
    np.add.at(lap, (ej, ej), w)
    np.add.at(lap, (ei, ej), -w)
    np.add.at(lap, (ej, ei), -w)
    b = np.zeros(n_players)
    np.add.at(b, ei, w * y)
    np.add.at(b, ej, -(w * y))
    if l_pinv is None:
        l_pinv = np.linalg.pinv(lap)
    return l_pinv @ b, lap, l_pinv


def _components(ei, ej, n_players) -> int:
    parent = list(range(n_players))

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    for a, b in zip(ei.tolist(), ej.tolist()):
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[ra] = rb
    return len({find(i) for i in range(n_players)})


def _triangles(ei, ej, n_players):
    """Every measured triangle as ``(i, j, k)`` with ``i<j<k``, plus the set of edge indices
    that lie on at least one of them."""
    edge_of: dict[tuple[int, int], int] = {}
    adj: dict[int, set[int]] = {i: set() for i in range(n_players)}
    for e, (a, b) in enumerate(zip(ei.tolist(), ej.tolist())):
        edge_of[(a, b)] = e
        adj[a].add(b)
        adj[b].add(a)
    tris: list[tuple[int, int, int, int, int, int]] = []   # i,j,k + the 3 edge indices
    on_tri: set[int] = set()
    for (a, b), e_ab in edge_of.items():
        for c in sorted(adj[a] & adj[b]):
            if c <= b:
                continue          # enumerate each triangle once, as a<b<c
            e_ac = edge_of.get((a, c)) if (a, c) in edge_of else edge_of.get((c, a))
            e_bc = edge_of.get((b, c)) if (b, c) in edge_of else edge_of.get((c, b))
            if e_ac is None or e_bc is None:
                continue
            tris.append((a, b, c, e_ab, e_ac, e_bc))
            on_tri.update((e_ab, e_ac, e_bc))
    return tris, on_tri


# ── the null ──────────────────────────────────────────────────────────────────


def _null_moments(ei, ej, w, l_pinv, scope_mask):
    """Exact mean and variance of ``T = Σ_scope w·R²`` under a pure-transitive truth with
    binomial noise (the plug-in null), from the residual covariance in closed form.

    With incidence ``B`` and ``W = diag(w)``, the fit is ``R = (I - P)Y``,
    ``P = B(BᵀWB)⁺BᵀW``. Under ``Cov(Y) = W⁻¹`` this collapses to

        Cov(R) = W⁻¹ - B L⁺ Bᵀ

    whose diagonal is ``1/w_e - Reff_e`` (effective resistance). Hence
    ``E[T] = Σ_scope (1 - w_e·Reff_e)`` — which sums over ALL edges to ``E - V + C``
    (Foster's theorem), the familiar residual degrees of freedom. The variance comes from
    ``2·tr((W_S Σ)²)`` for the Satterthwaite match."""
    n_e = len(ei)
    # M = B L⁺ Bᵀ  (E×E) — E is small (hundreds at most on any ladder we fit).
    li = l_pinv[np.ix_(ei, ei)]
    lj = l_pinv[np.ix_(ej, ej)]
    lij = l_pinv[np.ix_(ei, ej)]
    m = li + lj - lij - lij.T
    sigma = np.diag(1.0 / w) - m
    ws = np.where(scope_mask, w, 0.0)
    c = ws[:, None] * sigma                       # W_S Σ
    mean = float(np.trace(c))
    var = float(2.0 * np.trace(c @ c))
    per_edge = 1.0 - w * np.diag(m)               # E[w_e R_e²] per edge
    return mean, max(var, 0.0), per_edge, n_e


def _chi2_sf(x: float, df: float) -> float:
    """P(χ²_df > x) via the Wilson-Hilferty cube-root normal approximation (accurate to
    ~1e-3 over the range we quote, and keeps this module numpy-only — no scipy)."""
    if df <= 0:
        return 1.0
    if x <= 0:
        return 1.0
    z = ((x / df) ** (1.0 / 3.0) - (1.0 - 2.0 / (9.0 * df))) / math.sqrt(2.0 / (9.0 * df))
    return 0.5 * math.erfc(z / math.sqrt(2.0))


# ── the decomposition ─────────────────────────────────────────────────────────


def hodge_decompose(
    results,
    *,
    width_scope: str = "triangles",
    width_incident_to: "set[str] | None" = None,
    bootstrap: int = DEFAULT_BOOTSTRAP,
    seed: int = 0,
    max_cycles: int = MAX_CYCLES,
    edge_z: float = EDGE_Z,
    cycle_z: float = CYCLE_Z,
) -> "HodgeFit | None":
    """Decompose a set of pairwise results into a transitive spine and a cyclic width.

    ``results`` is ``[(name_a, name_b, wins_a, games), …]`` — the SAME shape
    ``elo.fit_pairwise`` consumes, so any caller that can fit a ladder can decompose it.

    ``width_scope``: ``"triangles"`` (default — only edges on a measured triangle can express
    a cycle, and a pendant edge's residual is identically zero) or ``"all"``.
    ``width_incident_to``: further restrict the width statistics to edges touching one of
    these players (the live metric passes the trainee, so the number means "the TRAINEE's
    matchup deviation" and not the static anchor's).

    ``bootstrap``: parametric-bootstrap replicates for the null (0 disables → the plug-in
    null and its analytic p-value still stand). ``seed`` makes it deterministic.

    Returns ``None`` when there is no graph to decompose (no edges, or an empty width scope);
    a caller emitting a metric MUST treat that as "omit", never as zero."""
    names, ei, ej, wins, games = _build(results)
    n_p = len(names)
    n_e = len(ei)
    if n_p < 2 or n_e == 0:
        return None

    caveats: list[str] = []
    p_hat, y, w = _flows(wins, games)
    r, _lap, l_pinv = _laplacian_solve(ei, ej, w, y, n_p)
    resid = y - (r[ei] - r[ej])

    n_comp = _components(ei, ej, n_p)
    if n_comp > 1:
        caveats.append(f"graph has {n_comp} disconnected components — ratings are gauge-fixed "
                       f"independently per component, so the spine spread is not a single scale")

    tris, on_tri = _triangles(ei, ej, n_p)
    scope = np.ones(n_e, dtype=bool) if width_scope == "all" else np.array(
        [e in on_tri for e in range(n_e)], dtype=bool)
    if width_incident_to:
        want = {i for i, nm in enumerate(names) if nm in width_incident_to}
        scope &= np.array([(a in want or b in want)
                           for a, b in zip(ei.tolist(), ej.tolist())], dtype=bool)
    if not scope.any():
        return None

    ws = w[scope]
    rs = resid[scope]
    t_obs = float(np.sum(ws * rs * rs))
    sum_w = float(np.sum(ws))
    width_raw = math.sqrt(t_obs / sum_w) if sum_w > 0 else 0.0

    # Energies over the width scope (the split is orthogonal on ANY graph, so these add).
    grad_s = (r[ei] - r[ej])[scope]
    e_total = float(np.sum(ws * y[scope] ** 2))
    e_trans = float(np.sum(ws * grad_s ** 2))
    e_cyc = t_obs

    # ── null 1: plug-in (exact mean, Satterthwaite chi-square for the p-value)
    mean_t, var_t, _per_edge, _ = _null_moments(ei, ej, w, l_pinv, scope)
    mean_t = max(mean_t, 0.0)
    width_plugin = math.sqrt(mean_t / sum_w) if sum_w > 0 else 0.0
    if var_t > 0 and mean_t > 0:
        scale = var_t / (2.0 * mean_t)
        df = 2.0 * mean_t * mean_t / var_t
        p_plugin = _chi2_sf(t_obs / scale, df)
    else:
        p_plugin = 1.0

    # ── null 2: parametric bootstrap through the WHOLE pipeline (primary)
    p_boot: float | None = None
    width_null = width_plugin
    n_boot = 0
    if bootstrap and bootstrap > 0:
        rng = np.random.default_rng(seed)
        p_model = 1.0 / (1.0 + np.exp(-(r[ei] - r[ej])))
        n_int = games.astype(np.int64)
        null_t = np.empty(bootstrap)
        null_width = np.empty(bootstrap)
        for b in range(bootstrap):
            sim_wins = rng.binomial(n_int, p_model).astype(np.float64)
            _p, y_b, w_b = _flows(sim_wins, games)
            r_b, _l, _lp = _laplacian_solve(ei, ej, w_b, y_b, n_p)
            res_b = y_b - (r_b[ei] - r_b[ej])
            wb_s = w_b[scope]
            t_b = float(np.sum(wb_s * res_b[scope] ** 2))
            null_t[b] = t_b
            sw = float(np.sum(wb_s))
            null_width[b] = math.sqrt(t_b / sw) if sw > 0 else 0.0
        n_boot = int(bootstrap)
        # +1 on both sides: a bootstrap p-value can never be exactly 0 (Davison-Hinkley).
        p_boot = float((1.0 + np.sum(null_t >= t_obs)) / (bootstrap + 1.0))
        width_null = float(np.mean(null_width))
        mean_t = float(np.mean(null_t))

    excess = math.sqrt(max(0.0, width_raw ** 2 - width_null ** 2))
    frac = (e_cyc / e_total) if e_total > 0 else 0.0
    frac_excess = (max(0.0, e_cyc - mean_t) / e_total) if e_total > 0 else 0.0

    # ── significant 3-cycles
    cycles = _significant_cycles(names, ei, ej, p_hat, y, w, games, resid, tris,
                                 edge_z, cycle_z, max_cycles)

    if not tris:
        caveats.append("no measured triangle — a graph with no closed loop cannot express a "
                       "cycle, so the width is not a testable quantity here")
    if int(scope.sum()) < n_e:
        caveats.append(f"width measured over {int(scope.sum())}/{n_e} edges "
                       f"(scope={width_scope}"
                       + (", incident-restricted" if width_incident_to else "") + ")")

    return HodgeFit(
        players=list(names),
        ratings={names[i]: float(r[i]) for i in range(n_p)},
        n_edges=n_e,
        n_components=n_comp,
        n_triangles=len(tris),
        width_scope=width_scope,
        n_width_edges=int(scope.sum()),
        spine_spread=float(r.max() - r.min()),
        width_rms_raw=width_raw,
        width_rms_null=width_null,
        width_rms_null_plugin=width_plugin,
        width_rms_excess=excess,
        p_value=p_boot,
        p_value_plugin=p_plugin,
        cyclic_energy_fraction=frac,
        cyclic_energy_fraction_excess=frac_excess,
        energy_total=e_total,
        energy_transitive=e_trans,
        energy_cyclic=e_cyc,
        cycles=cycles,
        caveats=caveats,
        n_bootstrap=n_boot,
    )


def _significant_cycles(names, ei, ej, p_hat, y, w, games, resid, tris,
                        edge_z, cycle_z, max_cycles):
    """Triangles that are (1) **sign-cyclic** — A beats B beats C beats A, i.e. all three
    flows point the same way round the loop, so every node has exactly one win — (2) whose
    every leg's deviation clears its own per-edge noise floor ``|R_e| > z/√w_e``, and (3)
    whose **curl** clears the joint floor ``|Y_ab + Y_bc + Y_ca| > z·√(Σ 1/w_e)``.

    All three, because each alone lies: (1) is cheap to satisfy by luck on near-50% edges;
    (3) can fire on a triangle that is not even sign-cyclic (a strong-but-mismeasured
    transitive triple). Ranked by |curl z|, capped at ``max_cycles``."""
    out: list[HodgeCycle] = []
    for (a, b, c, e_ab, e_ac, e_bc) in tris:
        legs = (e_ab, e_bc, e_ac)                  # a→b, b→c, c→a
        ends = ((a, b), (b, c), (c, a))
        flows = [_oriented(y, ei, e, frm) for e, (frm, _to) in zip(legs, ends)]
        forward = flows[0] > 0
        if not all((f > 0) == forward for f in flows):
            continue                               # transitive sign pattern — not a cycle
        if not all(abs(resid[e]) > edge_z / math.sqrt(w[e]) for e in legs):
            continue
        curl = float(sum(flows))
        se = math.sqrt(sum(1.0 / w[e] for e in legs))
        z = curl / se if se > 0 else 0.0
        if abs(z) < cycle_z:
            continue
        # Name the loop in BEAT order. Forward = a>b>c>a; otherwise the loop runs backwards,
        # which is the same triangle read as a>c>b>a.
        if forward:
            order, oriented = (a, b, c), [(e_ab, a), (e_bc, b), (e_ac, c)]
        else:
            order, oriented = (a, c, b), [(e_ac, a), (e_bc, c), (e_ab, b)]
        out.append(HodgeCycle(
            players=(names[order[0]], names[order[1]], names[order[2]]),
            win_rates=tuple(_oriented(p_hat, ei, e, frm, complement=True)   # type: ignore[arg-type]
                            for e, frm in oriented),
            games=tuple(int(games[e]) for e, _frm in oriented),             # type: ignore[arg-type]
            curl=abs(curl), curl_se=se, curl_z=abs(z)))
    out.sort(key=lambda c: -c.curl_z)
    return out[:max_cycles]


def _oriented(vals, ei, e, frm, complement: bool = False) -> float:
    """Edge quantity read in the direction ``frm → other``. Flows negate when reversed; win
    rates take the complement (``complement=True``)."""
    if ei[e] == frm:
        return float(vals[e])
    return float(1.0 - vals[e]) if complement else float(-vals[e])


# ── edge builders ─────────────────────────────────────────────────────────────


def anchor_round_robin_edges(anchors: dict | None,
                             prior_games: int = 2000) -> tuple[list, list[str]]:
    """The static bot-vs-bot round-robin as pairwise results, plus any caveats.

    ``data/gen3_bot_elo_anchors.json`` DOES store the raw matrix (a 9×9 ``win_matrix`` and a
    ``pair_games`` count per pair), so the real measured edges are used: ``n`` from
    ``pair_games`` and ``p`` from the two matrix halves averaged
    (``(p_ab + (1-p_ba))/2`` — they need not sum to 1, since unfinished battles are dropped
    from each side independently).

    FALLBACK, and it changes the meaning: if a future anchor file carries only ``ratings``,
    the bot edges are RECONSTRUCTED from those ratings as ``p = σ(ΔR)`` with a synthetic
    ``prior_games`` count. Reconstructed edges are transitive BY CONSTRUCTION — they carry
    zero residual and act purely as a high-confidence prior that pins the bot frame — so any
    width measured over a graph containing them is entirely the OTHER players' deviation.
    That is flagged in the returned caveats."""
    if not anchors or not anchors.get("ratings"):
        return [], ["no bot anchors — the bot frame is unpinned"]
    ratings = anchors["ratings"]
    matrix = anchors.get("win_matrix") or {}
    pair_games = anchors.get("pair_games") or {}
    out: list[tuple[str, str, int, int]] = []
    caveats: list[str] = []
    if matrix and pair_games:
        seen: set[tuple[str, str]] = set()
        for a, row in matrix.items():
            for b, p_ab in row.items():
                key = (a, b) if a < b else (b, a)
                if key in seen or a == b:
                    continue
                n = pair_games.get(f"{key[0]} vs {key[1]}")
                if n is None:
                    n = pair_games.get(f"{key[1]} vs {key[0]}")
                if not n:
                    continue
                seen.add(key)
                p_ba = (matrix.get(b) or {}).get(a)
                p = float(p_ab) if p_ba is None else 0.5 * (float(p_ab) + 1.0 - float(p_ba))
                p = min(max(p, 0.0), 1.0)
                if key[0] != a:
                    p = 1.0 - p
                out.append((elo_mod.bot_key(key[0]), elo_mod.bot_key(key[1]),
                            int(round(p * int(n))), int(n)))
        return out, caveats
    # Reconstruction fallback — see the docstring.
    caveats.append(f"anchor file has no win_matrix/pair_games; bot edges RECONSTRUCTED from "
                   f"anchor ratings at {prior_games} synthetic games — they are transitive by "
                   f"construction and act as a pinning prior, contributing no width of their own")
    bots = sorted(ratings)
    for i, a in enumerate(bots):
        for b in bots[i + 1:]:
            p = elo_mod.win_prob(float(ratings[a]), float(ratings[b]))
            out.append((elo_mod.bot_key(a), elo_mod.bot_key(b),
                        int(round(p * prior_games)), int(prior_games)))
    return out, caveats


def cycle_edges(step: int, bot_win_rates: dict, sentinels, n_games: int,
                bot_counts: dict | None = None,
                anchors: dict | None = None) -> tuple[list, str, list[str]]:
    """The LIVE graph for one eval cycle: the trainee's star **joined to the static bot
    round-robin**, which is the only thing that closes a triangle.

    A cycle's own new games are a STAR (trainee vs each opponent). A star is a tree; a tree
    has no cycles; so a width measured on the cycle's games alone would be identically zero —
    a fake instrument. The bot-vs-bot round-robin supplies the bot-side edges, and the
    trainee×bot×bot triangles they close are what the live width actually reads.

    Sentinel edges (trainee-vs-sentinel only) are INCLUDED in the fit — they carry real spine
    information — but they lie on no triangle, so the default width scope drops them. Their
    residual is identically zero anyway (a pendant edge's node equation is that one edge), so
    including them in a width claim would only deflate it.

    Returns ``(results, trainee_key, caveats)``."""
    subj = elo_mod.snap_key(int(step))
    results: list[tuple[str, str, int, int]] = []
    for name, wr in (bot_win_rates or {}).items():
        if bot_counts and name in bot_counts:
            won, fin = int(bot_counts[name][0]), int(bot_counts[name][1])
        else:
            fin = int(n_games)
            won = int(round(float(wr) * fin))
        if fin > 0:
            results.append((subj, elo_mod.bot_key(name), won, fin))
    for s in (sentinels or []):
        try:
            s_step, wr = int(s["step"]), float(s["win_rate"])
        except (KeyError, TypeError, ValueError):
            continue
        n = int(n_games)
        if n > 0:
            results.append((subj, elo_mod.snap_key(s_step), int(round(wr * n)), n))
    rr, caveats = anchor_round_robin_edges(anchors)
    results.extend(rr)
    return results, subj, caveats


def edges_from_run(run_dir: str, *, source: str = "auto", with_bot_rr: bool = False,
                   anchors_path: str = elo_mod.BOT_ANCHORS_PATH) -> tuple[list, list[str]]:
    """The OFFLINE graph for a run — exactly the edge set ``snapshot_ladder.fit_ladder``
    fits, so the width is measured over the same graph the ELO gate is read from:

    1. the DENSE frozen snapshot-vs-snapshot matrix (``snapshot_ladder/games.jsonl``), and
    2. every cycle's trainee-vs-bot and trainee-vs-sentinel edges (``eval_results.jsonl``).

    ``with_bot_rr`` additionally folds in the static bot-vs-bot round-robin. It is OFF by
    default and that is a judgment call worth stating: those 36 edges carry ~2700 games each
    against a ladder edge's 100, so on the Fisher weighting they would carry ~99% of Σw and
    the reported width would become a property of the (immutable, shared-across-runs) bot
    anchor rather than of this run's ladder. Turn it on to read the bots' own cycles."""
    results: list[tuple[str, str, int, int]] = []
    caveats: list[str] = []
    try:
        from agents.training import snapshot_ladder as ladder_mod
        for (lo, hi), (wins_lo, g) in ladder_mod.load_games(run_dir).items():
            if g > 0:
                results.append((elo_mod.snap_key(lo), elo_mod.snap_key(hi), wins_lo, g))
    except Exception as e:  # noqa: BLE001 — a run may have no dense ladder at all
        caveats.append(f"no dense frozen ladder ({type(e).__name__})")
    n_dense = len(results)
    if n_dense == 0:
        caveats.append("no snapshot_ladder/games.jsonl — the graph is the SPARSE live one "
                       "(trainee stars + sentinel edges); triangles exist only where a "
                       "sentinel edge coincides with a rated snapshot")
    for na, nb, wa, g in elo_mod._rows_to_results(elo_mod.load_rows(run_dir, source)):
        if g > 0:
            results.append((na, nb, wa, g))
    if with_bot_rr:
        rr, rr_cav = anchor_round_robin_edges(elo_mod.load_bot_anchors(anchors_path))
        results.extend(rr)
        caveats.extend(rr_cav)
        caveats.append("bot round-robin edges INCLUDED — they dominate Σw, so the width is "
                       "mostly the bot anchor's own non-transitivity")
    return results, caveats


def decompose_run(run_dir: str, *, source: str = "auto", with_bot_rr: bool = False,
                  anchors_path: str = elo_mod.BOT_ANCHORS_PATH,
                  bootstrap: int = DEFAULT_BOOTSTRAP, seed: int = 0,
                  max_cycles: int = MAX_CYCLES) -> "HodgeFit | None":
    """Convenience: build a run's ladder graph and decompose it. ``None`` when the run has no
    comparison graph yet."""
    results, caveats = edges_from_run(run_dir, source=source, with_bot_rr=with_bot_rr,
                                      anchors_path=anchors_path)
    fit = hodge_decompose(results, bootstrap=bootstrap, seed=seed, max_cycles=max_cycles)
    if fit is not None:
        fit.caveats = caveats + fit.caveats
    return fit


LIVE_BOOTSTRAP = 60

# The two live scalars. TWO, deliberately: a per-opponent series here would be per-opponent
# NOISE (one cycle's edge is ~100 games), and the per-opponent story is the offline read's job.
WIDTH_TAG = "eval/hodge_width_elo"
FRACTION_TAG = "eval/hodge_cyclic_fraction"


def live_read(step: int, bot_win_rates: dict, sentinels, n_games: int,
              bot_counts: dict | None = None,
              anchors_path: str = elo_mod.BOT_ANCHORS_PATH,
              bootstrap: int = LIVE_BOOTSTRAP, seed: int = 0) -> "HodgeFit | None":
    """The per-eval-cycle read: the trainee's matchup deviation from its own rating, measured
    over trainee×bot×bot triangles.

    ⚠️ This is the WEAK instrument by construction — one cycle's edges are ~100 games each,
    so the noise floor is large and only a gross cyclic profile clears it. The real width
    instrument is the offline dense-ladder read (``decompose_run`` / ``python -m main.elo``).
    Returns ``None`` when the graph has no testable triangle — the caller must then OMIT the
    metric (never record 0, never record NaN)."""
    anchors = elo_mod.load_bot_anchors(anchors_path)
    results, subj, caveats = cycle_edges(step, bot_win_rates, sentinels, n_games,
                                         bot_counts=bot_counts, anchors=anchors)
    fit = hodge_decompose(results, width_incident_to={subj}, bootstrap=bootstrap, seed=seed)
    if fit is None or fit.n_triangles == 0:
        return None
    fit.caveats = caveats + fit.caveats
    return fit


def record_live_hodge(logger, step: int, bot_win_rates: dict, sentinels, n_games: int, *,
                      bot_counts: dict | None = None,
                      anchors_path: str = elo_mod.BOT_ANCHORS_PATH,
                      bootstrap: int = LIVE_BOOTSTRAP, seed: int = 0) -> dict:
    """Record the two live scalars beside ``eval/elo`` and return the ``eval_results.jsonl``
    ``hodge`` block.

    * ``eval/hodge_width_elo`` — the EXCESS width (raw² − null², floored at 0) in ELO points:
      how far the trainee's matchup profile departs from what a single rating predicts, over
      and above what its own ~100-game edges could produce by chance.
    * ``eval/hodge_cyclic_fraction`` — the null-adjusted share of the trainee's flow energy
      that a rating cannot explain.

    **What it does NOT measure**: the width of the whole pool. This cycle's games are a STAR;
    the triangles come from joining them to the static bot round-robin, so the metric is
    "trainee×bot×bot" and nothing else. Sentinel edges enter the FIT (real spine information)
    but lie on no triangle and are excluded from the width scope.

    The block is ALWAYS returned (``recorded: false`` + a caveat when the graph has no
    testable triangle) so an offline reader can count the omissions; the scalars are recorded
    only when the number is real and finite — never 0-as-a-stand-in, never NaN. Best-effort:
    telemetry may not break eval."""
    try:
        fit = live_read(step, bot_win_rates, sentinels, n_games, bot_counts=bot_counts,
                        anchors_path=anchors_path, bootstrap=bootstrap, seed=seed)
    except Exception as e:  # noqa: BLE001 — telemetry; never break eval
        return {"recorded": False, "caveats": [f"hodge read failed: {type(e).__name__}: {e}"]}
    if fit is None:
        return {"recorded": False,
                "caveats": ["no testable triangle — the cycle's own games are a star, and no "
                            "bot round-robin edges were available to close one"]}
    width = fit.width_rms_excess_elo
    frac = fit.cyclic_energy_fraction_excess
    if not (math.isfinite(width) and math.isfinite(frac)):
        return {"recorded": False, "caveats": ["non-finite width — record omitted"]}
    if logger is not None:
        logger.record(WIDTH_TAG, float(width))
        logger.record(FRACTION_TAG, float(frac))
    return {
        "recorded": True,
        "width_elo": round(float(width), 2),
        "cyclic_fraction": round(float(frac), 4),
        "width_raw_elo": round(fit.width_rms_raw_elo, 2),
        "width_null_elo": round(fit.width_rms_null_elo, 2),
        "p_value": None if fit.p_value is None else round(fit.p_value, 4),
        "n_triangles": fit.n_triangles,
        "n_width_edges": fit.n_width_edges,
        "caveats": list(fit.caveats),
    }
