"""Materialize the agent's ONE-SIDED observations from a battle's replayed protocol.

The forensic ``states.npz`` saves the obs vectors of states that *happened*; it
cannot score a counterfactual (a re-rolled turn), and the encoder's stateful
trackers (HiddenPowerTracker, ability/usage narrowing, the turn-history deltas,
the progress clock) are not recoverable from the flat output vector. The way
to get the obs of ANY point — recorded or re-rolled — is to replay the one-sided
protocol stream through the *real* obs pipeline from battle start, rebuilding
the tracker state exactly as the live player did. That replay is what this
module does.

**The one-sided / omniscient wall (hard requirement).** Input here is only the
per-side protocol chunks regenerated by ``utils.bridge.reconstruction``
(:func:`replay_battle` / :func:`reroll_turn`) — the exact bytes the live agent
saw. The omniscient reconstruction data (seed, both teams, dice) never enters
this module; the encoder reads the same partial poke-env view it reads live.

Fidelity contract
-----------------
``_ReplayObsPlayer`` mirrors the live eval decision cadence
(``EvalRLPlayer.choose_move`` → ``RLPlayer._predict_best_action``) exactly:

1. stall check first (same default :class:`StallConfig`, threshold 250 — the
   forfeit order goes nowhere, the recorded FORCELOSE in the replayed protocol
   ends the battle identically);
2. ``embed_battle`` (which records the decision context, updates the
   HiddenPowerTracker and the progress clock, and encodes the obs);
3. an all-zero mask ⇒ no decision (no row, no tracker advance) — the live
   ``idx is None`` deferral;
4. otherwise one materialized row, then ``tracker.advance(action)`` with the
   action the live player ACTUALLY took (``states.npz["actions"]``) — the chosen
   action feeds the turn-history fold, so replaying it is required for
   bit-faithful subsequent obs.

The round-trip guarantee (replaying a recorded battle reproduces the saved
``states.npz`` obs bit-for-bit) is enforced by
``agents/training/obs_roundtrip_fuzz_test.py``.

Counterfactual use (Phase 1)
----------------------------
Materializing a re-rolled continuation is composition, not new machinery: feed
``prefix_chunks + reroll.pN_chunks`` with the recorded actions for the prefix.
Rows are appended only while their history is faithful — one row past the last
provided action is still valid (an obs depends on *prior* actions only), which
is exactly the V(s′) row a re-roll consumer needs; after that the replay stops.

Prefix sharing (many branches of ONE decision)
----------------------------------------------
K counterfactual arms of the same decision share an identical prefix, and
replaying it K times is the measured bottleneck of the counterfactual label path
(``arm_ms = 4.78 + 0.853·turn``, of which prefix replay is ``2.53 + 0.855·turn``;
the branched turn itself is ~0.5 ms and the obs encode ~1.8 ms — cost model
2026-08-21). :func:`materialize_branches` replays the prefix **once**, snapshots
the player's whole battle/tracker state at the branch decision, and restores that
snapshot per arm. The restore is a rebuild from a buffer serialized ONCE, not a
per-arm ``deepcopy`` — once the prefix is shared it is the loop's largest single
cost (57% of the per-arm wall) and the two paths are exactly equivalent; see
:meth:`_PlayerSnapshot._freeze`. It is defined to be *exactly* equivalent to calling
:func:`materialize_decisions` once per arm on ``prefix + suffix`` — bit-for-bit
on every obs — and that equivalence is what
``obs_materializer_branch_integration_test.py`` pins. Measured on 6 gen-17
eval battles / 59 decisions / 452 arms: **59/59 byte-identical, 15.4 → 5.3 ms per
arm (2.91×)**, rising with the branch turn (3.7–3.9× at turn 26–28) because the
prefix cost it removes is the part that is linear in the turn.

Reading a record that has NO trace beside it (:func:`scan_record`)
-----------------------------------------------------------------
An eval trace ships its obs and its action indices in ``states.npz``. A **training**
reconstruction record — what the ``--cf-records`` tap (``agents.training.cf_records``) rings —
ships neither: only the seed, both packed teams and the committed choice strings. So the only
route to a training decision's observation is to replay the one-sided protocol AND recover the
action history by inverting those choices through the real mapper. :func:`scan_record` does both
in one replay and returns :class:`RecordDecision` rows (obs, mask, action index, choice string).
It is what ``agents.training.cf_producer`` reads a ring record with.

Known limit: a battle containing a true ``[Invalid choice]`` error round cannot
be mirrored exactly (poke-env answers those with a coin-flip default); the
server-authoritative mask makes them no-ops in practice. The
``[Unavailable choice]`` maybe-trapped probe IS reproduced exactly — the raw
command log replays the refused attempt, regenerating the same |error| line,
rejection event, and re-request the live player saw.
"""

from __future__ import annotations

import asyncio
import copy
import io
import logging
import pickle
import sys
import types
from collections import deque
from dataclasses import dataclass, field
from types import MappingProxyType
from typing import Any, List, Optional, Sequence

import numpy as np

from poke_env.concurrency import POKE_LOOP
from poke_env.ps_client import AccountConfiguration
from poke_env.ps_client.server_configuration import LocalhostServerConfiguration

from agents.inference.player import Gen3Player
from agents.training.stall import StallConfig
from utils.bridge.battle_stream_client import BattleStreamClient
from utils.bridge.reconstruction import ReconstructionRecord, replay_battle

_TAG_SEQ = 0


@dataclass(frozen=True)
class MaterializedDecision:
    """One decision point's full agent view: the observation the live policy
    would receive (obs-vector + prev-mask + turn-history, concatenated exactly
    as ``embed_battle`` returns it) and its action mask.

    ``obs`` is ``None`` for a TRACK-ONLY decision (one the caller asked NOT to encode via
    ``encode_only_at`` — the tracker is still advanced faithfully, only the expensive obs encode is
    skipped because nobody reads that decision's obs)."""

    obs: Optional[np.ndarray]
    mask: np.ndarray
    turn: int


@dataclass(frozen=True)
class MaterializedTrace:
    decisions: List[MaterializedDecision]
    # True when every materialized row had its action provided (full-history
    # faithfulness); False when the replay stopped one row past the last action.
    actions_complete: bool
    # When map_actions_at=i was requested: {action_idx: sim choice string} for
    # every LEGAL action at decision i, produced by the REAL action mapper
    # (Gen3ActionMapper via action_to_order) against the replayed battle state —
    # e.g. {6: "move icebeam", 2: "switch skarmory"}. None otherwise. This is
    # how a counterfactual consumer turns "alternative action index" into the
    # choice string reroll_turn needs, with zero mapping reimplementation.
    action_choices: Optional[dict] = None


class _ReplayObsPlayer(Gen3Player):
    """A transport-less Gen3Player that records ``embed_battle`` output at each
    decision instead of running a policy. Orders it returns go nowhere (the
    ``BattleStreamClient`` has no live bridge process registered)."""

    def __init__(self, *, replay_actions: Sequence[int],
                 map_actions_at: Optional[int] = None,
                 stop_after_decision: Optional[int] = None,
                 encode_only_at: "Optional[set]" = None, **kwargs):
        super().__init__(**kwargs)
        self._replay_actions = [int(a) for a in replay_actions]
        self._materialized: List[MaterializedDecision] = []
        self._actions_exhausted = False
        self._map_actions_at = map_actions_at
        self._stop_after = stop_after_decision
        # When set, ENCODE the obs only at these decision indices (others are track-only — the tracker
        # still advances faithfully, the encode is skipped). None = encode every decision (the default).
        self._encode_only_at = encode_only_at
        self._stopped = False
        self.action_choices: Optional[dict] = None

    @property
    def done(self) -> bool:
        return self._actions_exhausted or self._stopped

    def _encode_or_track(self, battle, i: int):
        """``(obs, mask)`` for decision ``i``, or ``None`` when this call is NOT a decision.

        Encode the obs only where the caller needs it (``encode_only_at``); elsewhere just TRACK
        (the tracker advances identically, the ~80%-cost encode is skipped → ``obs`` is None). The
        index ``i`` is this decision's position BEFORE the append (a no-decision ``mask.sum()==0``
        call doesn't append), so it lines up with the caller's ``encode_only_at`` indices.

        Shared with :class:`_InvertingReplayPlayer` so the two replay players cannot drift on the
        one step where drift would silently change an obs.
        """
        if self._encode_only_at is None or i in self._encode_only_at:
            obs_dict = self.embed_battle(battle)
            mask = obs_dict["action_mask"]
            if int(mask.sum()) == 0:
                return None
            return np.asarray(obs_dict["observation"], dtype=np.float32), mask
        _legal, mask, _tracker = self.track_decision(battle)
        if int(mask.sum()) == 0:
            return None
        return None, mask

    def choose_move(self, battle):
        # Mirror EvalRLPlayer.choose_move → RLPlayer._predict_best_action (see
        # module header). Order of operations is load-bearing.
        forfeit = self._handle_stall(battle, "REPLAY_STALL")
        if forfeit:
            return forfeit
        if self.done:
            return self.choose_default_move()
        i = len(self._materialized)
        step = self._encode_or_track(battle, i)
        if step is None:
            return self.choose_default_move()
        obs, mask = step
        self._materialized.append(
            MaterializedDecision(obs=obs, mask=np.asarray(mask), turn=battle.strict_view().turn))
        if i == self._map_actions_at:
            # Map every legal action through the REAL mapper at this exact
            # decision state — the choice strings a counterfactual re-roll
            # feeds back to the sim. Read-only (the mapper is pure).
            self.action_choices = {
                int(idx): self.action_to_order(int(idx), battle).message[len("/choose "):]
                for idx in np.flatnonzero(mask)
            }
        if i < len(self._replay_actions):
            self._get_tracker(battle).advance(self._replay_actions[i])
        else:
            # This row is still faithful (an obs depends on PRIOR actions only);
            # anything past it would fold an unknown action into the history.
            self._actions_exhausted = True
        if self._stop_after is not None and i >= self._stop_after:
            self._stopped = True
        return self.choose_default_move()


def materialize_decisions(
    chunks: Sequence[str],
    *,
    username: str,
    packed_team: str,
    side: str,
    actions: Sequence[int] = (),
    battle_format: str = "gen3ou",
    battle_tag: Optional[str] = None,
    mappings=None,
    stall_config: Optional[StallConfig] = None,
    map_actions_at: Optional[int] = None,
    stop_after_decision: Optional[int] = None,
    encode_only_at: "Optional[set]" = None,
) -> MaterializedTrace:
    """Replay one side's protocol ``chunks`` through the real obs pipeline.

    ``chunks`` are that side's chunks from :func:`utils.bridge.reconstruction.replay_battle`
    (or ``prefix + reroll`` chunks from :func:`...reroll_turn`). ``username`` /
    ``packed_team`` / ``side`` describe the side being replayed — take them from
    the record (``record.username(side)`` / ``record.packed_team(side)``); the
    username must match so poke-env resolves the player's role. ``actions`` are
    the live action indices (``states.npz["actions"]``) consumed one per
    materialized decision.

    ``map_actions_at=i`` additionally returns, in ``.action_choices``, the
    legal action-index → sim-choice-string mapping at decision ``i`` (via the
    real action mapper) — what a counterfactual consumer feeds ``reroll_turn``.
    ``stop_after_decision=i`` stops the replay once row ``i`` is materialized
    (cheap when only a prefix is needed).

    ``encode_only_at`` (a set of decision indices) ENCODES the obs only at those decisions; the rest
    are TRACK-ONLY (``decision.obs is None``) — the tracker still advances faithfully, but the
    expensive obs encode (~80% of the per-decision cost) is skipped where the caller won't read it
    (e.g. a search that needs only ONE successor's obs, or a choice-map / action-history pass that
    needs none). ``None`` (default) encodes every decision. The encoded decisions' obs are bit-for-bit
    identical to a full encode (the skipped encode is read-only on the tracker).
    """
    tag = _next_tag(battle_tag, battle_format)
    player, client = _build_replay_player(
        username=username, packed_team=packed_team, side=side, actions=actions,
        battle_format=battle_format, mappings=mappings, stall_config=stall_config,
        map_actions_at=map_actions_at, stop_after_decision=stop_after_decision,
        encode_only_at=encode_only_at,
    )
    _refuse_poke_loop("materialize_decisions")
    asyncio.run_coroutine_threadsafe(_feed(client, player, chunks, tag, first=True),
                                     POKE_LOOP).result()
    return MaterializedTrace(
        decisions=list(player._materialized),
        actions_complete=not player._actions_exhausted,
        action_choices=player.action_choices,
    )


def _next_tag(battle_tag: Optional[str], battle_format: str) -> str:
    global _TAG_SEQ
    _TAG_SEQ += 1
    return battle_tag or f"battle-{battle_format}-recon{_TAG_SEQ}"


def _build_replay_player(*, username: str, packed_team: str, side: str,
                         actions: Sequence[int], battle_format: str, mappings,
                         stall_config, map_actions_at, stop_after_decision, encode_only_at):
    """The player + transport-less client every replay path uses. Split out so the
    single-shot and prefix-sharing entry points build IDENTICAL objects (any drift here
    would silently break the bit-identity contract between them)."""
    player = _ReplayObsPlayer(
        replay_actions=actions,
        map_actions_at=map_actions_at,
        stop_after_decision=stop_after_decision,
        encode_only_at=encode_only_at,
        mappings=mappings,
        stall_config=stall_config,
        battle_format=battle_format,
        account_configuration=AccountConfiguration(username, None),
        server_configuration=LocalhostServerConfiguration,
        start_listening=False,
        max_concurrent_battles=1,
    )
    client = BattleStreamClient(
        player.ps_client._account_configuration,
        side=side,
        on_battle_message=player._handle_battle_message,
        on_update_challenges=player._update_challenges,
        on_challenge_request=player._handle_challenge_request,
        loop=POKE_LOOP,
    )
    player.ps_client = client
    # What _create_battle reads for the declared-team tracking (live: set by
    # get_next_team() just before the battle starts).
    player._current_packed_team = packed_team
    return player, client


async def _feed(client, player, chunks: Sequence[str], tag: str, *, first: bool) -> int:
    """Feed ``chunks`` and return how many were CONSUMED (the loop stops early once the
    player is done). The count is what lets :func:`materialize_branches` hand the
    still-unfed tail of a prefix to each branch instead of silently dropping it."""
    inited = not first
    consumed = 0
    for chunk in chunks:
        header = f">{tag}\n"
        if not inited:
            inited = True
            header += "|init|battle\n"
        # Awaited fully per chunk — the exact sequential-deterministic
        # delivery the eval bridge path (`run_local_battles._demux`) uses.
        await client.feed(header + chunk)
        consumed += 1
        if player.done:
            break
    return consumed


def _refuse_poke_loop(who: str) -> None:
    """The player's asyncio primitives live on POKE_LOOP (poke-env's background loop
    thread), so the feed must run there. ``run_coroutine_threadsafe`` works from sync
    context AND from inside any OTHER running loop; only a caller already on POKE_LOOP
    itself would deadlock on ``.result()`` — refuse loudly."""
    try:
        if asyncio.get_running_loop() is POKE_LOOP:
            raise RuntimeError(f"{who} must not be called from POKE_LOOP")
    except RuntimeError as e:
        if "POKE_LOOP" in str(e):
            raise


# ---------------------------------------------------------------------------
# Prefix sharing — replay the prefix ONCE, branch per arm
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Branch:
    """One arm of a shared-prefix decision.

    ``chunks`` are that arm's SUFFIX chunks (everything after the prefix — e.g. an
    ``ArmReroll``'s per-side chunks). ``actions`` are the action indices from the branch
    decision onward: ``actions[0]`` is the action played AT the branch decision (the
    counterfactual), and the whole list is appended to the shared ``prefix_actions``.
    ``label`` is opaque and echoed back by the caller's own bookkeeping."""

    chunks: Sequence[str]
    actions: Sequence[int] = field(default_factory=tuple)
    label: Any = None


#: Objects that must be SHARED by a clone rather than copied. Two reasons, both real:
#:  * ``logging.Logger`` — deep-copying one drags in ``Logger.manager.loggerDict``, i.e.
#:    EVERY logger in the process (torch's included), whose handlers hold
#:    ``_thread.RLock``; that is unpicklable, and a logger is shared infrastructure, not
#:    per-battle state.
#:  * ``MappingProxyType`` — unpicklable too, and copying one would be WRONG anyway: it
#:    is a read-only view (``LegalActions.last_request``), so a copy is at best a
#:    type-changing no-op.
_SHARED_TYPES: tuple = (logging.Logger, logging.Manager, logging.Handler, MappingProxyType)

def _immutable_record_types() -> tuple:
    """Additionally shared: APPEND-ONLY IMMUTABLE RECORDS.

    A branch APPENDS to the event log and the tracker history; it never rewrites an existing
    entry. ``BattleEvent`` is a ``frozen=True`` dataclass documented as "one immutable,
    ordered record"; ``BattleContext`` is a per-turn snapshot built once in
    ``EpisodeTracker.record()``. Sharing them instead of copying them is therefore exactly
    equivalent, AND it is the difference between a clone that costs O(turns) of deep
    structure and one that costs O(live objects): measured at turn 12, pinning the 16
    history contexts took the tracker clone from 2.96 ms to 1.06 ms.

    ⚠️ This is a CONTRACT, not an inference. If either type ever gains in-place mutation,
    counterfactual arms after the first would read history the previous arm corrupted —
    which is precisely what ``obs_materializer_branch_integration_test.py`` exists to catch,
    and why that test compares EVERY arm rather than sampling one.

    Imported lazily so this module keeps its narrow import graph.
    """
    from agents.battle.battle_event import BattleEvent
    from agents.training.battle_snapshot import BattleContext
    return (BattleEvent, BattleContext)


def _shared_singleton_types() -> tuple:
    """Also shared: PROCESS SINGLETONS that declare themselves one via ``__deepcopy__``.

    ``GenData.__deepcopy__`` returns ``self``, so the deepcopy path shares the gen-3 dex whether
    or not it is pinned. :meth:`_PlayerSnapshot._freeze` uses PICKLE, which honours no such hook
    and would deep-copy the whole dex into every arm instead. Pinning makes the two clone
    mechanisms provably agree rather than agreeing by accident of what is reachable today
    (measured 2026-08-23: ``GenData`` is NOT reachable from a live battle graph — the frozen blob
    is ~44 kB — so this is a latent-hazard guard, not a live fix).
    """
    from poke_env.data.gen_data import GenData
    return (GenData,)


def _pin_shared(obj, pins: dict, seen: "Optional[set]" = None) -> dict:
    """Walk ``obj``'s object graph and record ``{id: obj}`` for every member of
    :data:`_SHARED_TYPES`, so a later ``deepcopy(..., memo=pins)`` returns them
    unchanged. Run ONCE per snapshot; the resulting pin set stays valid for every restore
    (a restore copies from the snapshot, whose pinned objects are the same objects)."""
    if seen is None:
        seen = set()
    shared = _SHARED_TYPES + _immutable_record_types() + _shared_singleton_types()
    stack = [obj]
    while stack:
        o = stack.pop()
        i = id(o)
        if i in seen:
            continue
        seen.add(i)
        if isinstance(o, shared):
            pins[i] = o
            continue
        if isinstance(o, (str, bytes, bytearray, int, float, complex, bool,
                          type(None), np.ndarray, np.generic)):
            continue
        if isinstance(o, type) or isinstance(o, types.ModuleType):
            continue
        if isinstance(o, dict):
            stack.extend(o.keys())
            stack.extend(o.values())
            continue
        if isinstance(o, (list, tuple, set, frozenset, deque)):
            stack.extend(o)
            continue
        d = getattr(o, "__dict__", None)
        if isinstance(d, dict):
            stack.extend(d.values())
        for cls in type(o).__mro__:
            for slot in getattr(cls, "__slots__", ()) or ():
                try:
                    stack.append(getattr(o, slot))
                except AttributeError:
                    pass
    return pins


#: Set once the pickle fast path has been reported as unavailable, so the warning is printed one
#: time per process rather than once per arm.
_FREEZE_WARNED = False


class _PinnedPickler(pickle.Pickler):
    """A pickler that writes PINNED objects by reference instead of copying them.

    The exact pickle-side counterpart of ``deepcopy(obj, memo=pins)``: the same
    ``{id: obj}`` set that a memo pre-seeds is here turned into ``persistent_id`` indices, so a
    shared logger / mapping proxy / immutable record comes back as itself."""

    def __init__(self, buf, pin_idx: dict):
        super().__init__(buf, protocol=pickle.HIGHEST_PROTOCOL)
        self._pin_idx = pin_idx

    def persistent_id(self, obj):
        return self._pin_idx.get(id(obj))


class _PinnedUnpickler(pickle.Unpickler):
    """The read side: resolve a persistent id back to the very object that was pinned."""

    def __init__(self, buf, pin_list: list):
        super().__init__(buf)
        self._pin_list = pin_list

    def persistent_load(self, pid):
        return self._pin_list[pid]


def _pickle_pinned(obj, pin_idx: dict) -> bytes:
    buf = io.BytesIO()
    _PinnedPickler(buf, pin_idx).dump(obj)
    return buf.getvalue()


def _unpickle_pinned(blob: bytes, pin_list: list):
    return _PinnedUnpickler(io.BytesIO(blob), pin_list).load()


class _PlayerSnapshot:
    """A restorable copy of everything one replay feed mutates.

    poke-env's ``Battle`` is ``__slots__``-based plain data (no locks, no asyncio
    primitives, no back-reference to the dex — ``Pokemon``/``Move`` carry an int ``_gen``
    and look entries up on demand), so a ``deepcopy`` of the battle graph is a complete
    and cheap clone. The exceptions are :data:`_SHARED_TYPES`, pinned into the memo by
    :func:`_pin_shared`."""

    __slots__ = ("battles", "trackers", "stall_loggers", "materialized",
                 "actions_exhausted", "stopped", "action_choices", "queue_depth",
                 "trying_again", "_pins", "_pin_list", "_blobs")

    def __init__(self, player):
        self._pins = {}
        seen: set = set()
        for src in (player._battles, player._trackers, player._stall_loggers):
            _pin_shared(src, self._pins, seen)
        self.battles = self._clone(player._battles)
        self.trackers = self._clone(player._trackers)
        self.stall_loggers = self._clone(player._stall_loggers)
        self._pin_list = list(self._pins.values())
        self._blobs = self._freeze()
        # MaterializedDecision is frozen and never mutated in place, so the list itself
        # is the only thing that changes (append-only) — a shallow copy is exact.
        self.materialized = list(player._materialized)
        self.actions_exhausted = player._actions_exhausted
        self.stopped = player._stopped
        self.action_choices = player.action_choices
        self.queue_depth = player._battle_count_queue.qsize()
        self.trying_again = player._trying_again.is_set()

    def _clone(self, obj):
        return copy.deepcopy(obj, dict(self._pins))

    def _freeze(self) -> Optional[tuple]:
        """Serialize the three masters ONCE so a restore is a ``loads`` instead of a ``deepcopy``.

        **This is the arm loop's largest single cost.** Measured 2026-08-23 on a live
        search-dividend oracle decision: ``restore`` was **3.69 ms of the materializer's 6.45 ms
        per arm — 57% of it and ~25% of the whole search's wall clock**, because a restore is
        three ``deepcopy`` traversals of the poke-env battle graph and a deepcopy re-walks and
        re-dispatches every node every time. Pickle walks it once, at snapshot time, and the
        per-arm cost collapses to a C-level rebuild from a flat buffer: **1.98 → 0.22 ms (9.1×)**
        on the same graph, against a one-off 0.66 ms to freeze.

        Three properties make it EXACTLY equivalent to the deepcopy path, and each one is a
        deliberate choice rather than a happy accident:

        * **Three SEPARATE blobs, never one.** ``_clone`` is called once per structure with its
          own fresh ``dict(self._pins)`` memo, so an object reachable from both ``battles`` and
          ``trackers`` is DUPLICATED into two independent copies (measured: 12 such objects).
          One combined blob would alias them, which is a different object graph and a silent
          aliasing bug of exactly the shape ``_immutable_record_types`` is careful about.
        * **The pins are honoured**, via ``persistent_id`` — a pinned object is written as an
          index into :attr:`_pin_list` and comes back as the SAME object, which is what
          ``memo=pins`` does for deepcopy. Without it a ``logging.Logger`` would drag in every
          logger in the process and an ``RLock`` would make the graph unpicklable outright.
        * **Value semantics, not identity semantics.** Pickle mints fresh ``str`` objects where
          ``_deepcopy_atomic`` returns the interned original. Nothing downstream compares battle
          state by identity, and the equivalence that matters — bit-identical observations — is
          what ``obs_materializer_branch_integration_test.py`` asserts on every arm.

        Returns ``None`` if the graph will not pickle, in which case :meth:`restore` keeps using
        ``deepcopy``. A fall-back is announced ONCE on stderr: it is a ~9× slowdown that no
        output would otherwise mention, and an invisible perf regression is the failure mode this
        project has eaten most often.
        """
        pin_idx = {id(o): i for i, o in enumerate(self._pin_list)}
        try:
            return tuple(_pickle_pinned(x, pin_idx)
                         for x in (self.battles, self.trackers, self.stall_loggers))
        except Exception as e:                                  # noqa: BLE001
            global _FREEZE_WARNED
            if not _FREEZE_WARNED:
                _FREEZE_WARNED = True
                print(f"⚠️ [obs_materializer] branch snapshots fell back to deepcopy "
                      f"(~9x slower per arm) — {type(e).__name__}: {str(e)[:160]}",
                      file=sys.stderr, flush=True)
            return None

    def restore(self, player) -> None:
        """Reset ``player`` to the snapshotted state. Every mutable structure is a FRESH
        deep copy, so the caller may mutate it freely and restore again."""
        if self._blobs is not None:
            player._battles, player._trackers, player._stall_loggers = (
                _unpickle_pinned(b, self._pin_list) for b in self._blobs)
        else:
            player._battles = self._clone(self.battles)
            player._trackers = self._clone(self.trackers)
            player._stall_loggers = self._clone(self.stall_loggers)
        player._materialized = list(self.materialized)
        player._actions_exhausted = self.actions_exhausted
        player._stopped = self.stopped
        player.action_choices = self.action_choices
        # A branch whose suffix ENDS the battle drains one item from the battle-count
        # queue (poke-env's `|win|` handler awaits `.get()`); without this the NEXT
        # branch's `|win|` would block forever on an empty queue.
        q = player._battle_count_queue
        while q.qsize() > self.queue_depth:
            q.get_nowait()
        while q.qsize() < self.queue_depth:
            q.put_nowait(None)
        if self.trying_again:
            player._trying_again.set()
        else:
            player._trying_again.clear()


def materialize_branches(
    prefix_chunks: Sequence[str],
    branches: Sequence[Branch],
    *,
    username: str,
    packed_team: str,
    side: str,
    prefix_actions: Sequence[int] = (),
    battle_format: str = "gen3ou",
    battle_tag: Optional[str] = None,
    mappings=None,
    stall_config: Optional[StallConfig] = None,
    map_actions_at: Optional[int] = None,
    stop_after_decision: Optional[int] = None,
    encode_only_at: "Optional[set]" = None,
) -> "List[MaterializedTrace]":
    """Materialize K arms of ONE decision, replaying their shared prefix exactly once.

    Defined to be **exactly equivalent** to, for each ``branch``::

        materialize_decisions(list(prefix_chunks) + list(branch.chunks),
                              actions=list(prefix_actions) + list(branch.actions), ...)

    including bit-for-bit obs. The saving is that the prefix — the measured 53% + of a
    counterfactual arm's cost, growing linearly in the branch turn — is replayed once for
    the whole set instead of once per arm.

    ``prefix_actions`` are the recorded actions BEFORE the branch decision, so the branch
    decision's index is ``len(prefix_actions)``: the prefix replay stops there naturally
    (its action list is exhausted), which is exactly the point where the arms diverge.

    Raises ``RuntimeError`` if the prefix does not reach the branch decision (a caller
    whose ``prefix_actions`` and ``prefix_chunks`` disagree — that would silently branch
    from the wrong state).
    """
    branches = list(branches)
    if not branches:
        return []
    prefix_actions = [int(a) for a in prefix_actions]
    n_prefix = len(prefix_actions)
    tag = _next_tag(battle_tag, battle_format)

    player, client = _build_replay_player(
        username=username, packed_team=packed_team, side=side, actions=prefix_actions,
        battle_format=battle_format, mappings=mappings, stall_config=stall_config,
        map_actions_at=map_actions_at, stop_after_decision=stop_after_decision,
        encode_only_at=encode_only_at,
    )
    _refuse_poke_loop("materialize_branches")
    # The prefix player's action list has exactly `n_prefix` entries, so decision
    # `n_prefix` — the branch decision — is materialized and then sets _actions_exhausted
    # WITHOUT advancing the tracker. That is precisely the fork point: the tracker advance
    # is the first thing that differs between arms, and it has not happened yet.
    consumed = asyncio.run_coroutine_threadsafe(
        _feed(client, player, prefix_chunks, tag, first=True), POKE_LOOP).result()
    if len(player._materialized) != n_prefix + 1:
        raise RuntimeError(
            f"prefix replay produced {len(player._materialized)} decisions for a branch at "
            f"index {n_prefix} — prefix_chunks and prefix_actions disagree, so the arms "
            f"would branch from the wrong state")
    # The prefix feed stopped on whichever chunk carried the branch decision's request.
    # Anything after it is prefix the single-shot path WOULD have fed (after the tracker
    # advance), so each branch replays that tail ahead of its own suffix — dropping it is
    # exactly the divergence this tail exists to prevent.
    prefix_tail = list(prefix_chunks)[consumed:]
    snapshot = _PlayerSnapshot(player)

    out: List[MaterializedTrace] = []
    for branch in branches:
        snapshot.restore(player)
        full_actions = prefix_actions + [int(a) for a in branch.actions]
        player._replay_actions = full_actions
        # Replay the exact bookkeeping materialize_decisions would have done at decision
        # `n_prefix` had the branch's action been in its list from the start.
        if n_prefix < len(full_actions):
            # The prefix player exhausted its (shorter) action list at this very decision;
            # the branch supplies the action it was missing, so the replay is live again.
            player._actions_exhausted = False
            battle = player._battles[tag]
            player._get_tracker(battle).advance(full_actions[n_prefix])
        else:
            player._actions_exhausted = True
        if stop_after_decision is not None and n_prefix >= stop_after_decision:
            player._stopped = True
        if not player.done:
            asyncio.run_coroutine_threadsafe(
                _feed(client, player, prefix_tail + list(branch.chunks), tag, first=False),
                POKE_LOOP).result()
        out.append(MaterializedTrace(
            decisions=list(player._materialized),
            actions_complete=not player._actions_exhausted,
            action_choices=player.action_choices,
        ))
    return out


class _InvertingReplayPlayer(_ReplayObsPlayer):
    """Like :class:`_ReplayObsPlayer`, but instead of consuming a provided action-index list it
    RECOVERS each decision's action index by inverting the side's recorded sim-choice string through
    the real mapper. Two callers: the OPPONENT's action-index history for an interior search ply
    (the trace records only the trainee's actions), and :func:`scan_record`'s read of a TRAINING
    record, which has no recorded actions for either side."""

    def __init__(self, *, recorded_choices: Sequence[str], **kwargs):
        super().__init__(replay_actions=(), **kwargs)
        self._queue = list(recorded_choices)
        self.inverted_actions: List[int] = []
        # The recorded sim-choice STRING that was accepted at each decision — the same list
        # `inverted_actions` holds the index form of. A counterfactual that wants to replay "the
        # action that was actually taken" needs the string (that is what the sim eats), and
        # re-deriving it from the index would be a second mapping implementation.
        self.accepted_choices: List[str] = []

    def choose_move(self, battle):
        forfeit = self._handle_stall(battle, "REPLAY_STALL")
        if forfeit:
            return forfeit
        if self._stopped:
            return self.choose_default_move()
        # Inversion needs only the MASK (to map choices via the real mapper); the obs is encoded only
        # where the caller asked for it (`encode_only_at`; `infer_action_indices` asks nowhere, so it
        # stays TRACK-ONLY throughout and skips the ~80%-cost encode at every decision).
        i = len(self._materialized)
        step = self._encode_or_track(battle, i)
        if step is None:
            return self.choose_default_move()
        obs, mask = step
        self._materialized.append(MaterializedDecision(
            obs=obs, mask=np.asarray(mask), turn=battle.strict_view().turn))
        # Pop recorded choices until one INVERTS to a legal index (a refused maybe-trapped probe
        # inverts to None — consume it and try the correction, mirroring the sim's queue semantics).
        idx, accepted = None, None
        while self._queue and idx is None:
            accepted = self._queue.pop(0)
            idx = self._invert(battle, accepted, mask)
        if idx is not None:
            self.inverted_actions.append(int(idx))
            self.accepted_choices.append(str(accepted))
            self._get_tracker(battle).advance(int(idx))
        else:
            self._actions_exhausted = True
        if self._stop_after is not None and i >= self._stop_after:
            self._stopped = True
        return self.choose_default_move()

    def _invert(self, battle, choice_str: str, mask) -> Optional[int]:
        for idx in np.flatnonzero(np.asarray(mask)):
            try:
                order = self.action_to_order(int(idx), battle)
            except Exception:  # noqa: BLE001 — a stale/illegal candidate is just not a match
                continue
            if order.message[len("/choose "):] == choice_str:
                return int(idx)
        return None


def _run_inverting_replay(
    record: ReconstructionRecord,
    side: str,
    *,
    who: str,
    mappings=None,
    stall_config: Optional[StallConfig] = None,
    stop_after_decision: Optional[int] = None,
    chunks: "Optional[Sequence[str]]" = None,
    impl: str = "node",
    encode: bool = False,
) -> "_InvertingReplayPlayer":
    """Replay ``side``'s recorded battle through an :class:`_InvertingReplayPlayer` and return it.

    Shared by :func:`infer_action_indices` (``encode=False`` — indices only) and
    :func:`scan_record` (``encode=True`` — indices, choice strings AND the one-sided obs). One
    function so the two cannot drift on the replay setup, which is the part that would silently
    change an obs rather than fail.
    """
    global _TAG_SEQ
    _TAG_SEQ += 1
    name = record.username(side)
    if chunks is None:
        rep = replay_battle(record, impl=impl)
        chunks = rep.p1_chunks if side == "p1" else rep.p2_chunks
    recorded = [c for (s, c) in record.commands if s == side]
    player = _InvertingReplayPlayer(
        recorded_choices=recorded, stop_after_decision=stop_after_decision, mappings=mappings,
        # `None` encodes EVERY decision, the empty set encodes NONE — the two callers' two modes.
        encode_only_at=None if encode else set(),
        stall_config=stall_config,
        battle_format=record.format_id,
        account_configuration=AccountConfiguration(name, None),
        server_configuration=LocalhostServerConfiguration,
        start_listening=False, max_concurrent_battles=1)
    client = BattleStreamClient(
        player.ps_client._account_configuration, side=side,
        on_battle_message=player._handle_battle_message,
        on_update_challenges=player._update_challenges,
        on_challenge_request=player._handle_challenge_request, loop=POKE_LOOP)
    player.ps_client = client
    player._current_packed_team = record.packed_team(side)
    tag = record.battle_tag or f"battle-{record.format_id}-recon{_TAG_SEQ}"

    async def _feed_all() -> None:
        inited = False
        for chunk in chunks:
            header = f">{tag}\n"
            if not inited:
                inited = True
                header += "|init|battle\n"
            await client.feed(header + chunk)
            if player.done:
                break

    _refuse_poke_loop(who)
    asyncio.run_coroutine_threadsafe(_feed_all(), POKE_LOOP).result()
    # Every materialized decision must have inverted to exactly one action index. A shortfall means a
    # recorded choice failed to invert (an [Invalid choice] round, or a mapper edge) — which would
    # silently DESYNC the obs (its action history would be a ply short). Fail LOUD instead.
    if len(player.inverted_actions) != len(player._materialized):
        raise RuntimeError(
            f"{who}({side}): recovered {len(player.inverted_actions)} action indices for "
            f"{len(player._materialized)} decisions — a recorded choice failed to invert, so the "
            f"action history would desync the obs. This battle can't drive a faithful "
            f"replay of this side.")
    return player


def infer_action_indices(
    record: ReconstructionRecord,
    side: str,
    *,
    mappings=None,
    stop_after_decision: Optional[int] = None,
    chunks: "Optional[Sequence[str]]" = None,
    impl: str = "node",
) -> "list[int]":
    """Recover ``side``'s ACTION-INDEX history by replaying its recorded battle and inverting each
    recorded sim-choice string through the real mapper. The counterpart of ``states.npz['actions']``
    for the OPPONENT (the forensic trace records only the trainee's actions), so the opponent's
    one-sided obs can be materialized faithfully for an interior search ply. Refused maybe-trapped
    probes invert to ``None`` and are skipped (queue semantics).

    ``chunks`` (that side's chunks from an ALREADY-run :func:`replay_battle`) skips the internal
    replay — a caller that already replayed the battle (e.g. for the other side's obs) passes them so
    the whole game is replayed through the driver ONCE, not once per side. ``impl`` selects that
    driver (``"node"`` default | ``"rust"``) and is ignored when ``chunks`` is supplied."""
    player = _run_inverting_replay(
        record, side, who="infer_action_indices", mappings=mappings,
        stop_after_decision=stop_after_decision, chunks=chunks, impl=impl, encode=False)
    return list(player.inverted_actions)


@dataclass(frozen=True)
class RecordDecision:
    """One decision of a battle read back from its reconstruction record ALONE.

    The forensic path (``states.npz``) has the obs and the action indices already; a TRAINING
    record has neither — the tap (``agents.training.cf_records``) writes only the seed, the teams
    and the committed choice strings. So everything here is recovered by replay: ``obs`` from the
    one-sided protocol, ``action`` by inverting ``choice`` through the real action mapper.

    ``choice`` is the sim-choice STRING the side actually committed at this decision — what a
    counterfactual feeds back to the sim to replay "the action that was really taken".
    """

    index: int                       # position in the side's decision sequence
    turn: int
    action: int                      # the action INDEX (inverted through the real mapper)
    choice: str                      # the recorded sim-choice string, e.g. "move icebeam"
    mask: np.ndarray
    obs: Optional[np.ndarray] = None


def scan_record(
    record: ReconstructionRecord,
    side: Optional[str] = None,
    *,
    mappings=None,
    stall_config: Optional[StallConfig] = None,
    chunks: "Optional[Sequence[str]]" = None,
    impl: str = "node",
    encode: bool = True,
) -> "list[RecordDecision]":
    """Every decision ``side`` made in ``record``, with its obs, mask, action index and choice string.

    The entry point a consumer of the TRAINING record tap needs: a ring record carries no
    ``states.npz`` and no recorded actions, so the only way to reach a training decision's
    observation is to replay the one-sided protocol and invert the committed choices. One replay
    yields all four facts.

    ``side`` defaults to the record's ``trainee_username``'s side when the record names one, and to
    ``"p1"`` otherwise — which is what a training record is, since ``BridgeSession`` always seats
    ``env.agent1`` (the trainee) on p1. ``chunks`` skips the internal :func:`replay_battle` when the
    caller has already run one. ``encode=False`` returns masks/actions/choices with ``obs=None``
    (cheap: it skips the ~80%-of-cost obs encode at every decision).
    """
    if side is None:
        side = (record.side_of(record.trainee_username) if record.trainee_username else "p1")
    player = _run_inverting_replay(
        record, side, who="scan_record", mappings=mappings, stall_config=stall_config,
        chunks=chunks, impl=impl, encode=encode)
    return [
        RecordDecision(index=i, turn=int(d.turn), action=int(a), choice=str(c),
                       mask=np.asarray(d.mask), obs=d.obs)
        for i, (d, a, c) in enumerate(
            zip(player._materialized, player.inverted_actions, player.accepted_choices))
    ]


def materialize_from_record(
    record: ReconstructionRecord,
    *,
    username: Optional[str] = None,
    actions: Sequence[int] = (),
    mappings=None,
    stall_config: Optional[StallConfig] = None,
    map_actions_at: Optional[int] = None,
    stop_after_decision: Optional[int] = None,
    impl: str = "node",
) -> MaterializedTrace:
    """Convenience: replay the full recorded battle and materialize ``username``'s
    one-sided obs at every decision. ``username`` defaults to the record's
    ``trainee_username``. Only the regenerated per-side chunks cross into the
    obs pipeline — never the omniscient record fields. ``impl`` selects the replay driver
    (``"node"`` default | ``"rust"``)."""
    name = username or record.trainee_username
    if not name:
        raise ValueError("record carries no trainee_username — pass username=")
    side = record.side_of(name)
    rep = replay_battle(record, impl=impl)
    chunks = rep.p1_chunks if side == "p1" else rep.p2_chunks
    return materialize_decisions(
        chunks,
        username=name,
        packed_team=record.packed_team(side),
        side=side,
        actions=actions,
        battle_format=record.format_id,
        battle_tag=record.battle_tag,
        mappings=mappings,
        stall_config=stall_config,
        map_actions_at=map_actions_at,
        stop_after_decision=stop_after_decision,
    )
