"""Materialize the agent's ONE-SIDED observations from a battle's replayed protocol.

The forensic ``states.npz`` saves the obs vectors of states that *happened*; it
cannot score a counterfactual (a re-rolled turn), and the encoder's stateful
trackers (HiddenPowerTracker, ability/usage narrowing, the turn-history deltas,
the progress clock) are not recoverable from the 3457-dim output vector. The way
to get the obs of ANY point — recorded or re-rolled — is to replay the one-sided
protocol stream through the *real* obs pipeline from battle start, rebuilding
the tracker state exactly as the live player did. That replay is what this
module does.

**The one-sided / omniscient wall (hard requirement).** Input here is only the
per-side protocol chunks regenerated by ``utils.bridge.reconstruction``
(:func:`replay_battle` / :func:`reroll_turn`) — the exact bytes the live agent
saw. The omniscient reconstruction data (seed, both teams, dice) never enters
this module; the encoder reads the same partial poke-env view it reads live.

Fidelity contract
-----------------
``_ReplayObsPlayer`` mirrors the live eval decision cadence
(``EvalRLPlayer.choose_move`` → ``RLPlayer._predict_best_action``) exactly:

1. stall check first (same default :class:`StallConfig`, threshold 250 — the
   forfeit order goes nowhere, the recorded FORCELOSE in the replayed protocol
   ends the battle identically);
2. ``embed_battle`` (which records the decision context, updates the
   HiddenPowerTracker and the progress clock, and encodes the obs);
3. an all-zero mask ⇒ no decision (no row, no tracker advance) — the live
   ``idx is None`` deferral;
4. otherwise one materialized row, then ``tracker.advance(action)`` with the
   action the live player ACTUALLY took (``states.npz["actions"]``) — the chosen
   action feeds the turn-history fold, so replaying it is required for
   bit-faithful subsequent obs.

The round-trip guarantee (replaying a recorded battle reproduces the saved
``states.npz`` obs bit-for-bit) is enforced by
``agents/training/obs_roundtrip_fuzz_test.py``.

Counterfactual use (Phase 1)
----------------------------
Materializing a re-rolled continuation is composition, not new machinery: feed
``prefix_chunks + reroll.pN_chunks`` with the recorded actions for the prefix.
Rows are appended only while their history is faithful — one row past the last
provided action is still valid (an obs depends on *prior* actions only), which
is exactly the V(s′) row a re-roll consumer needs; after that the replay stops.

Known limit: a battle containing a true ``[Invalid choice]`` error round cannot
be mirrored exactly (poke-env answers those with a coin-flip default); the
server-authoritative mask makes them no-ops in practice. The
``[Unavailable choice]`` maybe-trapped probe IS reproduced exactly — the raw
command log replays the refused attempt, regenerating the same |error| line,
rejection event, and re-request the live player saw.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass
from typing import List, Optional, Sequence

import numpy as np

from poke_env.concurrency import POKE_LOOP
from poke_env.ps_client import AccountConfiguration
from poke_env.ps_client.server_configuration import LocalhostServerConfiguration

from agents.inference.player import Gen3Player
from agents.training.stall import StallConfig
from utils.bridge.battle_stream_client import BattleStreamClient
from utils.bridge.reconstruction import ReconstructionRecord, replay_battle

_TAG_SEQ = 0


@dataclass(frozen=True)
class MaterializedDecision:
    """One decision point's full agent view: the observation the live policy
    would receive (obs-vector + prev-mask + turn-history, concatenated exactly
    as ``embed_battle`` returns it) and its action mask.

    ``obs`` is ``None`` for a TRACK-ONLY decision (one the caller asked NOT to encode via
    ``encode_only_at`` — the tracker is still advanced faithfully, only the expensive obs encode is
    skipped because nobody reads that decision's obs)."""

    obs: Optional[np.ndarray]
    mask: np.ndarray
    turn: int


@dataclass(frozen=True)
class MaterializedTrace:
    decisions: List[MaterializedDecision]
    # True when every materialized row had its action provided (full-history
    # faithfulness); False when the replay stopped one row past the last action.
    actions_complete: bool
    # When map_actions_at=i was requested: {action_idx: sim choice string} for
    # every LEGAL action at decision i, produced by the REAL action mapper
    # (Gen3ActionMapper via action_to_order) against the replayed battle state —
    # e.g. {6: "move icebeam", 2: "switch skarmory"}. None otherwise. This is
    # how a counterfactual consumer turns "alternative action index" into the
    # choice string reroll_turn needs, with zero mapping reimplementation.
    action_choices: Optional[dict] = None


class _ReplayObsPlayer(Gen3Player):
    """A transport-less Gen3Player that records ``embed_battle`` output at each
    decision instead of running a policy. Orders it returns go nowhere (the
    ``BattleStreamClient`` has no live bridge process registered)."""

    def __init__(self, *, replay_actions: Sequence[int],
                 map_actions_at: Optional[int] = None,
                 stop_after_decision: Optional[int] = None,
                 encode_only_at: "Optional[set]" = None, **kwargs):
        super().__init__(**kwargs)
        self._replay_actions = [int(a) for a in replay_actions]
        self._materialized: List[MaterializedDecision] = []
        self._actions_exhausted = False
        self._map_actions_at = map_actions_at
        self._stop_after = stop_after_decision
        # When set, ENCODE the obs only at these decision indices (others are track-only — the tracker
        # still advances faithfully, the encode is skipped). None = encode every decision (the default).
        self._encode_only_at = encode_only_at
        self._stopped = False
        self.action_choices: Optional[dict] = None

    @property
    def done(self) -> bool:
        return self._actions_exhausted or self._stopped

    def choose_move(self, battle):
        # Mirror EvalRLPlayer.choose_move → RLPlayer._predict_best_action (see
        # module header). Order of operations is load-bearing.
        forfeit = self._handle_stall(battle, "REPLAY_STALL")
        if forfeit:
            return forfeit
        if self.done:
            return self.choose_default_move()
        i = len(self._materialized)
        # Encode the obs only where the caller needs it (encode_only_at); elsewhere just TRACK (the
        # tracker advances identically, the ~80%-cost encode is skipped → obs=None). The index `i` is
        # this decision's position BEFORE the append (a no-decision mask.sum()==0 call doesn't append),
        # so it lines up with the caller's encode_only_at indices.
        if self._encode_only_at is None or i in self._encode_only_at:
            obs_dict = self.embed_battle(battle)
            mask = obs_dict["action_mask"]
            if int(mask.sum()) == 0:
                return self.choose_default_move()
            obs = np.asarray(obs_dict["observation"], dtype=np.float32)
        else:
            _legal, mask, _tracker = self.track_decision(battle)
            if int(mask.sum()) == 0:
                return self.choose_default_move()
            obs = None
        self._materialized.append(
            MaterializedDecision(obs=obs, mask=np.asarray(mask), turn=battle.strict_view().turn))
        if i == self._map_actions_at:
            # Map every legal action through the REAL mapper at this exact
            # decision state — the choice strings a counterfactual re-roll
            # feeds back to the sim. Read-only (the mapper is pure).
            self.action_choices = {
                int(idx): self.action_to_order(int(idx), battle).message[len("/choose "):]
                for idx in np.flatnonzero(mask)
            }
        if i < len(self._replay_actions):
            self._get_tracker(battle).advance(self._replay_actions[i])
        else:
            # This row is still faithful (an obs depends on PRIOR actions only);
            # anything past it would fold an unknown action into the history.
            self._actions_exhausted = True
        if self._stop_after is not None and i >= self._stop_after:
            self._stopped = True
        return self.choose_default_move()


def materialize_decisions(
    chunks: Sequence[str],
    *,
    username: str,
    packed_team: str,
    side: str,
    actions: Sequence[int] = (),
    battle_format: str = "gen3ou",
    battle_tag: Optional[str] = None,
    mappings=None,
    stall_config: Optional[StallConfig] = None,
    map_actions_at: Optional[int] = None,
    stop_after_decision: Optional[int] = None,
    encode_only_at: "Optional[set]" = None,
) -> MaterializedTrace:
    """Replay one side's protocol ``chunks`` through the real obs pipeline.

    ``chunks`` are that side's chunks from :func:`utils.bridge.reconstruction.replay_battle`
    (or ``prefix + reroll`` chunks from :func:`...reroll_turn`). ``username`` /
    ``packed_team`` / ``side`` describe the side being replayed — take them from
    the record (``record.username(side)`` / ``record.packed_team(side)``); the
    username must match so poke-env resolves the player's role. ``actions`` are
    the live action indices (``states.npz["actions"]``) consumed one per
    materialized decision.

    ``map_actions_at=i`` additionally returns, in ``.action_choices``, the
    legal action-index → sim-choice-string mapping at decision ``i`` (via the
    real action mapper) — what a counterfactual consumer feeds ``reroll_turn``.
    ``stop_after_decision=i`` stops the replay once row ``i`` is materialized
    (cheap when only a prefix is needed).

    ``encode_only_at`` (a set of decision indices) ENCODES the obs only at those decisions; the rest
    are TRACK-ONLY (``decision.obs is None``) — the tracker still advances faithfully, but the
    expensive obs encode (~80% of the per-decision cost) is skipped where the caller won't read it
    (e.g. a search that needs only ONE successor's obs, or a choice-map / action-history pass that
    needs none). ``None`` (default) encodes every decision. The encoded decisions' obs are bit-for-bit
    identical to a full encode (the skipped encode is read-only on the tracker).
    """
    global _TAG_SEQ
    _TAG_SEQ += 1
    tag = battle_tag or f"battle-{battle_format}-recon{_TAG_SEQ}"

    player = _ReplayObsPlayer(
        replay_actions=actions,
        map_actions_at=map_actions_at,
        stop_after_decision=stop_after_decision,
        encode_only_at=encode_only_at,
        mappings=mappings,
        stall_config=stall_config,
        battle_format=battle_format,
        account_configuration=AccountConfiguration(username, None),
        server_configuration=LocalhostServerConfiguration,
        start_listening=False,
        max_concurrent_battles=1,
    )
    client = BattleStreamClient(
        player.ps_client._account_configuration,
        side=side,
        on_battle_message=player._handle_battle_message,
        on_update_challenges=player._update_challenges,
        on_challenge_request=player._handle_challenge_request,
        loop=POKE_LOOP,
    )
    player.ps_client = client
    # What _create_battle reads for the declared-team tracking (live: set by
    # get_next_team() just before the battle starts).
    player._current_packed_team = packed_team

    async def _feed_all() -> None:
        inited = False
        for chunk in chunks:
            header = f">{tag}\n"
            if not inited:
                inited = True
                header += "|init|battle\n"
            # Awaited fully per chunk — the exact sequential-deterministic
            # delivery the eval bridge path (`run_local_battles._demux`) uses.
            await client.feed(header + chunk)
            if player.done:
                break

    # The player's asyncio primitives live on POKE_LOOP (poke-env's background
    # loop thread), so the feed must run there. run_coroutine_threadsafe works
    # from sync context AND from inside any OTHER running loop; only a caller
    # already on POKE_LOOP itself would deadlock on .result() — refuse loudly.
    try:
        if asyncio.get_running_loop() is POKE_LOOP:
            raise RuntimeError("materialize_decisions must not be called from POKE_LOOP")
    except RuntimeError as e:
        if "POKE_LOOP" in str(e):
            raise
    asyncio.run_coroutine_threadsafe(_feed_all(), POKE_LOOP).result()
    return MaterializedTrace(
        decisions=list(player._materialized),
        actions_complete=not player._actions_exhausted,
        action_choices=player.action_choices,
    )


class _InvertingReplayPlayer(_ReplayObsPlayer):
    """Like :class:`_ReplayObsPlayer`, but instead of consuming a provided action-index list it
    RECOVERS each decision's action index by inverting the side's recorded sim-choice string through
    the real mapper. Used to reconstruct the OPPONENT's action-index history (the trace records only
    the trainee's actions) so its one-sided obs can be materialized faithfully."""

    def __init__(self, *, recorded_choices: Sequence[str], **kwargs):
        super().__init__(replay_actions=(), **kwargs)
        self._queue = list(recorded_choices)
        self.inverted_actions: List[int] = []

    def choose_move(self, battle):
        forfeit = self._handle_stall(battle, "REPLAY_STALL")
        if forfeit:
            return forfeit
        if self._stopped:
            return self.choose_default_move()
        # Inversion needs only the MASK (to map choices via the real mapper), never the obs — so this
        # replay is TRACK-ONLY throughout (skip the ~80%-cost encode at every decision).
        _legal, mask, _tracker = self.track_decision(battle)
        if int(mask.sum()) == 0:
            return self.choose_default_move()
        i = len(self._materialized)
        self._materialized.append(MaterializedDecision(
            obs=None, mask=np.asarray(mask), turn=battle.strict_view().turn))
        # Pop recorded choices until one INVERTS to a legal index (a refused maybe-trapped probe
        # inverts to None — consume it and try the correction, mirroring the sim's queue semantics).
        idx = None
        while self._queue and idx is None:
            idx = self._invert(battle, self._queue.pop(0), mask)
        if idx is not None:
            self.inverted_actions.append(int(idx))
            self._get_tracker(battle).advance(int(idx))
        else:
            self._actions_exhausted = True
        if self._stop_after is not None and i >= self._stop_after:
            self._stopped = True
        return self.choose_default_move()

    def _invert(self, battle, choice_str: str, mask) -> Optional[int]:
        for idx in np.flatnonzero(np.asarray(mask)):
            try:
                order = self.action_to_order(int(idx), battle)
            except Exception:  # noqa: BLE001 — a stale/illegal candidate is just not a match
                continue
            if order.message[len("/choose "):] == choice_str:
                return int(idx)
        return None


def infer_action_indices(
    record: ReconstructionRecord,
    side: str,
    *,
    mappings=None,
    stop_after_decision: Optional[int] = None,
    chunks: "Optional[Sequence[str]]" = None,
    impl: str = "node",
) -> "list[int]":
    """Recover ``side``'s ACTION-INDEX history by replaying its recorded battle and inverting each
    recorded sim-choice string through the real mapper. The counterpart of ``states.npz['actions']``
    for the OPPONENT (the forensic trace records only the trainee's actions), so the opponent's
    one-sided obs can be materialized faithfully for an interior search ply. Refused maybe-trapped
    probes invert to ``None`` and are skipped (queue semantics).

    ``chunks`` (that side's chunks from an ALREADY-run :func:`replay_battle`) skips the internal
    replay — a caller that already replayed the battle (e.g. for the other side's obs) passes them so
    the whole game is replayed through the driver ONCE, not once per side. ``impl`` selects that
    driver (``"node"`` default | ``"rust"``) and is ignored when ``chunks`` is supplied."""
    global _TAG_SEQ
    _TAG_SEQ += 1
    name = record.username(side)
    if chunks is None:
        rep = replay_battle(record, impl=impl)
        chunks = rep.p1_chunks if side == "p1" else rep.p2_chunks
    recorded = [c for (s, c) in record.commands if s == side]
    player = _InvertingReplayPlayer(
        recorded_choices=recorded, stop_after_decision=stop_after_decision, mappings=mappings,
        battle_format=record.format_id,
        account_configuration=AccountConfiguration(name, None),
        server_configuration=LocalhostServerConfiguration,
        start_listening=False, max_concurrent_battles=1)
    client = BattleStreamClient(
        player.ps_client._account_configuration, side=side,
        on_battle_message=player._handle_battle_message,
        on_update_challenges=player._update_challenges,
        on_challenge_request=player._handle_challenge_request, loop=POKE_LOOP)
    player.ps_client = client
    player._current_packed_team = record.packed_team(side)
    tag = record.battle_tag or f"battle-{record.format_id}-recon{_TAG_SEQ}"

    async def _feed_all() -> None:
        inited = False
        for chunk in chunks:
            header = f">{tag}\n"
            if not inited:
                inited = True
                header += "|init|battle\n"
            await client.feed(header + chunk)
            if player.done:
                break

    try:
        if asyncio.get_running_loop() is POKE_LOOP:
            raise RuntimeError("infer_action_indices must not be called from POKE_LOOP")
    except RuntimeError as e:
        if "POKE_LOOP" in str(e):
            raise
    asyncio.run_coroutine_threadsafe(_feed_all(), POKE_LOOP).result()
    # Every materialized decision must have inverted to exactly one action index. A shortfall means a
    # recorded choice failed to invert (an [Invalid choice] round, or a mapper edge) — which would
    # silently DESYNC the opponent's obs (its action history would be a ply short). Fail LOUD instead:
    # a faithful interior-opponent search can't run on this battle.
    if len(player.inverted_actions) != len(player._materialized):
        raise RuntimeError(
            f"infer_action_indices({side}): recovered {len(player.inverted_actions)} action indices for "
            f"{len(player._materialized)} decisions — a recorded choice failed to invert, so the "
            f"opponent's action history would desync its obs. This battle can't drive a faithful "
            f"interior-opponent search (depth ≥ 2).")
    return list(player.inverted_actions)


def materialize_from_record(
    record: ReconstructionRecord,
    *,
    username: Optional[str] = None,
    actions: Sequence[int] = (),
    mappings=None,
    stall_config: Optional[StallConfig] = None,
    map_actions_at: Optional[int] = None,
    stop_after_decision: Optional[int] = None,
    impl: str = "node",
) -> MaterializedTrace:
    """Convenience: replay the full recorded battle and materialize ``username``'s
    one-sided obs at every decision. ``username`` defaults to the record's
    ``trainee_username``. Only the regenerated per-side chunks cross into the
    obs pipeline — never the omniscient record fields. ``impl`` selects the replay driver
    (``"node"`` default | ``"rust"``)."""
    name = username or record.trainee_username
    if not name:
        raise ValueError("record carries no trainee_username — pass username=")
    side = record.side_of(name)
    rep = replay_battle(record, impl=impl)
    chunks = rep.p1_chunks if side == "p1" else rep.p2_chunks
    return materialize_decisions(
        chunks,
        username=name,
        packed_team=record.packed_team(side),
        side=side,
        actions=actions,
        battle_format=record.format_id,
        battle_tag=record.battle_tag,
        mappings=mappings,
        stall_config=stall_config,
        map_actions_at=map_actions_at,
        stop_after_decision=stop_after_decision,
    )
