# Observation Dimensions
POKEMON_VECTOR_DIM = 132
ACTIVE_CONTEXT_DIM = 31
GLOBAL_ENV_DIM = 11

# Sub-dimensions for Pokemon Vector
SPECIES_ID_DIM = 32
ITEM_ID_DIM = 16
ITEM_KNOWN_DIM = 1
COMBINED_TYPES_DIM = 8
ABILITY_SLOT_DIM = 8
ABILITY_KNOWN_DIM = 1
MOVE_SLOT_DIM = 8
MOVES_KNOWN_DIM = 4
CONDITION_DIM = 7
STATS_DIM = 5

# Sub-dimensions for Active Context
BOOSTS_DIM = 14
VOLATILES_DIM = 8
TEMPORAL_DIM = 9

# Max values for normalization
MAX_TURNS = 1000
MAX_SPIKES = 3
MAX_STATS = 255
