# Observation Dimensions
POKEMON_VECTOR_DIM = 132
POKEMON_FULL_DIM = 133 # Vector + Active Flag
ACTIVE_CONTEXT_DIM = 31
GLOBAL_ENV_DIM = 11
REACTIVE_DIM = 15

# Top-level Offsets (Total Dim: 1684)
NUM_POKEMON = 12
TEAM_SIZE = 6
OFFSET_OUR_TEAM = 0
OFFSET_OPP_TEAM = TEAM_SIZE * POKEMON_FULL_DIM # 798
OFFSET_CONTEXT = 2 * OFFSET_OPP_TEAM # 1596
OFFSET_GLOBAL = OFFSET_CONTEXT + (2 * ACTIVE_CONTEXT_DIM) # 1658
OFFSET_REACTIVE = OFFSET_GLOBAL + GLOBAL_ENV_DIM # 1669

# Internal Pokémon Vector Offsets (Total Dim: 132)
POKEMON_SPECIES_OFFSET = 0 # Size 7 (1 ID + 6 Stats)
POKEMON_ITEMS_OFFSET = 37 # Gap of 30 after species
POKEMON_TYPES_OFFSET = 54
POKEMON_ABILITIES_OFFSET = 62
POKEMON_CONDITION_OFFSET = 87
POKEMON_MOVES_OFFSET = 95
POKEMON_HP_OFFSET = 131

# Sub-dimensions
SPECIES_ID_DIM = 32 # This is for embedding, the raw vector has 1 ID + 6 Stats = 7
ITEM_ID_DIM = 16
ITEM_KNOWN_DIM = 1
COMBINED_TYPES_DIM = 8
ABILITY_SLOT_DIM = 8
ABILITY_KNOWN_DIM = 1
MOVE_SLOT_DIM = 8
MOVES_KNOWN_DIM = 4
CONDITION_DIM = 8 # None, BRN, PAR, SLP, FRZ, PSN, TOX, Turn
STATS_DIM = 6 # HP, Atk, Def, SpA, SpD, Spe

# Active Context Sub-dimensions
BOOSTS_DIM = 14
VOLATILES_DIM = 8
TEMPORAL_DIM = 9

# Max values for normalization
MAX_TURNS = 1000
MAX_SPIKES = 3
MAX_STATS = 255
MAX_SPECIES_ID = 387
MAX_MOVE_ID = 371
MAX_ITEM_ID = 130
MAX_ABILITY_ID = 77
TRACE_INTERVAL = 15
