# Observation Dimensions
POKEMON_VECTOR_DIM = 98
POKEMON_FULL_DIM = 99 # Vector + Active Flag
ACTIVE_CONTEXT_DIM = 31
GLOBAL_ENV_DIM = 11
MATCHUP_DIM = 288 # (6*4*6) for Our vs Their + (6*4*6) for Their vs Our
REACTIVE_DIM = 16 + MATCHUP_DIM

# Top-level Offsets (Total Dim: 1565)
NUM_POKEMON = 12
TEAM_SIZE = 6
OFFSET_OUR_TEAM = 0
OFFSET_OPP_TEAM = 6 * POKEMON_FULL_DIM  # 594
OFFSET_CONTEXT = 2 * OFFSET_OPP_TEAM    # 1188
OFFSET_GLOBAL = OFFSET_CONTEXT + (2 * ACTIVE_CONTEXT_DIM) # 1250
OFFSET_REACTIVE = OFFSET_GLOBAL + GLOBAL_ENV_DIM # 1261

# Internal Pokémon Vector Offsets (Total Dim: 102)
POKEMON_SPECIES_OFFSET = 0 # Size 7 (1 ID + 6 Stats)
POKEMON_ITEMS_OFFSET = 7
POKEMON_TYPES_OFFSET = 24  # 7 + 17
POKEMON_ABILITIES_OFFSET = 32 # 24 + 8
POKEMON_CONDITION_OFFSET = 57 # 32 + 25
POKEMON_MOVES_OFFSET = 65    # 57 + 8
POKEMON_HP_OFFSET = 97      # 65 + 32

# Sub-dimensions
SPECIES_ID_DIM = 1 # ID for embedding
ITEM_ID_DIM = 16
ITEM_KNOWN_DIM = 1
COMBINED_TYPES_DIM = 8
ABILITY_SLOT_DIM = 8
ABILITY_KNOWN_DIM = 1
MOVE_SLOT_DIM = 8
MOVES_KNOWN_DIM = 0
CONDITION_DIM = 8 # None, BRN, PAR, SLP, FRZ, PSN, TOX, Turn
STATS_DIM = 6 # HP, Atk, Def, SpA, SpD, Spe

# Active Context Sub-dimensions
BOOSTS_DIM = 14
VOLATILES_DIM = 8
TEMPORAL_DIM = 9

# Max values for normalization
MAX_TURNS = 1000
MAX_SPIKES = 3
MAX_STATS = 255
MAX_SPECIES_ID = 387
MAX_MOVE_ID = 371
MAX_ITEM_ID = 600
MAX_ABILITY_ID = 100
TRACE_INTERVAL = 15
