[pytest]
python_files = *_test.py
python_classes = Test*
python_functions = test_*
testpaths = src tools
norecursedirs = deps node_modules
markers =
    integration: marks tests as integration tests (require a running server)
asyncio_mode = auto
