#!/usr/bin/env bash
# THE REGISTERED CRITIC-ROW PAIR REPORT — arm W as ARM, arm S as CONTROL.
#
# Unlike arm S's standalone read (whose only available control, the 73M win-prob trees, was
# REFUSED on two counts at once: eval_sentinel_greedy arm=True/control=False and n_games
# 800 vs 400), this pair is comparable BY CONSTRUCTION: both frames are offline full-capture
# draws of 800 games x 12 opponents, both at the RECORDED greedy sentinel regime, both from the
# bit-exact eval_traces/step_74000016/snapshot.zip of a completed 75,005,952-step run, both
# generated by the same script with the same two seeds.
#
# 🚨 --v-column win_probs is ROW A: arm W's CRITIC against arm S's AUXILIARY win-prob head
# (--win-prob-coef 0.05). On a --critic shaped run `values` and `win_probs` are DIFFERENT
# READOUTS; the critic-vs-critic contrast (ROW B) is rank-based only and is computed by
# pair_critic_levels.py, because the calibration family and every gate.* row are undefined on a
# raw shaped-return column.
set -u
export PYTHONPATH=/home/goodlad/dev/gen3ai/src
export POKESIM_SIM_BRIDGE_BIN=/home/goodlad/dev/gen3ai/src/rust_sim/target/release/sim_bridge
export CUDA_VISIBLE_DEVICES=""
P=/home/goodlad/miniconda3/envs/gen3ai_stable/bin/python3
TMP=/home/goodlad/.claude/jobs/9ab51de6/tmp
DRAW=${1:-draw1}
cd /home/goodlad/dev/gen3ai
nice -n 15 $P -m main.ops.critic_read ai_v13_02_flywheel_winprob \
  --control ai_v13_01_flywheel_shaped \
  --arm-traces   "$TMP/pair_read/traces/$DRAW/eval_traces/step_74000016" \
  --control-traces "$TMP/armS_reads/traces/$DRAW/eval_traces/step_74000016" \
  --step 74000016 \
  --v-column win_probs \
  --floor-json "$TMP/pair_read/critic/floors_v6_max_imported.json" \
  --nice 15 \
  --out "$TMP/pair_read/critic/read_${DRAW}_W_vs_S" 2>&1
echo "=== EXIT $? $DRAW $(date -Is) ==="
