// @generated by `python -m agents.observation.rust_core_obs_layout --write` — DO NOT EDIT.
// Source of truth: `agents/observation/constants.py` (every offset / dim), `gen3_effects`,
// `turn_view.FAINT_CAUSE_VOCAB`, the Python sub-encoders' index maps, `assembler.SAT_LUT`,
// `sleep_belief`'s wake tables, `gen3_mechanics`' protect floor and poke-env's pre-split
// category map. Pinned by `src/agents/observation/rust_core_obs_layout_test.py`.
#![allow(dead_code)]

/// `Gen3ObservationEncoder.dimension` — the flat row's length.
pub const OBS_DIM: usize = 2761;
/// The `<f4` wire frame's head, which spells the row's shape (`wire.rs`); generated so a
/// layout change moves it with `OBS_DIM` instead of failing a hand-written assert.
pub const FRAME_HEAD: &str = "{\"dtype\":\"<f4\",\"shape\":[2761],\"b64\":\"";
pub const POKEMON_SPECIES_OFFSET: usize = 0;
pub const POKEMON_ITEMS_OFFSET: usize = 7;
pub const POKEMON_TYPES_OFFSET: usize = 10;
pub const POKEMON_ABILITIES_OFFSET: usize = 12;
pub const POKEMON_CONDITION_OFFSET: usize = 16;
pub const POKEMON_MOVES_OFFSET: usize = 23;
pub const POKEMON_HP_OFFSET: usize = 67;
pub const POKEMON_SPECIES_KNOWN_OFFSET: usize = 68;
pub const POKEMON_COUNTER_OFFSET: usize = 69;
pub const POKEMON_SPREAD_OFFSET: usize = 71;
pub const POKEMON_SPREAD_DIM: usize = 18;
pub const POKEMON_HP_REVEALED_OFFSET: usize = 89;
pub const POKEMON_HP_PROBS_OFFSET: usize = 90;
pub const POKEMON_HP_BLOCK_DIM: usize = 17;
pub const POKEMON_SLEEP_BELIEF_OFFSET: usize = 106;
pub const POKEMON_SLEEP_BELIEF_DIM: usize = 3;
pub const POKEMON_RECENCY_OFFSET: usize = 109;
pub const POKEMON_RECENCY_DIM: usize = 3;
pub const POKEMON_PROTECT_OFFSET: usize = 112;
pub const POKEMON_LAST_ACTION_OFFSET: usize = 113;
pub const POKEMON_LAST_ACTION_DIM: usize = 6;
pub const POKEMON_VECTOR_DIM: usize = 119;
pub const POKEMON_TRAPPED_OFFSET: usize = 119;
pub const POKEMON_MAYBE_TRAPPED_OFFSET: usize = 120;
pub const POKEMON_ACTIVE_OFFSET: usize = 121;
pub const POKEMON_FULL_DIM: usize = 122;
pub const SPECIES_ID_DIM: usize = 1;
pub const ITEM_ID_DIM: usize = 1;
pub const ITEM_KNOWN_DIM: usize = 1;
pub const ITEM_CONSUMED_DIM: usize = 1;
pub const COMBINED_TYPES_DIM: usize = 2;
pub const ABILITY_SLOT_DIM: usize = 2;
pub const ABILITY_DOMINANCE_DIM: usize = 1;
pub const ABILITY_KNOWN_DIM: usize = 1;
pub const MOVE_SLOT_DIM: usize = 11;
pub const CONDITION_DIM: usize = 7;
pub const STATS_DIM: usize = 6;
pub const POKEMON_COUNTER_DIM: usize = 2;
pub const BOOSTS_DIM: usize = 14;
pub const VOLATILES_DIM: usize = 46;
pub const ACTIVE_CONTEXT_DIM: usize = 60;
pub const WEATHER_ONEHOT_DIM: usize = 5;
pub const CLOCK_DIM: usize = 3;
pub const CLOCK_OFFSET_IN_GLOBAL: usize = 9;
pub const GLOBAL_ENV_DIM: usize = 20;
pub const REACTIVE_SCALAR_DIM: usize = 5;
pub const ACTIVE_REQ_MOVES_PER: usize = 4;
pub const ACTIVE_REQ_MOVES_DIM: usize = 12;
pub const ACTIVE_REQ_MOVES_OFFSET: usize = 5;
pub const REACTIVE_DIM: usize = 17;
pub const PAIR_HISTORY_CELL_DIM: usize = 5;
pub const PAIR_HISTORY_DIM: usize = 180;
pub const EVENT_WINDOW_N: usize = 32;
pub const EVENT_TOKEN_DIM: usize = 30;
pub const EVENT_WINDOW_DIM: usize = 960;
pub const TEAM_SIZE: usize = 6;
pub const NUM_POKEMON: usize = 12;
pub const OFFSET_OUR_TEAM: usize = 0;
pub const OFFSET_OPP_TEAM: usize = 732;
pub const OFFSET_CONTEXT: usize = 1464;
pub const OFFSET_GLOBAL: usize = 1584;
pub const OFFSET_REACTIVE: usize = 1604;
pub const OFFSET_PAIR_HISTORY: usize = 1621;
pub const OFFSET_EVENT_WINDOW: usize = 1801;
pub const MAX_TURNS: usize = 250;
pub const MAX_SPIKES: usize = 3;
pub const MAX_PP: usize = 64;
pub const EVENT_T_PAD: usize = 0;
pub const EVENT_T_MOVE: usize = 1;
pub const EVENT_T_SWITCH_IN: usize = 2;
pub const EVENT_T_FAINT: usize = 3;
pub const EVENT_T_STATUS_APPLIED: usize = 4;
pub const EVENT_T_STATUS_CURED: usize = 5;
pub const EVENT_T_BOOST: usize = 6;
pub const EVENT_T_ITEM_REVEAL: usize = 7;
pub const EVENT_T_HAZARD: usize = 8;
pub const EVENT_T_SWITCH_REJECTED: usize = 9;
pub const EVENT_T_CANT: usize = 10;
pub const EVENT_T_DENIED: usize = 11;
pub const N_EVENT_TYPES: usize = 12;
pub const ITEM_TR_NONE: usize = 0;
pub const ITEM_TR_REVEALED: usize = 1;
pub const ITEM_TR_CONSUMED: usize = 2;
pub const ITEM_TR_REMOVED: usize = 3;
pub const ITEM_TR_SWAPPED: usize = 4;
pub const ITEM_TR_RECEIVED: usize = 5;
pub const ENTRY_NONE: usize = 0;
pub const ENTRY_CHOSEN: usize = 1;
pub const ENTRY_REPLACEMENT: usize = 2;
pub const ENTRY_DRAG: usize = 3;
pub const ENTRY_BATON_PASS: usize = 4;
pub const DENIAL_NONE: usize = 0;
pub const DENIAL_FAINTED_FIRST: usize = 1;
pub const DENIAL_TURN_CUT: usize = 2;

/// `constants.EventCol` — the 22 columns of one event row, by name.
pub const EV_TYPE: usize = 0;
pub const EV_ACTOR_SPECIES: usize = 1;
pub const EV_ACTOR_SIDE: usize = 2;
pub const EV_TARGET_SPECIES: usize = 3;
pub const EV_MOVE: usize = 4;
pub const EV_MAGNITUDE: usize = 5;
pub const EV_OUT_HIT: usize = 6;
pub const EV_OUT_MISS: usize = 7;
pub const EV_OUT_FAIL: usize = 8;
pub const EV_CRIT: usize = 9;
pub const EV_EFF_NEUTRAL: usize = 10;
pub const EV_EFF_SUPER: usize = 11;
pub const EV_EFF_RESIST: usize = 12;
pub const EV_EFF_IMMUNE: usize = 13;
pub const EV_WE_FIRST: usize = 14;
pub const EV_STATUS: usize = 15;
pub const EV_TURNS_AGO: usize = 16;
pub const EV_FORCED_WINDOW: usize = 17;
pub const EV_VALID: usize = 18;
pub const EV_CANT: usize = 19;
pub const EV_FAINT_CAUSE: usize = 20;
pub const EV_ITEM_TRANSITION: usize = 21;
pub const EV_REL_SPECIES: usize = 22;
pub const EV_REL_SIDE: usize = 23;
pub const EV_ENTRY: usize = 24;
pub const EV_DENIAL: usize = 25;
pub const EV_CALLER: usize = 26;
pub const EV_STAT: usize = 27;
pub const EV_LAYERS: usize = 28;
pub const EV_PURSUIT_SWITCH: usize = 29;

/// `constants.EVENT_STATUS_IDS` (the event row's STATUS column) — also `pokemon._STATUS_STR_IDX`.
pub static EVENT_STATUS_IDS: [(&str, usize); 6] = [("brn", 1), ("par", 2), ("slp", 3), ("frz", 4), ("psn", 5), ("tox", 6)];
pub static CONDITION_STATUS_IDX: [(&str, usize); 6] = [("brn", 1), ("par", 2), ("slp", 3), ("frz", 4), ("psn", 5), ("tox", 6)];

/// `gen3_effects.VOLATILE_SLOTS` — the active context's volatile columns, in order.
pub static VOLATILE_SLOTS: [&str; 46] = ["attract", "bide", "charge", "confusion", "curse", "defensecurl", "destinybond", "disable", "doomdesire", "encore", "endure", "flashfire", "flinch", "focusenergy", "focuspunch", "followme", "foresight", "futuresight", "grudge", "helpinghand", "imprison", "ingrain", "leechseed", "lockedmove", "lockon", "magiccoat", "minimize", "mustrecharge", "nightmare", "partiallytrapped", "protect", "pursuit", "rage", "snatch", "struggle", "substitute", "taunt", "torment", "trapped", "uproar", "yawn", "ability_activated", "perish", "stockpile", "mudsport", "watersport"];
/// `gen3_effects.GEN3_VOLATILE_TO_SLOT` — (id, slot index, value), sorted by id.
pub static VOLATILE_TO_SLOT: [(&str, usize, f64); 70] = [
    ("attract", 0, 1.0),
    ("bide", 1, 1.0),
    ("bind", 29, 1.0),
    ("charge", 2, 1.0),
    ("clamp", 29, 1.0),
    ("confusion", 3, 1.0),
    ("curse", 4, 1.0),
    ("defensecurl", 5, 1.0),
    ("destinybond", 6, 1.0),
    ("disable", 7, 1.0),
    ("doomdesire", 8, 1.0),
    ("encore", 9, 1.0),
    ("endure", 10, 1.0),
    ("firespin", 29, 1.0),
    ("flashfire", 11, 1.0),
    ("flinch", 12, 1.0),
    ("focusenergy", 13, 1.0),
    ("focuspunch", 14, 1.0),
    ("followme", 15, 1.0),
    ("foresight", 16, 1.0),
    ("futuresight", 17, 1.0),
    ("grudge", 18, 1.0),
    ("helpinghand", 19, 1.0),
    ("immunity", 41, 1.0),
    ("imprison", 20, 1.0),
    ("ingrain", 21, 1.0),
    ("insomnia", 41, 1.0),
    ("leechseed", 22, 1.0),
    ("limber", 41, 1.0),
    ("lockedmove", 23, 1.0),
    ("lockon", 24, 1.0),
    ("magiccoat", 25, 1.0),
    ("magmaarmor", 41, 1.0),
    ("mindreader", 24, 1.0),
    ("minimize", 26, 1.0),
    ("mudsport", 44, 1.0),
    ("mustrecharge", 27, 1.0),
    ("nightmare", 28, 1.0),
    ("oblivious", 41, 1.0),
    ("owntempo", 41, 1.0),
    ("partiallytrapped", 29, 1.0),
    ("perish0", 42, 0.25),
    ("perish1", 42, 0.5),
    ("perish2", 42, 0.75),
    ("perish3", 42, 1.0),
    ("protect", 30, 1.0),
    ("pursuit", 31, 1.0),
    ("rage", 32, 1.0),
    ("sandtomb", 29, 1.0),
    ("shedskin", 41, 1.0),
    ("snatch", 33, 1.0),
    ("stickyhold", 41, 1.0),
    ("stockpile", 43, 0.3333333333333333),
    ("stockpile1", 43, 0.3333333333333333),
    ("stockpile2", 43, 0.6666666666666666),
    ("stockpile3", 43, 1.0),
    ("struggle", 34, 1.0),
    ("substitute", 35, 1.0),
    ("suctioncups", 41, 1.0),
    ("synchronize", 41, 1.0),
    ("taunt", 36, 1.0),
    ("torment", 37, 1.0),
    ("trapped", 38, 1.0),
    ("uproar", 39, 1.0),
    ("vitalspirit", 41, 1.0),
    ("watersport", 45, 1.0),
    ("waterveil", 41, 1.0),
    ("whirlpool", 29, 1.0),
    ("wrap", 29, 1.0),
    ("yawn", 40, 1.0),
];
/// `gen3_effects.NOT_A_VOLATILE` — ids that reach the view but encode to nothing.
pub static NOT_A_VOLATILE: [&str; 7] = ["focusband", "healbell", "magnitude", "mist", "safeguard", "spite", "typechange"];
/// `gen3_effects.CANT_REASONS_LIVE` — the event row's CANT column is 1 + the index.
pub static CANT_REASONS_LIVE: [&str; 13] = ["slp", "frz", "par", "flinch", "recharge", "attract", "disable", "taunt", "imprison", "focuspunch", "nopp", "truant", "damp"];
/// `turn_view.FAINT_CAUSE_VOCAB_LIVE` — the event row's FAINT_CAUSE column is 1 + the index
/// (the archive's eight + `destinybond` / `perishsong`, gen3_event_record_v2).
pub static FAINT_CAUSE_VOCAB: [&str; 10] = ["attack", "hazard", "weather", "status", "recoil", "selfko", "leechseed", "other", "destinybond", "perishsong"];

/// `TypeEncoder.TYPE_TO_IDX` — keyed by the `PokemonType` NAME the per-mon block reads
/// (`THREE_QUESTION_MARKS` is NOT a key: a `???`-typed mon reads 0, as in Python), and by the
/// `"???"` spelling the move encoder translates to.
pub static TYPE_TO_IDX: [(&str, usize); 18] = [("NORMAL", 1), ("FIRE", 2), ("WATER", 3), ("GRASS", 4), ("ELECTRIC", 5), ("ICE", 6), ("FIGHTING", 7), ("POISON", 8), ("GROUND", 9), ("FLYING", 10), ("PSYCHIC", 11), ("BUG", 12), ("ROCK", 13), ("GHOST", 14), ("DRAGON", 15), ("STEEL", 16), ("DARK", 17), ("???", 18)];
/// poke-env's `Move._MOVE_CATEGORY_PER_TYPE_PRE_SPLIT`: the `PokemonType` NAMES whose damaging
/// moves are SPECIAL (the rest are PHYSICAL) — `moves._category_val`'s gen-3 source.
pub static SPECIAL_TYPES_PRE_SPLIT: [&str; 9] = ["DARK", "DRAGON", "ELECTRIC", "FIRE", "GRASS", "ICE", "PSYCHIC", "THREE_QUESTION_MARKS", "WATER"];

/// `global_env._WEATHER_IDX` (the `None` key is index 0, the default).
pub static WEATHER_IDX: [(&str, usize); 8] = [("sunnyday", 1), ("desolateland", 1), ("raindance", 2), ("primordialsea", 2), ("sandstorm", 3), ("hail", 4), ("snow", 4), ("snowscape", 4)];
pub const WEATHER_MAX_TURNS: f64 = 5.0;
/// `global_env._LOG_MAX_TURNS` = `math.log(1 + MAX_TURNS)`.
pub const LOG_MAX_TURNS: f64 = 5.5254529391317835;
/// `global_env._SCREEN_CONDITIONS`, as the lower-cased `SideCondition` names the view keys by.
pub static SCREEN_CONDITIONS: [&str; 4] = ["reflect", "light_screen", "safeguard", "mist"];

/// `active_context`'s boost order.
pub static BOOST_ORDER: [&str; 7] = ["atk", "def", "spa", "spd", "spe", "accuracy", "evasion"];
/// `PokemonEncoder._NATURE_STAT_ORDER`.
pub static NATURE_STAT_ORDER: [&str; 5] = ["atk", "def", "spa", "spd", "spe"];

/// `assembler.SAT_LUT` — `log1p(n) / log(11)` for n = 0..=10, in float64.
pub static SAT_LUT: [f64; 11] = [0.0, 0.2890648263178878, 0.45815690999132613, 0.5781296526357756, 0.6711877414712396, 0.7472217363092141, 0.8115075629572489, 0.8671944789536634, 0.9163138199826525, 0.9602525677891275, 1.0];
pub const RECENCY_SAT: usize = 10;
pub const PAIR_SAT: usize = 10;

/// `sleep_belief`'s verified gen-3 wake tables (index = the observed counter, clamped).
pub static SLEEP_OPP_NOEB: [f64; 6] = [0.0, 0.25, 0.3333333333333333, 0.5, 1.0, 1.0];
pub static SLEEP_OPP_EB: [f64; 6] = [0.25, 0.6666666666666666, 1.0, 1.0, 1.0, 1.0];
pub static SLEEP_REST_NOEB: [f64; 6] = [0.0, 0.0, 1.0, 1.0, 1.0, 1.0];
pub static SLEEP_REST_EB: [f64; 6] = [0.0, 1.0, 1.0, 1.0, 1.0, 1.0];
pub const SLEEP_MAX_K: usize = 5;
pub static SLEEP_USABLE_MOVES: [&str; 2] = ["sleeptalk", "snore"];
pub const EARLY_BIRD: &str = "earlybird";
pub const UNKNOWN_ABILITY: &str = "unknownability";

/// `gen3_mechanics._PROTECT_COUNTER_MAX` — the 1/8 floor of the protect-success odds.
pub const PROTECT_COUNTER_MAX: u64 = 8;
/// `wish_belief.WISH_HEAL_FRACTION`.
pub const WISH_HEAL_FRACTION: f64 = 0.5;

