"""GENERATES `src/rust_env/src/bots/tables.rs` — every table and constant the scripted bots read,
from the PYTHON objects the bots themselves read (M5 Lane F).

* MOVES — for every ``GenData.from_gen(3).moves`` id (+ poke-env's synthetic ``recharge`` /
  ``fight`` rows), the value of each ``Move`` PROPERTY a bot reads, taken from a real
  ``Move(id, 3)``: ``base_power``, ``type``, ``category`` (the gen-3 by-type rule), ``accuracy``,
  ``expected_hits``, ``target``, ``boosts``. Floats cross as IEEE-754 bits.
* TWO type charts, because the bots read two: poke-env's ``GenData.from_gen(3).type_chart``
  (``Pokemon.damage_multiplier``) and `agents.gen3_mechanics`' data/-sourced chart
  (``effective_multiplier``). They are equal today; each function reads its own.
* `gen3_mechanics`' ability multipliers, status immunities and move-id sets; the constants of
  `agents/opponents.py`, `agents/baitbot.py` and ``SimpleHeuristicsPlayer``.

``python -m utils.rust_env.bot_tables --write`` regenerates; `bot_tables_test.py` (routine) fails
while the committed file differs from a fresh render.
"""
from __future__ import annotations

import struct
import sys

from utils.paths import src_path

OUT = ("rust_env", "src", "bots", "tables.rs")


def _bits(x) -> str:
    return "0x" + format(struct.unpack("<Q", struct.pack("<d", float(x)))[0], "016x")


def _f(x) -> str:
    return f"f64::from_bits({_bits(x)})"


def _str(s) -> str:
    assert '"' not in s and "\\" not in s, s
    return f'"{s}"'


def _opt(s) -> str:
    return "None" if s is None else f"Some({_str(s)})"


def render() -> str:
    from poke_env.battle.move import Move
    from poke_env.data import GenData
    from poke_env.player.baselines import CURSE_NON_GHOST_BOOSTS, SimpleHeuristicsPlayer as SH

    from agents import baitbot, gen3_mechanics as GM, opponents as O

    gd = GenData.from_gen(3)
    L = ["// @generated by `python -m utils.rust_env.bot_tables --write` — DO NOT EDIT.",
         "// Source of truth: the Python objects the scripted bots read (poke-env `Move` properties,",
         "// `GenData.from_gen(3).type_chart`, `agents.gen3_mechanics`, `agents.opponents`,",
         "// `agents.baitbot`, `SimpleHeuristicsPlayer`). Pinned by `src/utils/rust_env/bot_tables_test.py`.",
         "#![allow(clippy::unreadable_literal)]", "",
         "/// One move as a bot reads it (`Move(id, 3)`'s properties).",
         "pub struct MoveRow {",
         "    pub id: &'static str,",
         "    /// `entry.get(\"basePower\", 0)` (a Hidden Power's override is applied by the caller).",
         "    pub base_power: u32,",
         "    /// `Move.type` — a `PokemonType` NAME.",
         "    pub typ: &'static str,",
         "    /// `Move.category` NAME (gen 3: PHYSICAL / SPECIAL by type; STATUS as the dex says).",
         "    pub category: &'static str,",
         "    pub accuracy: f64,",
         "    pub expected_hits: f64,",
         "    /// `Move.target` — a `Target` NAME, or None.",
         "    pub target: Option<&'static str>,",
         "    /// `Move.boosts` in dict order, or None.",
         "    pub boosts: Option<&'static [(&'static str, i32)]>,",
         "}", "",
         "/// Sorted by id (binary search).",
         "pub static MOVES: &[MoveRow] = &["]
    ids = sorted(set(gd.moves) | {"recharge", "fight"})
    for mid in ids:
        m = Move(mid, 3)
        b = m.boosts
        bj = "None" if b is None else "Some(&[" + ", ".join(f"({_str(k)}, {int(v)})" for k, v in b.items()) + "])"
        L.append(f"    MoveRow {{ id: {_str(mid)}, base_power: {int(m.base_power)}, typ: {_str(m.type.name)}, "
                 f"category: {_str(m.category.name)}, accuracy: {_f(m.accuracy)}, expected_hits: {_f(m.expected_hits)}, "
                 f"target: {_opt(None if m.target is None else m.target.name)}, boosts: {bj} }},")
    L += ["];", ""]

    def chart(name, doc, rows):
        out = [f"/// {doc}", "/// `(defending, attacking, multiplier)`, sorted.",
               f"pub static {name}: &[(&str, &str, f64)] = &["]
        for d in sorted(rows):
            for a in sorted(rows[d]):
                out.append(f"    ({_str(d)}, {_str(a)}, {_f(rows[d][a])}),")
        return out + ["];", ""]

    L += chart("POKEENV_CHART", "`GenData.from_gen(3).type_chart[defending][attacking]` — `Pokemon.damage_multiplier`.",
               gd.type_chart)
    L += chart("MECH_CHART", "`gen3_mechanics._type_chart[defending][attacking]` (data/) — `effective_multiplier`.",
               GM._type_chart)
    L.append("/// `gen3_mechanics._NULL_TYPES` / poke-env's null types (`damage_multiplier` → 1).")
    L.append("pub static NULL_TYPES: &[&str] = &[" + ", ".join(_str(t.name) for t in sorted(GM._NULL_TYPES, key=lambda t: t.name)) + "];")
    L.append("/// `gen3_mechanics._REAL_TYPES` — the attacking/defending keys of the dense `_CHART`.")
    L.append("pub static MECH_REAL_TYPES: &[&str] = &[" + ", ".join(_str(t.name) for t in GM._REAL_TYPES) + "];")
    L += ["", "/// `gen3_mechanics.ABILITY_TYPE_MULTIPLIER`: `(ability, move type, multiplier)`.",
          "pub static ABILITY_TYPE_MULTIPLIER: &[(&str, &str, f64)] = &["]
    for ab, row in GM.ABILITY_TYPE_MULTIPLIER.items():
        for t, v in row.items():
            L.append(f"    ({_str(ab)}, {_str(t.name)}, {_f(v)}),")
    L += ["];", "", "/// `gen3_mechanics.STATUS_MOVE_IMMUNITY`: `(move id, immune type)`.",
          "pub static STATUS_MOVE_IMMUNITY: &[(&str, &str)] = &["]
    for mid, types in GM.STATUS_MOVE_IMMUNITY.items():
        for t in sorted(types, key=lambda t: t.name):
            L.append(f"    ({_str(mid)}, {_str(t.name)}),")
    L.append("];")

    def idset(name, doc, s):
        L.extend(["", f"/// {doc}", f"pub static {name}: &[&str] = &[" + ", ".join(_str(x) for x in sorted(s)) + "];"])

    idset("STATUS_MOVES", "`gen3_mechanics.STATUS_MOVES`.", GM.STATUS_MOVES)
    idset("RECOVERY_MOVES", "`gen3_mechanics.RECOVERY_MOVES`.", GM.RECOVERY_MOVES)
    idset("HAZARD_CLEAR_MOVES", "`gen3_mechanics.HAZARD_CLEAR_MOVES`.", GM.HAZARD_CLEAR_MOVES)
    idset("PROTECT_MOVES", "`gen3_mechanics.INVULNERABLE_MOVES` (opponents.py `_PROTECT_MOVES`).", GM.INVULNERABLE_MOVES)
    idset("SETUP_MOVES", "`gen3_mechanics.SETUP_MOVES`.", GM.SETUP_MOVES)
    idset("SETUP_STATS", "`opponents._SETUP_STATS`.", O._SETUP_STATS)
    idset("ANTI_HAZARDS_MOVES", "`SimpleHeuristicsPlayer.ANTI_HAZARDS_MOVES`.", SH.ANTI_HAZARDS_MOVES)
    L += ["", "/// `baselines.CURSE_NON_GHOST_BOOSTS` (dict order) — a non-Ghost user's Curse, for `self_setup_boosts`.",
          "pub static CURSE_NON_GHOST_BOOSTS: &[(&str, i32)] = &["
          + ", ".join(f"({_str(k)}, {int(v)})" for k, v in CURSE_NON_GHOST_BOOSTS.items()) + "];"]
    L += ["", "/// `SimpleHeuristicsPlayer.ENTRY_HAZARDS` (dict order; `stealhrock` is upstream's own spelling).",
          "pub static ENTRY_HAZARDS: &[(&str, &str)] = &["]
    L += [f"    ({_str(k)}, {_str(v.name)})," for k, v in SH.ENTRY_HAZARDS.items()]
    L += ["];", ""]
    consts = [
        ("SPEED_TIER_COEFICIENT", SH.SPEED_TIER_COEFICIENT), ("HP_FRACTION_COEFICIENT", SH.HP_FRACTION_COEFICIENT),
        ("SWITCH_OUT_MATCHUP_THRESHOLD", SH.SWITCH_OUT_MATCHUP_THRESHOLD),
        ("RECOVERY_HP_THRESHOLD", O._RECOVERY_HP_THRESHOLD), ("PROTECT_PROBABILITY", O._PROTECT_PROBABILITY),
        ("AVG_DAMAGE_ROLL", O._AVG_DAMAGE_ROLL), ("KO_FRACTION", O._KO_FRACTION), ("WALL_FRACTION", O._WALL_FRACTION),
        ("SETUP_HP_THRESHOLD", O._SETUP_HP_THRESHOLD), ("KO_FINISH_THRESHOLD", O._KO_FINISH_THRESHOLD),
        ("STATUS_WALL_HP_THRESHOLD", O._STATUS_WALL_HP_THRESHOLD), ("DEFAULT_P_BAIT", baitbot.DEFAULT_P_BAIT),
    ]
    for name, v in consts:
        L.append(f"/// Python value `{v!r}`.")
        L.append(f"pub const {name}: f64 = {_f(v)};")
    L.append("/// `opponents._SETUP_BOOST_CAP` (an int in Python).")
    L.append(f"pub const SETUP_BOOST_CAP: i32 = {int(O._SETUP_BOOST_CAP)};")
    assert isinstance(O._SETUP_BOOST_CAP, int)
    return "\n".join(L) + "\n"


def path():
    return src_path(*OUT)


if __name__ == "__main__":
    text = render()
    if "--write" in sys.argv:
        path().parent.mkdir(parents=True, exist_ok=True)
        path().write_text(text)
        print(f"wrote {path()} ({text.count(chr(10))} lines)")
    else:
        sys.stdout.write(text)
