"""X5 A/B LOOK 2: the read, at the registered n = 5 seeds per arm (design_x5_belief_tokens.md §7.4, §7.9). For each
of the two strength reads it reads the family's look-1 AND look-2 requests through ``main.h2h.cross``'s declared
family read, builds the FULL 5 × 5 matrix (look 1's 9 cells + look 2's 16), and decides at look 2 (boundary 2.683 on
df 8; futility Δ̂ ≤ −δ; rule 8) → ``result.json`` + ``result.md`` beside this file.

    PYTHONPATH=<tree>/src python read_look2.py [--root <ledger root>] [--progress]

``--progress`` prints per-request cell counts only (an interim read is PROGRESS, never a verdict). A missing / short /
aborted cell, a cell recorded under BOTH looks, a look-2 cell that is a look-1 cell, or a broken precondition makes
that read INCONCLUSIVE (never interpreted). The oracle arms are not extended at look 2 (§7.6: reference arms; look 1's
oracle reads stand in ``../x5ab_look1_2026-10-06/``).

DRY RUN ONLY: ``--models``, ``--seeds``, ``--look1-seeds``, ``--min-pairs`` and ``--out-dir`` point the same code at a
scratch ledger; a read off the registered seeds or below 1,000 pairs is INCONCLUSIVE by construction (the statistic
is still printed, to prove the path)."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Sequence

sys.path.insert(0, str(Path(__file__).resolve().parent))
from agents.training import eval_ledger as L  # noqa: E402
from main.h2h import cross as X  # noqa: E402
import plan_look2 as PLAN  # noqa: E402

HERE = Path(__file__).resolve().parent
LOOK = 2


def _fmt_stat(st: Any) -> str:
    if not st:
        return "INCONCLUSIVE (no statistic)"
    lo, hi = st["ci95_pp"]
    return (f"Δ̂ {st['delta_hat_pp']:+.2f} pp [{lo:+.2f}, {hi:+.2f}], t {st['t']:.3f} (= (Δ̂ + δ) / SE) on {st['df']} "
            f"df, SE {st['se_pp']:.2f}, upper one-sided 95 % {st['upper95_one_sided_pp']:+.2f}")


def _matrix(st: Any, rows: List[str], cols: List[str], look1: int) -> List[str]:
    out = ["| row \\ col | " + " | ".join(cols) + " | row mean |", "|---" * (len(cols) + 2) + "|"]
    for i, (r, line, rm) in enumerate(zip(rows, st["h_pp"], st["row_means_pp"])):
        cells = [f"{x:.2f}" if (i < look1 and j < look1) else f"**{x:.2f}**" for j, x in enumerate(line)]
        out.append(f"| {r} | " + " | ".join(cells) + f" | {rm:.2f} |")
    out.append("| col mean | " + " | ".join(f"{x:.2f}" for x in st["col_means_pp"]) + " | |")
    return out


def read_one(root: Path, read: str, got: Dict[str, Dict[int, Path]], seeds: Sequence[int],
             look1_seeds: Sequence[int], fails: List[str], min_pairs: int) -> Dict[str, Any]:
    fam, req1, req2 = PLAN.READS[read]
    c1, c2 = PLAN.look_cells(root, fam, req1), PLAN.look_cells(root, fam, req2)
    rows_p, cols_p = PLAN.rows_cols(got, read)
    rs = [PLAN.sha(rows_p[s]) for s in seeds if s in rows_p]
    cs = [PLAN.sha(cols_p[s]) for s in seeds if s in cols_p]
    reasons = list(fails)
    # the uniqueness guard, read side: look 2 holds no look-1 cell, and look 1 holds exactly its registered cells
    k1 = {(c.player, c.opponent) for c in c1}
    old = {(PLAN.sha(rows_p[r]), PLAN.sha(cols_p[c])) for r in look1_seeds for c in look1_seeds
           if r in rows_p and c in cols_p}
    dup = [f"{c.player_id} vs {c.opponent_id}" for c in c2 if (c.player, c.opponent) in k1]
    if dup:
        reasons.append(f"{req2} replays look-1 cell(s): {dup}")
    if k1 != old:
        reasons.append(f"{req1} holds {len(k1)} cell(s), not exactly the registered {len(old)} look-1 cells")
    m = X.matrix_from_cells(list(c1) + list(c2), rs, cs, min_pairs=min_pairs)
    st = None
    if m.h is not None:                       # the statistic, even when an outer reason makes the read INCONCLUSIVE
        try:
            st = X.cross_stat(m.h).as_dict()
        except X.CrossInputError as e:       # a matrix the statistic is not defined on is an invalid input
            reasons.append(f"cross statistic undefined: {e}")
    d = X.summarize(LOOK, m, reasons)
    return {"family": fam, "requests": [req1, req2], "n_cells_look1": len(c1), "n_cells_look2": len(c2),
            "decision": d.as_dict(), "verdict": X.verdict_text(d), "stat_shown": st, "cells": list(m.cells),
            "rows": [PLAN.label(rows_p[s]) for s in seeds if s in rows_p],
            "cols": [PLAN.label(cols_p[s]) for s in seeds if s in cols_p],
            "row_sha256": rs, "col_sha256": cs}


def render_md(out: Dict[str, Any]) -> str:
    seeds = out["seeds"]
    n1 = len(out["look1_seeds"])
    b = X.LOOK_BOUNDARIES[LOOK]
    L_: List[str] = ["# X5 A/B look 2 — the read (generated by read_look2.py)", ""]
    if out["dry_run"]:
        L_ += [f"**DRY RUN** (min pairs {out['min_pairs']}, seeds {seeds}): not a read of the experiment.", ""]
    L_ += [f"## Strength (registered, design_x5_belief_tokens.md §7.4 / §7.9; look {LOOK}, n = {len(seeds)}, "
           f"df {2 * (len(seeds) - 1)}, NON-INFERIOR iff t ≥ {b}; FUTILITY STOP iff Δ̂ ≤ −3.5 pp; rule 8)", ""]
    for name, rows in (("matched_steps", "fm 15M"), ("matched_wall_time", "fm 12M")):
        e = out.get(name)
        if e is None:
            continue
        d = e["decision"]
        L_ += [f"### {name.replace('_', ' ')}: **{e['verdict']}**", "",
               f"- {_fmt_stat(d['stat'] or e['stat_shown'])}; boundary {d['boundary']}",
               f"- cells: {e['n_cells_look1']} from {e['requests'][0]} + {e['n_cells_look2']} from {e['requests'][1]}",
               f"- reasons: {d['reasons'] or 'none'}; near a boundary: {d['near_boundary'] or 'none'}", ""]
        st = d["stat"] or e["stat_shown"]
        if st:
            L_ += [f"h_ij = {rows} seed i's score (pp) vs blob 15M seed j (look-2 cells in bold):", ""]
            L_ += _matrix(st, [f"fm s{s}" for s in seeds], [f"blob s{s}" for s in seeds], n1) + [""]
    L_ += ["## Preconditions", "", f"- failures: {out['preconditions'] or 'none'}"]
    return "\n".join(L_) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=None)
    ap.add_argument("--progress", action="store_true")
    ap.add_argument("--models", default=str(PLAN.ARCHIVE_MODELS))
    ap.add_argument("--seeds", type=int, nargs="+", default=list(PLAN.SEEDS))
    ap.add_argument("--look1-seeds", type=int, nargs="+", default=list(PLAN.LOOK1_SEEDS))
    ap.add_argument("--min-pairs", type=int, default=X.MIN_PAIRS)
    ap.add_argument("--out-dir", default=str(HERE))
    ap.add_argument("--reads", nargs="+", default=["steps", "wall"], choices=["steps", "wall"])
    a = ap.parse_args()
    root = Path(a.root) if a.root else L.archive_ledger_root()
    dry = (a.min_pairs != X.MIN_PAIRS or list(a.seeds) != list(PLAN.SEEDS)
           or list(a.look1_seeds) != list(PLAN.LOOK1_SEEDS) or Path(a.models) != PLAN.ARCHIVE_MODELS)
    if dry and Path(a.out_dir).resolve() == HERE:
        print("REFUSED: a dry-run read never writes result.* beside this file (pass --out-dir)", file=sys.stderr)
        return 3
    if a.progress:
        for read in a.reads:
            fam, r1, r2 = PLAN.READS[read]
            for req in (r1, r2):
                cs = PLAN.look_cells(root, fam, req)
                done = sum(1 for c in cs if c.n_pairs >= a.min_pairs)
                print(f"{read} {req}: {len(cs)} cells, {done} at >= {a.min_pairs} pairs, "
                      f"{sum(c.n_pairs for c in cs)} pairs, aborted {sum(c.aborted for c in cs)}")
        return 0
    got, fails = PLAN.resolve(Path(a.models), a.seeds)
    out: Dict[str, Any] = {"look": LOOK, "dry_run": dry, "min_pairs": a.min_pairs, "seeds": a.seeds,
                           "look1_seeds": a.look1_seeds, "preconditions": fails,
                           "cited": ["blob-path identity at 708dcb0a vs e5e660dd (ledger 2026-10-06 BANK)",
                                     "restarts / crashes / init_num_threads: the runs' ledger BANK entries"]}
    for read, name in (("steps", "matched_steps"), ("wall", "matched_wall_time")):
        if read in a.reads:
            out[name] = read_one(root, read, got, a.seeds, a.look1_seeds, fails, a.min_pairs)
    od = Path(a.out_dir)
    od.mkdir(parents=True, exist_ok=True)
    (od / "result.json").write_text(json.dumps(out, indent=1, sort_keys=True, default=str) + "\n")
    (od / "result.md").write_text(render_md(out))
    print(json.dumps({k: out[k]["verdict"] for k in ("matched_steps", "matched_wall_time") if k in out}, indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
