// @generated by `python -m agents.battle.rust_core_schema --write` — DO NOT EDIT.
// Source of truth: `agents/battle/battle_event.py` (MESSAGE_POLICY, EVENT_KIND, EventKind,
// EVENT_VALUE_KEYS, EVENT_OPTIONAL_KEYS) + `Player.MESSAGES_TO_IGNORE`. Pinned by
// `src/agents/battle/rust_core_schema_test.py`.

use super::{Intercept, Route};

/// `agents.battle.battle_event.EventKind`, with its stable integer values.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EventKind {
    Move = 1,
    Switch = 2,
    Drag = 3,
    Faint = 4,
    Damage = 5,
    Heal = 6,
    Boost = 7,
    Unboost = 8,
    Setboost = 9,
    Clearboost = 10,
    Status = 11,
    Curestatus = 12,
    Cant = 13,
    Crit = 14,
    Miss = 15,
    Fail = 16,
    Immune = 17,
    Resisted = 18,
    Supereffective = 19,
    Item = 20,
    Enditem = 21,
    Ability = 22,
    Weather = 23,
    Field = 24,
    Side = 25,
    VolatileStart = 26,
    VolatileEnd = 27,
    Activate = 28,
    Prepare = 29,
    Mustrecharge = 30,
    Transform = 31,
    Formechange = 32,
    Swap = 33,
    Sethp = 34,
    ChoiceRejected = 35,
    Unknown = 99,
}

impl EventKind {
    /// The Python enum member NAME (`MOVE`, `CHOICE_REJECTED`, …).
    pub fn name(self) -> &'static str {
        match self {
            EventKind::Move => "MOVE",
            EventKind::Switch => "SWITCH",
            EventKind::Drag => "DRAG",
            EventKind::Faint => "FAINT",
            EventKind::Damage => "DAMAGE",
            EventKind::Heal => "HEAL",
            EventKind::Boost => "BOOST",
            EventKind::Unboost => "UNBOOST",
            EventKind::Setboost => "SETBOOST",
            EventKind::Clearboost => "CLEARBOOST",
            EventKind::Status => "STATUS",
            EventKind::Curestatus => "CURESTATUS",
            EventKind::Cant => "CANT",
            EventKind::Crit => "CRIT",
            EventKind::Miss => "MISS",
            EventKind::Fail => "FAIL",
            EventKind::Immune => "IMMUNE",
            EventKind::Resisted => "RESISTED",
            EventKind::Supereffective => "SUPEREFFECTIVE",
            EventKind::Item => "ITEM",
            EventKind::Enditem => "ENDITEM",
            EventKind::Ability => "ABILITY",
            EventKind::Weather => "WEATHER",
            EventKind::Field => "FIELD",
            EventKind::Side => "SIDE",
            EventKind::VolatileStart => "VOLATILE_START",
            EventKind::VolatileEnd => "VOLATILE_END",
            EventKind::Activate => "ACTIVATE",
            EventKind::Prepare => "PREPARE",
            EventKind::Mustrecharge => "MUSTRECHARGE",
            EventKind::Transform => "TRANSFORM",
            EventKind::Formechange => "FORMECHANGE",
            EventKind::Swap => "SWAP",
            EventKind::Sethp => "SETHP",
            EventKind::ChoiceRejected => "CHOICE_REJECTED",
            EventKind::Unknown => "UNKNOWN",
        }
    }
    /// `EVENT_VALUE_KEYS[kind]` — the keys a consumer may rely on.
    pub fn required_keys(self) -> &'static [&'static str] {
        match self {
            EventKind::Move => &["move_id"],
            EventKind::Switch => &[],
            EventKind::Drag => &[],
            EventKind::Faint => &[],
            EventKind::Damage => &["amount"],
            EventKind::Heal => &["amount"],
            EventKind::Boost => &["amount", "stat"],
            EventKind::Unboost => &["amount", "stat"],
            EventKind::Setboost => &["amount", "stat"],
            EventKind::Clearboost => &["op"],
            EventKind::Status => &["status"],
            EventKind::Curestatus => &["status"],
            EventKind::Cant => &["reason"],
            EventKind::Crit => &[],
            EventKind::Miss => &[],
            EventKind::Fail => &[],
            EventKind::Immune => &["multiplier"],
            EventKind::Resisted => &["multiplier"],
            EventKind::Supereffective => &["multiplier"],
            EventKind::Item => &["item"],
            EventKind::Enditem => &["item"],
            EventKind::Ability => &["ability"],
            EventKind::Weather => &["weather"],
            EventKind::Field => &["effect"],
            EventKind::Side => &["condition"],
            EventKind::VolatileStart => &["effect"],
            EventKind::VolatileEnd => &["effect"],
            EventKind::Activate => &["effect"],
            EventKind::Prepare => &[],
            EventKind::Mustrecharge => &[],
            EventKind::Transform => &[],
            EventKind::Formechange => &[],
            EventKind::Swap => &[],
            EventKind::Sethp => &["hp"],
            EventKind::ChoiceRejected => &[],
            EventKind::Unknown => &[],
        }
    }
    /// `EVENT_OPTIONAL_KEYS[kind]` — the rest of the declared vocabulary.
    pub fn optional_keys(self) -> &'static [&'static str] {
        match self {
            EventKind::Move => &["from_move", "pursuit_switch", "target_status"],
            EventKind::Switch => &[],
            EventKind::Drag => &[],
            EventKind::Faint => &[],
            EventKind::Damage => &["hp_after", "reason"],
            EventKind::Heal => &["hp_after", "reason"],
            EventKind::Boost => &[],
            EventKind::Unboost => &[],
            EventKind::Setboost => &[],
            EventKind::Clearboost => &[],
            EventKind::Status => &["reason"],
            EventKind::Curestatus => &["op"],
            EventKind::Cant => &["move", "of", "of_actor", "of_side"],
            EventKind::Crit => &["from"],
            EventKind::Miss => &["from"],
            EventKind::Fail => &["from"],
            EventKind::Immune => &[],
            EventKind::Resisted => &[],
            EventKind::Supereffective => &[],
            EventKind::Item => &["from", "of"],
            EventKind::Enditem => &["from", "of"],
            EventKind::Ability => &["from", "of", "op"],
            EventKind::Weather => &["from", "of"],
            EventKind::Field => &["op"],
            EventKind::Side => &["op"],
            EventKind::VolatileStart => &["from", "of", "op"],
            EventKind::VolatileEnd => &["from", "of", "op"],
            EventKind::Activate => &["from", "of"],
            EventKind::Prepare => &[],
            EventKind::Mustrecharge => &[],
            EventKind::Transform => &[],
            EventKind::Formechange => &["op"],
            EventKind::Swap => &[],
            EventKind::Sethp => &["amount", "reason"],
            EventKind::ChoiceRejected => &["reason"],
            EventKind::Unknown => &[],
        }
    }
}

/// Every protocol keyword the core knows, one variant each (`Plain` = a line with no `|`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Kw {
    /// `||`
    Separator,
    /// `|-ability|`
    Ability,
    /// `|-activate|`
    Activate,
    /// `|-anim|`
    Anim,
    /// `|-block|`
    Block,
    /// `|-boost|`
    Boost,
    /// `|-burst|`
    Burst,
    /// `|-center|`
    Center,
    /// `|-clearallboost|`
    Clearallboost,
    /// `|-clearboost|`
    Clearboost,
    /// `|-clearnegativeboost|`
    Clearnegativeboost,
    /// `|-clearpositiveboost|`
    Clearpositiveboost,
    /// `|-combine|`
    Combine,
    /// `|-copyboost|`
    Copyboost,
    /// `|-crit|`
    Crit,
    /// `|-curestatus|`
    Curestatus,
    /// `|-cureteam|`
    Cureteam,
    /// `|-damage|`
    Damage,
    /// `|-end|`
    End,
    /// `|-endability|`
    Endability,
    /// `|-enditem|`
    Enditem,
    /// `|-fail|`
    Fail,
    /// `|-fieldactivate|`
    Fieldactivate,
    /// `|-fieldend|`
    Fieldend,
    /// `|-fieldstart|`
    Fieldstart,
    /// `|-formechange|`
    Formechange,
    /// `|-heal|`
    Heal,
    /// `|-hint|`
    Hint,
    /// `|-hitcount|`
    Hitcount,
    /// `|-immune|`
    Immune,
    /// `|-invertboost|`
    Invertboost,
    /// `|-item|`
    Item,
    /// `|-mega|`
    Mega,
    /// `|-message|`
    Message,
    /// `|-miss|`
    Miss,
    /// `|-mustrecharge|`
    Mustrecharge,
    /// `|-notarget|`
    Notarget,
    /// `|-nothing|`
    Nothing,
    /// `|-ohko|`
    Ohko,
    /// `|-prepare|`
    Prepare,
    /// `|-primal|`
    Primal,
    /// `|-resisted|`
    Resisted,
    /// `|-setboost|`
    Setboost,
    /// `|-sethp|`
    Sethp,
    /// `|-sideend|`
    Sideend,
    /// `|-sidestart|`
    Sidestart,
    /// `|-singlemove|`
    Singlemove,
    /// `|-singleturn|`
    Singleturn,
    /// `|-start|`
    Start,
    /// `|-status|`
    Status,
    /// `|-supereffective|`
    Supereffective,
    /// `|-swapboost|`
    Swapboost,
    /// `|-swapsideconditions|`
    Swapsideconditions,
    /// `|-terastallize|`
    Terastallize,
    /// `|-transform|`
    Transform,
    /// `|-unboost|`
    Unboost,
    /// `|-waiting|`
    Waiting,
    /// `|-weather|`
    Weather,
    /// `|-zbroken|`
    Zbroken,
    /// `|-zpower|`
    Zpower,
    /// `|:|`
    Colon,
    /// `|J|`
    JoinUpper,
    /// `|L|`
    LeaveUpper,
    /// `|askreg|`
    Askreg,
    /// `|badge|`
    Badge,
    /// `|bigerror|`
    Bigerror,
    /// `|c|`
    C,
    /// `|c:|`
    ChatTimestamped,
    /// `|cant|`
    Cant,
    /// `|chat|`
    Chat,
    /// `|clearpoke|`
    Clearpoke,
    /// `|crit|`
    BareCrit,
    /// `|debug|`
    Debug,
    /// `|deinit|`
    Deinit,
    /// `|detailschange|`
    Detailschange,
    /// `|drag|`
    Drag,
    /// `|error|`
    Error,
    /// `|expire|`
    Expire,
    /// `|faint|`
    Faint,
    /// `|gametype|`
    Gametype,
    /// `|gen|`
    Gen,
    /// `|hidelines|`
    Hidelines,
    /// `|html|`
    Html,
    /// `|immune|`
    BareImmune,
    /// `|inactive|`
    Inactive,
    /// `|inactiveoff|`
    Inactiveoff,
    /// `|init|`
    Init,
    /// `|j|`
    JoinShort,
    /// `|join|`
    Join,
    /// `|l|`
    LeaveShort,
    /// `|leave|`
    Leave,
    /// `|message|`
    BareMessage,
    /// `|move|`
    Move,
    /// `|n|`
    RenameShort,
    /// `|name|`
    Name,
    /// `|noinit|`
    Noinit,
    /// `|notify|`
    Notify,
    /// `|player|`
    Player,
    /// `|poke|`
    Poke,
    /// `|popup|`
    Popup,
    /// `|rated|`
    Rated,
    /// `|raw|`
    Raw,
    /// `|replace|`
    Replace,
    /// `|request|`
    Request,
    /// `|resisted|`
    BareResisted,
    /// `|rule|`
    Rule,
    /// `|sentchoice|`
    Sentchoice,
    /// `|showteam|`
    Showteam,
    /// `|split|`
    Split,
    /// `|start|`
    BareStart,
    /// `|supereffective|`
    BareSupereffective,
    /// `|swap|`
    Swap,
    /// `|switch|`
    Switch,
    /// `|t:|`
    Timestamp,
    /// `|teampreview|`
    Teampreview,
    /// `|teamsize|`
    Teamsize,
    /// `|tempnotify|`
    Tempnotify,
    /// `|tempnotifyoff|`
    Tempnotifyoff,
    /// `|tie|`
    Tie,
    /// `|tier|`
    Tier,
    /// `|title|`
    Title,
    /// `|turn|`
    Turn,
    /// `|uhtml|`
    Uhtml,
    /// `|uhtmlchange|`
    Uhtmlchange,
    /// `|upkeep|`
    Upkeep,
    /// `|win|`
    Win,
    /// `|zbroken|`
    BareZbroken,
    /// A line that does not start with `|` (poke-env ignores it: a one-element split).
    Plain,
}

impl Kw {
    /// The protocol keyword text.
    pub fn as_str(self) -> &'static str {
        match self {
            Kw::Separator => "",
            Kw::Ability => "-ability",
            Kw::Activate => "-activate",
            Kw::Anim => "-anim",
            Kw::Block => "-block",
            Kw::Boost => "-boost",
            Kw::Burst => "-burst",
            Kw::Center => "-center",
            Kw::Clearallboost => "-clearallboost",
            Kw::Clearboost => "-clearboost",
            Kw::Clearnegativeboost => "-clearnegativeboost",
            Kw::Clearpositiveboost => "-clearpositiveboost",
            Kw::Combine => "-combine",
            Kw::Copyboost => "-copyboost",
            Kw::Crit => "-crit",
            Kw::Curestatus => "-curestatus",
            Kw::Cureteam => "-cureteam",
            Kw::Damage => "-damage",
            Kw::End => "-end",
            Kw::Endability => "-endability",
            Kw::Enditem => "-enditem",
            Kw::Fail => "-fail",
            Kw::Fieldactivate => "-fieldactivate",
            Kw::Fieldend => "-fieldend",
            Kw::Fieldstart => "-fieldstart",
            Kw::Formechange => "-formechange",
            Kw::Heal => "-heal",
            Kw::Hint => "-hint",
            Kw::Hitcount => "-hitcount",
            Kw::Immune => "-immune",
            Kw::Invertboost => "-invertboost",
            Kw::Item => "-item",
            Kw::Mega => "-mega",
            Kw::Message => "-message",
            Kw::Miss => "-miss",
            Kw::Mustrecharge => "-mustrecharge",
            Kw::Notarget => "-notarget",
            Kw::Nothing => "-nothing",
            Kw::Ohko => "-ohko",
            Kw::Prepare => "-prepare",
            Kw::Primal => "-primal",
            Kw::Resisted => "-resisted",
            Kw::Setboost => "-setboost",
            Kw::Sethp => "-sethp",
            Kw::Sideend => "-sideend",
            Kw::Sidestart => "-sidestart",
            Kw::Singlemove => "-singlemove",
            Kw::Singleturn => "-singleturn",
            Kw::Start => "-start",
            Kw::Status => "-status",
            Kw::Supereffective => "-supereffective",
            Kw::Swapboost => "-swapboost",
            Kw::Swapsideconditions => "-swapsideconditions",
            Kw::Terastallize => "-terastallize",
            Kw::Transform => "-transform",
            Kw::Unboost => "-unboost",
            Kw::Waiting => "-waiting",
            Kw::Weather => "-weather",
            Kw::Zbroken => "-zbroken",
            Kw::Zpower => "-zpower",
            Kw::Colon => ":",
            Kw::JoinUpper => "J",
            Kw::LeaveUpper => "L",
            Kw::Askreg => "askreg",
            Kw::Badge => "badge",
            Kw::Bigerror => "bigerror",
            Kw::C => "c",
            Kw::ChatTimestamped => "c:",
            Kw::Cant => "cant",
            Kw::Chat => "chat",
            Kw::Clearpoke => "clearpoke",
            Kw::BareCrit => "crit",
            Kw::Debug => "debug",
            Kw::Deinit => "deinit",
            Kw::Detailschange => "detailschange",
            Kw::Drag => "drag",
            Kw::Error => "error",
            Kw::Expire => "expire",
            Kw::Faint => "faint",
            Kw::Gametype => "gametype",
            Kw::Gen => "gen",
            Kw::Hidelines => "hidelines",
            Kw::Html => "html",
            Kw::BareImmune => "immune",
            Kw::Inactive => "inactive",
            Kw::Inactiveoff => "inactiveoff",
            Kw::Init => "init",
            Kw::JoinShort => "j",
            Kw::Join => "join",
            Kw::LeaveShort => "l",
            Kw::Leave => "leave",
            Kw::BareMessage => "message",
            Kw::Move => "move",
            Kw::RenameShort => "n",
            Kw::Name => "name",
            Kw::Noinit => "noinit",
            Kw::Notify => "notify",
            Kw::Player => "player",
            Kw::Poke => "poke",
            Kw::Popup => "popup",
            Kw::Rated => "rated",
            Kw::Raw => "raw",
            Kw::Replace => "replace",
            Kw::Request => "request",
            Kw::BareResisted => "resisted",
            Kw::Rule => "rule",
            Kw::Sentchoice => "sentchoice",
            Kw::Showteam => "showteam",
            Kw::Split => "split",
            Kw::BareStart => "start",
            Kw::BareSupereffective => "supereffective",
            Kw::Swap => "swap",
            Kw::Switch => "switch",
            Kw::Timestamp => "t:",
            Kw::Teampreview => "teampreview",
            Kw::Teamsize => "teamsize",
            Kw::Tempnotify => "tempnotify",
            Kw::Tempnotifyoff => "tempnotifyoff",
            Kw::Tie => "tie",
            Kw::Tier => "tier",
            Kw::Title => "title",
            Kw::Turn => "turn",
            Kw::Uhtml => "uhtml",
            Kw::Uhtmlchange => "uhtmlchange",
            Kw::Upkeep => "upkeep",
            Kw::Win => "win",
            Kw::BareZbroken => "zbroken",
            Kw::Plain => "",
        }
    }
    /// The keyword for protocol text, or `None` for a keyword the schema does not know.
    pub fn from_protocol(s: &str) -> Option<Kw> {
        Some(match s {
            "" => Kw::Separator,
            "-ability" => Kw::Ability,
            "-activate" => Kw::Activate,
            "-anim" => Kw::Anim,
            "-block" => Kw::Block,
            "-boost" => Kw::Boost,
            "-burst" => Kw::Burst,
            "-center" => Kw::Center,
            "-clearallboost" => Kw::Clearallboost,
            "-clearboost" => Kw::Clearboost,
            "-clearnegativeboost" => Kw::Clearnegativeboost,
            "-clearpositiveboost" => Kw::Clearpositiveboost,
            "-combine" => Kw::Combine,
            "-copyboost" => Kw::Copyboost,
            "-crit" => Kw::Crit,
            "-curestatus" => Kw::Curestatus,
            "-cureteam" => Kw::Cureteam,
            "-damage" => Kw::Damage,
            "-end" => Kw::End,
            "-endability" => Kw::Endability,
            "-enditem" => Kw::Enditem,
            "-fail" => Kw::Fail,
            "-fieldactivate" => Kw::Fieldactivate,
            "-fieldend" => Kw::Fieldend,
            "-fieldstart" => Kw::Fieldstart,
            "-formechange" => Kw::Formechange,
            "-heal" => Kw::Heal,
            "-hint" => Kw::Hint,
            "-hitcount" => Kw::Hitcount,
            "-immune" => Kw::Immune,
            "-invertboost" => Kw::Invertboost,
            "-item" => Kw::Item,
            "-mega" => Kw::Mega,
            "-message" => Kw::Message,
            "-miss" => Kw::Miss,
            "-mustrecharge" => Kw::Mustrecharge,
            "-notarget" => Kw::Notarget,
            "-nothing" => Kw::Nothing,
            "-ohko" => Kw::Ohko,
            "-prepare" => Kw::Prepare,
            "-primal" => Kw::Primal,
            "-resisted" => Kw::Resisted,
            "-setboost" => Kw::Setboost,
            "-sethp" => Kw::Sethp,
            "-sideend" => Kw::Sideend,
            "-sidestart" => Kw::Sidestart,
            "-singlemove" => Kw::Singlemove,
            "-singleturn" => Kw::Singleturn,
            "-start" => Kw::Start,
            "-status" => Kw::Status,
            "-supereffective" => Kw::Supereffective,
            "-swapboost" => Kw::Swapboost,
            "-swapsideconditions" => Kw::Swapsideconditions,
            "-terastallize" => Kw::Terastallize,
            "-transform" => Kw::Transform,
            "-unboost" => Kw::Unboost,
            "-waiting" => Kw::Waiting,
            "-weather" => Kw::Weather,
            "-zbroken" => Kw::Zbroken,
            "-zpower" => Kw::Zpower,
            ":" => Kw::Colon,
            "J" => Kw::JoinUpper,
            "L" => Kw::LeaveUpper,
            "askreg" => Kw::Askreg,
            "badge" => Kw::Badge,
            "bigerror" => Kw::Bigerror,
            "c" => Kw::C,
            "c:" => Kw::ChatTimestamped,
            "cant" => Kw::Cant,
            "chat" => Kw::Chat,
            "clearpoke" => Kw::Clearpoke,
            "crit" => Kw::BareCrit,
            "debug" => Kw::Debug,
            "deinit" => Kw::Deinit,
            "detailschange" => Kw::Detailschange,
            "drag" => Kw::Drag,
            "error" => Kw::Error,
            "expire" => Kw::Expire,
            "faint" => Kw::Faint,
            "gametype" => Kw::Gametype,
            "gen" => Kw::Gen,
            "hidelines" => Kw::Hidelines,
            "html" => Kw::Html,
            "immune" => Kw::BareImmune,
            "inactive" => Kw::Inactive,
            "inactiveoff" => Kw::Inactiveoff,
            "init" => Kw::Init,
            "j" => Kw::JoinShort,
            "join" => Kw::Join,
            "l" => Kw::LeaveShort,
            "leave" => Kw::Leave,
            "message" => Kw::BareMessage,
            "move" => Kw::Move,
            "n" => Kw::RenameShort,
            "name" => Kw::Name,
            "noinit" => Kw::Noinit,
            "notify" => Kw::Notify,
            "player" => Kw::Player,
            "poke" => Kw::Poke,
            "popup" => Kw::Popup,
            "rated" => Kw::Rated,
            "raw" => Kw::Raw,
            "replace" => Kw::Replace,
            "request" => Kw::Request,
            "resisted" => Kw::BareResisted,
            "rule" => Kw::Rule,
            "sentchoice" => Kw::Sentchoice,
            "showteam" => Kw::Showteam,
            "split" => Kw::Split,
            "start" => Kw::BareStart,
            "supereffective" => Kw::BareSupereffective,
            "swap" => Kw::Swap,
            "switch" => Kw::Switch,
            "t:" => Kw::Timestamp,
            "teampreview" => Kw::Teampreview,
            "teamsize" => Kw::Teamsize,
            "tempnotify" => Kw::Tempnotify,
            "tempnotifyoff" => Kw::Tempnotifyoff,
            "tie" => Kw::Tie,
            "tier" => Kw::Tier,
            "title" => Kw::Title,
            "turn" => Kw::Turn,
            "uhtml" => Kw::Uhtml,
            "uhtmlchange" => Kw::Uhtmlchange,
            "upkeep" => Kw::Upkeep,
            "win" => Kw::Win,
            "zbroken" => Kw::BareZbroken,
            _ => return None,
        })
    }
    /// How a poke-env `Player` + `Gen3Battle` routes a line of this keyword.
    pub fn route(self) -> Route {
        match self {
            Kw::Separator => Route::Control,
            Kw::Ability => Route::Event(EventKind::Ability),
            Kw::Activate => Route::Event(EventKind::Activate),
            Kw::Anim => Route::Cosmetic,
            Kw::Block => Route::Cosmetic,
            Kw::Boost => Route::Event(EventKind::Boost),
            Kw::Burst => Route::Unsupported,
            Kw::Center => Route::Cosmetic,
            Kw::Clearallboost => Route::Event(EventKind::Clearboost),
            Kw::Clearboost => Route::Event(EventKind::Clearboost),
            Kw::Clearnegativeboost => Route::Event(EventKind::Clearboost),
            Kw::Clearpositiveboost => Route::Event(EventKind::Clearboost),
            Kw::Combine => Route::Cosmetic,
            Kw::Copyboost => Route::Event(EventKind::Clearboost),
            Kw::Crit => Route::Event(EventKind::Crit),
            Kw::Curestatus => Route::Event(EventKind::Curestatus),
            Kw::Cureteam => Route::Event(EventKind::Curestatus),
            Kw::Damage => Route::Event(EventKind::Damage),
            Kw::End => Route::Event(EventKind::VolatileEnd),
            Kw::Endability => Route::Event(EventKind::Ability),
            Kw::Enditem => Route::Event(EventKind::Enditem),
            Kw::Fail => Route::Event(EventKind::Fail),
            Kw::Fieldactivate => Route::Cosmetic,
            Kw::Fieldend => Route::Event(EventKind::Field),
            Kw::Fieldstart => Route::Event(EventKind::Field),
            Kw::Formechange => Route::Event(EventKind::Formechange),
            Kw::Heal => Route::Event(EventKind::Heal),
            Kw::Hint => Route::Cosmetic,
            Kw::Hitcount => Route::Cosmetic,
            Kw::Immune => Route::Event(EventKind::Immune),
            Kw::Invertboost => Route::Event(EventKind::Clearboost),
            Kw::Item => Route::Event(EventKind::Item),
            Kw::Mega => Route::Unsupported,
            Kw::Message => Route::Cosmetic,
            Kw::Miss => Route::Event(EventKind::Miss),
            Kw::Mustrecharge => Route::Event(EventKind::Mustrecharge),
            Kw::Notarget => Route::Event(EventKind::Fail),
            Kw::Nothing => Route::Event(EventKind::Fail),
            Kw::Ohko => Route::Cosmetic,
            Kw::Prepare => Route::Event(EventKind::Prepare),
            Kw::Primal => Route::Unsupported,
            Kw::Resisted => Route::Event(EventKind::Resisted),
            Kw::Setboost => Route::Event(EventKind::Setboost),
            Kw::Sethp => Route::Event(EventKind::Sethp),
            Kw::Sideend => Route::Event(EventKind::Side),
            Kw::Sidestart => Route::Event(EventKind::Side),
            Kw::Singlemove => Route::Event(EventKind::VolatileStart),
            Kw::Singleturn => Route::Event(EventKind::VolatileStart),
            Kw::Start => Route::Event(EventKind::VolatileStart),
            Kw::Status => Route::Event(EventKind::Status),
            Kw::Supereffective => Route::Event(EventKind::Supereffective),
            Kw::Swapboost => Route::Event(EventKind::Clearboost),
            Kw::Swapsideconditions => Route::Event(EventKind::Side),
            Kw::Terastallize => Route::Unsupported,
            Kw::Transform => Route::Event(EventKind::Transform),
            Kw::Unboost => Route::Event(EventKind::Unboost),
            Kw::Waiting => Route::Cosmetic,
            Kw::Weather => Route::Event(EventKind::Weather),
            Kw::Zbroken => Route::Unsupported,
            Kw::Zpower => Route::Unsupported,
            Kw::Colon => Route::Cosmetic,
            Kw::JoinUpper => Route::Cosmetic,
            Kw::LeaveUpper => Route::Cosmetic,
            Kw::Askreg => Route::Control,
            Kw::Badge => Route::Cosmetic,
            Kw::Bigerror => Route::Intercept(Intercept::BigError),
            Kw::C => Route::Cosmetic,
            Kw::ChatTimestamped => Route::Cosmetic,
            Kw::Cant => Route::Event(EventKind::Cant),
            Kw::Chat => Route::Cosmetic,
            Kw::Clearpoke => Route::Control,
            Kw::BareCrit => Route::Cosmetic,
            Kw::Debug => Route::Cosmetic,
            Kw::Deinit => Route::Control,
            Kw::Detailschange => Route::Event(EventKind::Formechange),
            Kw::Drag => Route::Event(EventKind::Drag),
            Kw::Error => Route::Intercept(Intercept::Error),
            Kw::Expire => Route::Intercept(Intercept::Ignored),
            Kw::Faint => Route::Event(EventKind::Faint),
            Kw::Gametype => Route::Control,
            Kw::Gen => Route::Control,
            Kw::Hidelines => Route::Cosmetic,
            Kw::Html => Route::Cosmetic,
            Kw::BareImmune => Route::Cosmetic,
            Kw::Inactive => Route::Control,
            Kw::Inactiveoff => Route::Control,
            Kw::Init => Route::Control,
            Kw::JoinShort => Route::Cosmetic,
            Kw::Join => Route::Cosmetic,
            Kw::LeaveShort => Route::Cosmetic,
            Kw::Leave => Route::Cosmetic,
            Kw::BareMessage => Route::Cosmetic,
            Kw::Move => Route::Event(EventKind::Move),
            Kw::RenameShort => Route::Cosmetic,
            Kw::Name => Route::Cosmetic,
            Kw::Noinit => Route::Control,
            Kw::Notify => Route::Cosmetic,
            Kw::Player => Route::Control,
            Kw::Poke => Route::Control,
            Kw::Popup => Route::Cosmetic,
            Kw::Rated => Route::Control,
            Kw::Raw => Route::Control,
            Kw::Replace => Route::Event(EventKind::Formechange),
            Kw::Request => Route::Intercept(Intercept::Request),
            Kw::BareResisted => Route::Cosmetic,
            Kw::Rule => Route::Control,
            Kw::Sentchoice => Route::Control,
            Kw::Showteam => Route::Intercept(Intercept::ShowTeam),
            Kw::Split => Route::Control,
            Kw::BareStart => Route::Control,
            Kw::BareSupereffective => Route::Cosmetic,
            Kw::Swap => Route::Event(EventKind::Swap),
            Kw::Switch => Route::Event(EventKind::Switch),
            Kw::Timestamp => Route::Intercept(Intercept::Ignored),
            Kw::Teampreview => Route::Control,
            Kw::Teamsize => Route::Control,
            Kw::Tempnotify => Route::Cosmetic,
            Kw::Tempnotifyoff => Route::Cosmetic,
            Kw::Tie => Route::Intercept(Intercept::Tie),
            Kw::Tier => Route::Control,
            Kw::Title => Route::Control,
            Kw::Turn => Route::Control,
            Kw::Uhtml => Route::Cosmetic,
            Kw::Uhtmlchange => Route::Intercept(Intercept::Ignored),
            Kw::Upkeep => Route::Control,
            Kw::Win => Route::Intercept(Intercept::Win),
            Kw::BareZbroken => Route::Unsupported,
            Kw::Plain => Route::Plain,
        }
    }
}

/// The number of keyword variants (excluding `Plain`).
pub const N_KEYWORDS: usize = 127;
