"""Render the Rust core's EVENT SCHEMA table from the Python one (``gen3_core_event_schema_codegen_v1``).

The Rust core (``src/rust_sim/src/core_events/``) must classify every protocol keyword exactly as
``agents.battle.battle_event.MESSAGE_POLICY`` does, map EVENT keywords to the same ``EventKind``
integers, route the player-intercepted keywords exactly as ``Player._handle_battle_message`` does,
and emit exactly the declared ``value`` vocabulary (``gen3_event_value_schema_v1``). Two hand-kept
copies of a 120-keyword table is how two paths drift, so the Rust copy is GENERATED from this
module's inputs and committed, and ``rust_core_schema_test.py`` (routine, ~free) fails the day the
Python side changes without a regeneration — the ``arch_tables`` pattern.

    python -m agents.battle.rust_core_schema --write     # regenerate the committed Rust file
    python -m agents.battle.rust_core_schema --check     # exit 1 if it is stale
"""

from __future__ import annotations

import argparse
import sys
from typing import Dict, List, Tuple

from poke_env.player.player import Player

from agents.battle.battle_event import (EVENT_KIND, EVENT_OPTIONAL_KEYS, EVENT_VALUE_KEYS,
                                        MESSAGE_POLICY, EventKind, Policy)
from utils.paths import repo_path

OUT = repo_path("src", "rust_sim", "src", "core_events", "schema.rs")

#: Keywords ``Player._handle_battle_message`` handles ITSELF, before ``parse_message``: each maps to
#: the Rust ``Intercept`` it is routed to. The player's ``MESSAGES_TO_IGNORE`` set is read from the
#: class (below), so an added ignore is picked up by a regeneration.
_INTERCEPTED = {
    "request": "Request",
    "showteam": "ShowTeam",
    "win": "Win",
    "tie": "Tie",
    "error": "Error",
    "bigerror": "BigError",
}

#: Variant names a mechanical CamelCase would collide or cannot spell.
_SPECIAL_NAMES = {
    "": "Separator", ":": "Colon", "t:": "Timestamp", "c:": "ChatTimestamped",
    "J": "JoinUpper", "L": "LeaveUpper", "j": "JoinShort", "l": "LeaveShort", "n": "RenameShort",
}


def _camel(keyword: str) -> str:
    if keyword in _SPECIAL_NAMES:
        return _SPECIAL_NAMES[keyword]
    parts = [p for p in keyword.lstrip("-").replace(":", " ").replace("-", " ").split() if p]
    return "".join(p[:1].upper() + p[1:] for p in parts)


def keyword_rows() -> List[Tuple[str, str, str]]:
    """``(keyword, VariantName, route)`` for every keyword, sorted by keyword. ``route`` is Rust."""
    kws = set(MESSAGE_POLICY) | set(_INTERCEPTED) | set(Player.MESSAGES_TO_IGNORE)
    names: Dict[str, str] = {}
    for kw in sorted(kws):
        base = _camel(kw)
        names[kw] = base
    # A dashed keyword keeps the plain name; its bare legacy twin gets `Bare`.
    by_name: Dict[str, List[str]] = {}
    for kw, n in names.items():
        by_name.setdefault(n, []).append(kw)
    for n, group in by_name.items():
        if len(group) > 1:
            for kw in group:
                if not kw.startswith("-"):
                    names[kw] = "Bare" + n
    assert len(set(names.values())) == len(names), "variant-name collision"
    rows = []
    for kw in sorted(kws):
        if kw in Player.MESSAGES_TO_IGNORE:
            route = "Route::Intercept(Intercept::Ignored)"
        elif kw in _INTERCEPTED:
            route = f"Route::Intercept(Intercept::{_INTERCEPTED[kw]})"
        else:
            policy, _ = MESSAGE_POLICY[kw]
            if policy is Policy.EVENT:
                route = f"Route::Event(EventKind::{EVENT_KIND[kw].name.title().replace('_', '')})"
            elif policy is Policy.CONTROL:
                route = "Route::Control"
            elif policy is Policy.COSMETIC:
                route = "Route::Cosmetic"
            elif policy is Policy.STATE_ONLY:
                route = "Route::StateOnly"
            else:
                route = "Route::Unsupported"
        rows.append((kw, names[kw], route))
    return rows


def _rs_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render() -> str:
    rows = keyword_rows()
    kinds = sorted(EventKind, key=lambda k: k.value)
    out: List[str] = []
    w = out.append
    w("// @generated by `python -m agents.battle.rust_core_schema --write` — DO NOT EDIT.")
    w("// Source of truth: `agents/battle/battle_event.py` (MESSAGE_POLICY, EVENT_KIND, EventKind,")
    w("// EVENT_VALUE_KEYS, EVENT_OPTIONAL_KEYS) + `Player.MESSAGES_TO_IGNORE`. Pinned by")
    w("// `src/agents/battle/rust_core_schema_test.py`.")
    w("")
    w("use super::{Intercept, Route};")
    w("")
    w("/// `agents.battle.battle_event.EventKind`, with its stable integer values.")
    w("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]")
    w("pub enum EventKind {")
    for k in kinds:
        w(f"    {k.name.title().replace('_', '')} = {k.value},")
    w("}")
    w("")
    w("impl EventKind {")
    w("    /// The Python enum member NAME (`MOVE`, `CHOICE_REJECTED`, …).")
    w("    pub fn name(self) -> &'static str {")
    w("        match self {")
    for k in kinds:
        w(f"            EventKind::{k.name.title().replace('_', '')} => {_rs_str(k.name)},")
    w("        }")
    w("    }")
    w("    /// `EVENT_VALUE_KEYS[kind]` — the keys a consumer may rely on.")
    w("    pub fn required_keys(self) -> &'static [&'static str] {")
    w("        match self {")
    for k in kinds:
        keys = ", ".join(_rs_str(x) for x in sorted(EVENT_VALUE_KEYS.get(k, frozenset())))
        w(f"            EventKind::{k.name.title().replace('_', '')} => &[{keys}],")
    w("        }")
    w("    }")
    w("    /// `EVENT_OPTIONAL_KEYS[kind]` — the rest of the declared vocabulary.")
    w("    pub fn optional_keys(self) -> &'static [&'static str] {")
    w("        match self {")
    for k in kinds:
        keys = ", ".join(_rs_str(x) for x in sorted(EVENT_OPTIONAL_KEYS.get(k, frozenset())))
        w(f"            EventKind::{k.name.title().replace('_', '')} => &[{keys}],")
    w("        }")
    w("    }")
    w("}")
    w("")
    w("/// Every protocol keyword the core knows, one variant each (`Plain` = a line with no `|`).")
    w("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]")
    w("pub enum Kw {")
    for kw, name, _ in rows:
        w(f"    /// `|{kw}|`")
        w(f"    {name},")
    w("    /// A line that does not start with `|` (poke-env ignores it: a one-element split).")
    w("    Plain,")
    w("}")
    w("")
    w("impl Kw {")
    w("    /// The protocol keyword text.")
    w("    pub fn as_str(self) -> &'static str {")
    w("        match self {")
    for kw, name, _ in rows:
        w(f"            Kw::{name} => {_rs_str(kw)},")
    w('            Kw::Plain => "",')
    w("        }")
    w("    }")
    w("    /// The keyword for protocol text, or `None` for a keyword the schema does not know.")
    w("    pub fn from_protocol(s: &str) -> Option<Kw> {")
    w("        Some(match s {")
    for kw, name, _ in rows:
        w(f"            {_rs_str(kw)} => Kw::{name},")
    w("            _ => return None,")
    w("        })")
    w("    }")
    w("    /// How a poke-env `Player` + `Gen3Battle` routes a line of this keyword.")
    w("    pub fn route(self) -> Route {")
    w("        match self {")
    for kw, name, route in rows:
        w(f"            Kw::{name} => {route},")
    w("            Kw::Plain => Route::Plain,")
    w("        }")
    w("    }")
    w("}")
    w("")
    w("/// The number of keyword variants (excluding `Plain`).")
    w(f"pub const N_KEYWORDS: usize = {len(rows)};")
    return "\n".join(out) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    text = render()
    if a.write:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(text)
        print(f"wrote {OUT}")
        return 0
    current = OUT.read_text() if OUT.exists() else ""
    if current != text:
        print(f"STALE: {OUT} — run `python -m agents.battle.rust_core_schema --write`")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
