"""Render the Rust core's POKE-ENV TABLES from poke-env itself (``gen3_core_present_tables_v1``).

``present()`` (``src/rust_sim/src/present/``, the Rust Core Program's M2) reproduces poke-env's
READING of a battle, and that reading consults poke-env's OWN static data, not the simulator's:
the gen-3 pokedex ``Pokemon._update_from_pokedex`` reads (types, base stats, possible abilities,
base species), the move table ``Move`` reads (PP, target, the ``mustpressure`` flag, base power,
type), the ``Effect`` enum's lifecycle sets (``ends_on_turn``, ``is_turn_countable``,
``is_action_countable``, ``breaks_protect``, ``BATON_PASS_COPIED_EFFECTS``), the ``SideCondition``
enum and ``STACKABLE_CONDITIONS``, and the ``PokemonType`` member names. A second hand-kept copy is
how two readers drift, so the Rust copy is GENERATED from those objects and committed, and
``rust_core_present_tables_test.py`` (routine, ~free) fails the day poke-env's data changes without
a regeneration — the ``rust_core_schema`` pattern.

This is the ORACLE's data, deliberately: ``data/`` is the simulator's source of truth, and where
poke-env's table and the simulator's disagree the READING follows poke-env (that is what "the
reading" means). ``view_adapter._possible_abilities`` made the same choice for the same reason.

    python -m agents.battle.rust_core_present_tables --write
    python -m agents.battle.rust_core_present_tables --check
"""

from __future__ import annotations

import argparse
import sys
from typing import List

from utils.paths import repo_path

OUT = repo_path("src", "rust_sim", "src", "present", "tables.rs")
GEN = 3


def _rs(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _to_id(s: str) -> str:
    from poke_env.data.normalize import to_id_str

    return to_id_str(s)


def render() -> str:
    from poke_env.battle.effect import (_ACTION_COUNTER_EFFECTS, _ENDS_ON_TURN_EFFECTS,
                                        _PROTECT_BREAKING_EFFECTS, _TURN_COUNTER_EFFECTS,
                                        BATON_PASS_COPIED_EFFECTS, Effect)
    from poke_env.battle.move import _PROTECT_COUNTER_MOVES, SPECIAL_MOVES, Move
    from poke_env.battle.pokemon_type import PokemonType
    from poke_env.battle.side_condition import STACKABLE_CONDITIONS, SideCondition
    from poke_env.data.gen_data import GenData

    g = GenData.from_gen(GEN)
    out: List[str] = []
    w = out.append
    w("// @generated by `python -m agents.battle.rust_core_present_tables --write` — DO NOT EDIT.")
    w("// Source of truth: poke-env's OWN gen-3 data and enums (`GenData.from_gen(3)`, `Effect`,")
    w("// `SideCondition`, `PokemonType`, `Move`). Pinned by")
    w("// `src/agents/battle/rust_core_present_tables_test.py`.")
    w("")
    w("/// One `GenData.from_gen(3).pokedex` row, as `Pokemon._update_from_pokedex` reads it.")
    w("pub struct SpeciesRow {")
    w("    pub id: &'static str,")
    w("    /// `to_id_str(dex_entry[\"baseSpecies\"])` — `Pokemon.base_species`.")
    w("    pub base_species: &'static str,")
    w("    /// The dex `types`, as poke-env's `PokemonType` member NAMES (`FIRE`), or the raw dex")
    w("    /// string when poke-env has no member for it (`from_name` would raise).")
    w("    pub types: &'static [&'static str],")
    w("    /// `baseStats` in the dict's own key order: hp, atk, def, spa, spd, spe.")
    w("    pub base_stats: [u16; 6],")
    w("    /// `to_id_str(a) for a in dex_entry[\"abilities\"].values()`, in dict order.")
    w("    pub abilities: &'static [&'static str],")
    w("    /// The `forme` test that makes `_update_from_pokedex` set `forme_change_ability`")
    w("    /// (Mega / Primal / Stellar / Terastal / `-Tera`): the dex's ability slot `0`, id'd.")
    w("    pub forme_change_ability: Option<&'static str>,")
    w("}")
    w("")
    w("/// `GenData.from_gen(3).pokedex`, sorted by id.")
    w("pub static SPECIES: &[SpeciesRow] = &[")
    for sid in sorted(g.pokedex):
        e = g.pokedex[sid]
        types = []
        for t in e["types"]:
            name = "THREE_QUESTION_MARKS" if t == "???" else t.upper()
            types.append(name if name in PokemonType.__members__ else t)
        bs = e["baseStats"]
        stats = ", ".join(str(int(bs[k])) for k in ("hp", "atk", "def", "spa", "spd", "spe"))
        forme = e.get("forme")
        fca = None
        if forme is not None and (forme.startswith("Mega") or forme in ("Primal", "Stellar", "Terastal")
                                  or forme.endswith("-Tera")):
            fca = _to_id(e["abilities"]["0"])
        abil = ", ".join(_rs(_to_id(a)) for a in e["abilities"].values())
        w(f"    SpeciesRow {{ id: {_rs(sid)}, base_species: {_rs(_to_id(e['baseSpecies']))}, "
          f"types: &[{', '.join(_rs(t) for t in types)}], base_stats: [{stats}], "
          f"abilities: &[{abil}], forme_change_ability: {('Some(' + _rs(fca) + ')') if fca else 'None'} }},")
    w("];")
    w("")
    w("/// One `GenData.from_gen(3).moves` row, as `Move` reads it.")
    w("pub struct MoveRow {")
    w("    pub id: &'static str,")
    w("    pub pp: u16,")
    w("    pub target: &'static str,")
    w("    /// `\"mustpressure\" in flags` — the second half of `_pressure_on`.")
    w("    pub must_pressure: bool,")
    w("    pub base_power: u16,")
    w("    /// `Move.type` as a `PokemonType` NAME.")
    w("    pub typ: &'static str,")
    w("    /// `Move.should_be_stored(id, 3)`.")
    w("    pub storable: bool,")
    w("    /// `id in _PROTECT_COUNTER_MOVES` — `Move.is_protect_counter`.")
    w("    pub protect_counter: bool,")
    w("    /// `category in (\"Physical\", \"Special\")` — the `|move|` handler's pending")
    w("    /// damaging-move capture, which looks the target up (a creation side effect).")
    w("    pub damaging: bool,")
    w("}")
    w("")
    w("/// `GenData.from_gen(3).moves`, sorted by id.")
    w("pub static MOVES: &[MoveRow] = &[")
    for mid in sorted(g.moves):
        e = g.moves[mid]
        typ = e.get("type", "???")
        typ = "THREE_QUESTION_MARKS" if typ == "???" else typ.upper()
        w(f"    MoveRow {{ id: {_rs(mid)}, pp: {int(e.get('pp', 0))}, target: {_rs(e.get('target', ''))}, "
          f"must_pressure: {'true' if 'mustpressure' in e.get('flags', {}) else 'false'}, "
          f"base_power: {int(e.get('basePower', 0))}, typ: {_rs(typ)}, "
          f"storable: {'true' if Move.should_be_stored(mid, GEN) else 'false'}, "
          f"protect_counter: {'true' if mid in _PROTECT_COUNTER_MOVES else 'false'}, "
          f"damaging: {'true' if e.get('category') in ('Physical', 'Special') else 'false'} }},")
    w("];")
    w("")
    w("/// `move.SPECIAL_MOVES` — never stored, never PP-tracked.")
    w(f"pub static SPECIAL_MOVES: &[&str] = &[{', '.join(_rs(m) for m in sorted(SPECIAL_MOVES))}];")
    w("")
    w("/// One `Effect` member and the lifecycle sets it belongs to.")
    w("pub struct EffectRow {")
    w("    /// The enum member NAME (`LEECH_SEED`); `LiveView` keys it `leechseed`.")
    w("    pub name: &'static str,")
    w("    pub ends_on_turn: bool,")
    w("    pub turn_countable: bool,")
    w("    pub action_countable: bool,")
    w("    pub breaks_protect: bool,")
    w("    /// In `BATON_PASS_COPIED_EFFECTS`.")
    w("    pub bp_copied: bool,")
    w("}")
    w("")
    w("/// Every `Effect` member, sorted by NAME.")
    w("pub static EFFECTS: &[EffectRow] = &[")
    for e in sorted(Effect, key=lambda x: x.name):
        w(f"    EffectRow {{ name: {_rs(e.name)}, "
          f"ends_on_turn: {'true' if e in _ENDS_ON_TURN_EFFECTS else 'false'}, "
          f"turn_countable: {'true' if e in _TURN_COUNTER_EFFECTS else 'false'}, "
          f"action_countable: {'true' if e in _ACTION_COUNTER_EFFECTS else 'false'}, "
          f"breaks_protect: {'true' if e in _PROTECT_BREAKING_EFFECTS else 'false'}, "
          f"bp_copied: {'true' if e in BATON_PASS_COPIED_EFFECTS else 'false'} }},")
    w("];")
    w("")
    w("/// Every `SideCondition` member NAME, sorted, with its `STACKABLE_CONDITIONS` cap (0 = not")
    w("/// stackable).")
    w("pub static SIDE_CONDITIONS: &[(&str, u8)] = &[")
    for c in sorted(SideCondition, key=lambda x: x.name):
        w(f"    ({_rs(c.name)}, {int(STACKABLE_CONDITIONS.get(c, 0))}),")
    w("];")
    w("")
    w("/// Every `PokemonType` member NAME, sorted.")
    w(f"pub static TYPE_NAMES: &[&str] = &[{', '.join(_rs(t.name) for t in sorted(PokemonType, key=lambda x: x.name))}];")
    w("")
    from poke_env.battle.abstract_battle import AbstractBattle

    w("/// `AbstractBattle.MESSAGES_TO_IGNORE` — the keywords `parse_message` returns on at once.")
    w(f"pub static BATTLE_IGNORED: &[&str] = &[{', '.join(_rs(k) for k in sorted(AbstractBattle.MESSAGES_TO_IGNORE))}];")
    w("")
    from poke_env.battle.field import Field

    w("/// Every `Field` member NAME, sorted.")
    w(f"pub static FIELD_NAMES: &[&str] = &[{', '.join(_rs(f.name) for f in sorted(Field, key=lambda x: x.name))}];")
    w("")
    w("/// `GenData.UNKNOWN_ITEM` — the sentinel `Pokemon._item` starts at.")
    w(f"pub const UNKNOWN_ITEM: &str = {_rs(g.UNKNOWN_ITEM)};")
    return "\n".join(out) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    grp = ap.add_mutually_exclusive_group(required=True)
    grp.add_argument("--write", action="store_true")
    grp.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    text = render()
    if a.write:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(text)
        print(f"wrote {OUT}")
        return 0
    current = OUT.read_text() if OUT.exists() else ""
    if current != text:
        print(f"STALE: {OUT} — run `python -m agents.battle.rust_core_present_tables --write`")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
