"""The GENERATED inventory of every poke-env importer outside the vendored fork (P0 of the retirement).

**Why this exists.** The owner's 2026-10-06 direction is to retire poke-env to ONE stack ("not maintain
the dual stack" — every fact the Rust reader already reads is a second copy in the Python battle layer,
which is the change amplification). Retirement is phased (``designs/research_state/measurements/
pokeenv_and_hotpath_survey_2026-10-06/README.md`` §A4.5; backlog ``T27``) and its first phase is a
RATCHET: the set of files that import ``poke_env`` may only shrink, so a phase's progress is a number
that falls and a new importer is a visible, owner-visible event. This module is the scanner behind it;
``src/poke_env_import_gate_test.py`` is the gate; ``designs/ops/poke_env_import_allowlist.txt`` is the
committed allowlist (the generated list as of the freeze).

**What counts as an importer** (an AST scan, one parse per file that mentions ``poke_env`` at all):

* ``import poke_env[.x] [as y]`` and ``from poke_env[.x] import …`` — at module level, inside a function or
  method (LAZY), or under ``if TYPE_CHECKING:`` (TYPE-CHECKING). All three count: a lazy import still loads
  the package the day the function runs, and a type-only import still names a poke-env class in our code.
* A literal poke-env module STRING handed to an import-effecting call —
  ``importlib.import_module("poke_env.x")``, ``__import__``, ``mock.patch("poke_env.x.y")``,
  ``monkeypatch.setattr("poke_env.x.y", …)`` (and ``delattr`` / ``resolve_name`` / ``find_spec``): each imports
  the package at call time, so a test whose ONLY contact is a string patch target is still an importer.

**Scope.** Every ``.py`` under ``src/``, ``tools/`` and ``scripts/`` EXCEPT the vendored fork
(``src/poke_env/`` — it is the thing being retired, not a user of it) and build / cache directories
(``target``, ``node_modules``, ``__pycache__``, ``dist``, ``.git``). A test file is ``*_test.py`` or a
``conftest.py``; everything else (benchmarks, generators, entry points) is non-test.

**Blind spots, stated.** (1) A module name BUILT at run time (``import_module(name)`` with a non-literal) is
invisible. (2) ``designs/`` holds frozen measurement scripts that import poke-env; they are history, not
production, and are out of scope. (3) A shell snippet that runs ``python -c "import poke_env"``
(``scripts/bootstrap.sh``'s import-precedence smoke) is not Python source. (4) ``from . import x`` inside the
fork is not scanned at all.

**The one PERMANENT entry.** :data:`PEER_PROCESS_PERMANENT` — a script that runs in an EXTERNAL
interpreter (Metamon's, where ``import poke_env`` is UPSTREAM poke-env 0.8.3.3, never our fork) and is never
imported by this repo's code. It is allowed forever, is not in the allowlist file and is not counted by the
shrink rule; the end state of the retirement is an empty allowlist plus this.

CLI (``export PYTHONPATH=$PWD/src``)::

    python -m utils.poke_env_importers              # the live inventory: counts + a per-file table
    python -m utils.poke_env_importers --json       # the same, machine-readable
    python -m utils.poke_env_importers --init       # FIRST generation of the allowlist (refuses if it exists)
    python -m utils.poke_env_importers --shrink     # drop entries that no longer import poke_env, lower the
                                                    #   gate's two FROZEN counts to match; REFUSES growth
"""
from __future__ import annotations

import argparse
import ast
import json
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Set, Tuple

from utils.paths import repo_root

PACKAGE = "poke_env"
#: Repo-relative roots the scan walks.
SCAN_ROOTS: Tuple[str, ...] = ("src", "tools", "scripts")
#: The vendored fork — repo-relative POSIX path, pruned whole.
VENDORED_FORK = "src/poke_env"
#: Directory NAMES never descended into.
PRUNE_DIRS = frozenset({"target", "node_modules", "__pycache__", ".git", "dist", ".mypy_cache", ".pytest_cache"})
#: The committed allowlist (one repo-relative path per line, ``#`` comments), generated by ``--init`` and only
#: ever rewritten by ``--shrink``.
ALLOWLIST_REL = "designs/ops/poke_env_import_allowlist.txt"
#: The gate file whose two FROZEN counts ``--shrink`` lowers.
GATE_REL = "src/poke_env_import_gate_test.py"
#: Runs in an EXTERNAL interpreter against UPSTREAM poke-env; never imported here. Allowed forever, uncounted.
PEER_PROCESS_PERMANENT: Tuple[str, ...] = ("src/main/anchors/peer_scripts/metamon_side.py",)

#: Calls whose literal first argument names a module / attribute path that gets imported when they run.
_IMPORT_EFFECT_CALLS = frozenset({"import_module", "__import__", "patch", "setattr", "delattr", "resolve_name",
                                  "find_spec"})
#: Scope strength, strongest first (a file's scope is its strongest hit's).
_SCOPE_ORDER = ("top", "lazy", "type_checking")


class ScanError(RuntimeError):
    """A file the scan could not read or parse — a file the gate cannot see is a hole, so it is loud."""


@dataclass(frozen=True)
class Hit:
    line: int
    module: str          #: the poke-env module / dotted target named (``poke_env.battle.pokemon``)
    scope: str           #: ``top`` | ``lazy`` | ``type_checking``
    form: str            #: ``import`` | ``from`` | ``dynamic``


@dataclass(frozen=True)
class Importer:
    path: str                    #: repo-relative POSIX path
    is_test: bool
    scope: str                   #: the strongest scope among its hits
    modules: Tuple[str, ...]     #: the distinct poke-env modules it names, sorted
    hits: Tuple[Hit, ...]

    def as_json(self) -> dict:
        return {"path": self.path, "kind": "test" if self.is_test else "non_test", "scope": self.scope,
                "modules": list(self.modules), "lines": sorted({h.line for h in self.hits})}


@dataclass
class Inventory:
    importers: Dict[str, Importer] = field(default_factory=dict)
    files_scanned: int = 0

    def paths(self, *, include_permanent: bool = True) -> Set[str]:
        return {p for p in self.importers if include_permanent or p not in PEER_PROCESS_PERMANENT}

    def allowlistable(self) -> Dict[str, Importer]:
        """The importers the allowlist must cover — everything but the permanent peer-process entries."""
        return {p: i for p, i in self.importers.items() if p not in PEER_PROCESS_PERMANENT}


def is_test_path(path: str) -> bool:
    name = path.rsplit("/", 1)[-1]
    return name.endswith("_test.py") or name == "conftest.py"


def _is_poke_env_name(name: str) -> bool:
    return name == PACKAGE or name.startswith(PACKAGE + ".")


def _call_name(fn: ast.expr) -> str:
    if isinstance(fn, ast.Name):
        return fn.id
    if isinstance(fn, ast.Attribute):
        return fn.attr
    return ""


def _literal_head(e: ast.expr) -> Optional[str]:
    """The literal text a string expression STARTS with (a plain constant, or an f-string's first constant)."""
    if isinstance(e, ast.Constant) and isinstance(e.value, str):
        return e.value
    if isinstance(e, ast.JoinedStr) and e.values and isinstance(e.values[0], ast.Constant) \
            and isinstance(e.values[0].value, str):
        return e.values[0].value
    return None


def _is_type_checking(test: ast.expr) -> bool:
    return (isinstance(test, ast.Name) and test.id == "TYPE_CHECKING") or (
        isinstance(test, ast.Attribute) and test.attr == "TYPE_CHECKING")


class _Collector(ast.NodeVisitor):
    def __init__(self) -> None:
        self.hits: List[Hit] = []
        self._fn = 0
        self._tc = 0

    def _scope(self) -> str:
        return "type_checking" if self._tc else ("lazy" if self._fn else "top")

    def _enter_fn(self, node: ast.AST) -> None:
        self._fn += 1
        self.generic_visit(node)
        self._fn -= 1

    def visit_FunctionDef(self, node: ast.FunctionDef) -> None:
        self._enter_fn(node)

    def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> None:
        self._enter_fn(node)

    def visit_Lambda(self, node: ast.Lambda) -> None:
        self._enter_fn(node)

    def visit_If(self, node: ast.If) -> None:
        if _is_type_checking(node.test):
            self._tc += 1
            for child in node.body:
                self.visit(child)
            self._tc -= 1
            for child in node.orelse:          # the else arm of `if TYPE_CHECKING` is RUNTIME code
                self.visit(child)
        else:
            self.generic_visit(node)

    def visit_Import(self, node: ast.Import) -> None:
        for alias in node.names:
            if _is_poke_env_name(alias.name):
                self.hits.append(Hit(node.lineno, alias.name, self._scope(), "import"))

    def visit_ImportFrom(self, node: ast.ImportFrom) -> None:
        if node.level == 0 and node.module and _is_poke_env_name(node.module):
            self.hits.append(Hit(node.lineno, node.module, self._scope(), "from"))

    def visit_Call(self, node: ast.Call) -> None:
        if _call_name(node.func) in _IMPORT_EFFECT_CALLS and node.args:
            head = _literal_head(node.args[0])
            if head is not None and _is_poke_env_name(head):
                self.hits.append(Hit(node.lineno, head, self._scope(), "dynamic"))
        self.generic_visit(node)


def scan_source(src: str, filename: str = "<src>") -> List[Hit]:
    """Every poke-env import (statement or literal import-effect call) in ``src``, line-ordered."""
    if PACKAGE not in src:                       # the cheap prefilter: an import statement spells the name
        return []
    try:
        tree = ast.parse(src, filename)
    except SyntaxError as e:
        raise ScanError(f"{filename}: cannot parse ({e}) — the import gate cannot see this file") from e
    c = _Collector()
    c.visit(tree)
    return sorted(c.hits, key=lambda h: (h.line, h.module))


def _make_importer(path: str, hits: Sequence[Hit]) -> Importer:
    scope = next(s for s in _SCOPE_ORDER if any(h.scope == s for h in hits))
    return Importer(path=path, is_test=is_test_path(path), scope=scope,
                    modules=tuple(sorted({h.module for h in hits})), hits=tuple(hits))


def iter_py_files(root: Optional[Path] = None) -> Iterable[Tuple[str, Path]]:
    """``(repo-relative POSIX path, absolute path)`` for every scanned ``.py`` file, sorted."""
    root = root or repo_root()
    out: List[Tuple[str, Path]] = []
    for top in SCAN_ROOTS:
        base = root / top
        if not base.is_dir():
            continue
        for dirpath, dirnames, filenames in os.walk(base):
            rel_dir = Path(dirpath).relative_to(root).as_posix()
            dirnames[:] = sorted(d for d in dirnames
                                 if d not in PRUNE_DIRS and f"{rel_dir}/{d}" != VENDORED_FORK)
            for fn in filenames:
                if fn.endswith(".py"):
                    out.append((f"{rel_dir}/{fn}", Path(dirpath) / fn))
    return sorted(out)


def scan_repo(root: Optional[Path] = None) -> Inventory:
    """The live inventory of the checkout at ``root`` (default: THIS checkout)."""
    inv = Inventory()
    for rel, p in iter_py_files(root):
        inv.files_scanned += 1
        try:
            text = p.read_text()
        except (OSError, UnicodeDecodeError) as e:
            raise ScanError(f"{rel}: cannot read ({e}) — the import gate cannot see this file") from e
        hits = scan_source(text, rel)
        if hits:
            inv.importers[rel] = _make_importer(rel, hits)
    return inv


# --------------------------------------------------------------------------------------- the allowlist file

_HEADER = """\
# poke-env IMPORT ALLOWLIST — the GENERATED list of every file outside the vendored fork (src/poke_env/) that
# imports poke_env, frozen at {when}. T27 / P0 of the poke-env retirement
# (designs/research_state/measurements/pokeenv_and_hotpath_survey_2026-10-06/README.md §A4.5).
#
# THIS LIST MAY ONLY SHRINK.
#   * src/poke_env_import_gate_test.py fails on an importer that is NOT listed, and on a listed file that no
#     longer imports poke_env (so a retired importer leaves this list in the commit that retires it).
#   * The gate's FROZEN_NON_TEST_COUNT / FROZEN_TEST_COUNT are the ceiling; raising one is NOT a legal move
#     without the owner. A new file the Rust/Python parity work genuinely forces is named in the commit body
#     and the owner decides.
#   * Shrink with:  python -m utils.poke_env_importers --shrink      (removes the stale entries, lowers the counts)
#   * Regenerating this file from scratch is --init, which refuses while the file exists.
# One repo-relative path per line, sorted; non-test files first, then test files.
"""


def read_allowlist(root: Optional[Path] = None) -> List[str]:
    p = (root or repo_root()) / ALLOWLIST_REL
    if not p.is_file():
        return []
    return [ln.strip() for ln in p.read_text().splitlines() if ln.strip() and not ln.lstrip().startswith("#")]


def render_allowlist(paths: Iterable[str], when: str) -> str:
    ps = sorted(set(paths), key=lambda x: (is_test_path(x), x))
    return _HEADER.format(when=when) + "\n".join(ps) + "\n"


def _frozen_counts_line(non_test: int, test: int) -> str:
    return f"FROZEN_NON_TEST_COUNT = {non_test}\nFROZEN_TEST_COUNT = {test}"


def _rewrite_frozen_counts(gate_src: str, non_test: int, test: int) -> str:
    out, n1 = re.subn(r"(?m)^FROZEN_NON_TEST_COUNT = \d+$", f"FROZEN_NON_TEST_COUNT = {non_test}", gate_src)
    out, n2 = re.subn(r"(?m)^FROZEN_TEST_COUNT = \d+$", f"FROZEN_TEST_COUNT = {test}", out)
    if (n1, n2) != (1, 1):
        raise ScanError(f"{GATE_REL}: expected exactly one FROZEN_NON_TEST_COUNT and one FROZEN_TEST_COUNT line, "
                        f"found {n1} and {n2} — edit them by hand")
    return out


def counts(paths: Iterable[str]) -> Tuple[int, int]:
    ps = list(paths)
    t = sum(1 for p in ps if is_test_path(p))
    return len(ps) - t, t


# --------------------------------------------------------------------------------------------------- the CLI

def _summary(inv: Inventory) -> str:
    imps = inv.importers.values()
    lines = [f"files scanned: {inv.files_scanned}   importers: {len(inv.importers)} "
             f"(non-test {sum(not i.is_test for i in imps)}, test {sum(i.is_test for i in imps)}; "
             f"permanent peer-process: {len(inv.paths()) - len(inv.paths(include_permanent=False))})"]
    for kind, is_test in (("non-test", False), ("test", True)):
        by_scope = {s: sum(1 for i in imps if i.is_test == is_test and i.scope == s) for s in _SCOPE_ORDER}
        lines.append(f"  {kind:9s} " + "  ".join(f"{s}={n}" for s, n in by_scope.items()))
    return "\n".join(lines)


def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="The generated poke-env importer inventory (T27 / P0).")
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--json", action="store_true", help="print the live inventory as JSON")
    g.add_argument("--init", action="store_true", help="write the allowlist for the first time (refuses if present)")
    g.add_argument("--shrink", action="store_true",
                   help="drop allowlist entries that no longer import poke_env and lower the gate's FROZEN "
                        "counts; refuses if a live importer is not listed (growth)")
    ap.add_argument("--when", default=None, help="date stamped into a --init header (default: today)")
    a = ap.parse_args(argv)
    root = repo_root()
    inv = scan_repo(root)

    if a.json:
        print(json.dumps({"files_scanned": inv.files_scanned,
                          "importers": [i.as_json() for _, i in sorted(inv.importers.items())]}, indent=1))
        return 0

    live = set(inv.allowlistable())
    allow_path = root / ALLOWLIST_REL

    if a.init:
        if allow_path.exists():
            print(f"refusing: {ALLOWLIST_REL} already exists — the list only shrinks (use --shrink)", file=sys.stderr)
            return 2
        import datetime
        when = a.when or datetime.date.today().isoformat()
        allow_path.write_text(render_allowlist(live, when))
        nt, t = counts(live)
        print(f"wrote {ALLOWLIST_REL}: {len(live)} entries\n{_frozen_counts_line(nt, t)}")
        return 0

    if a.shrink:
        listed = set(read_allowlist(root))
        grown = sorted(live - listed)
        if grown:
            print("refusing: live importer(s) NOT on the allowlist — the list only shrinks, it is never "
                  "extended by this tool:\n  " + "\n  ".join(grown), file=sys.stderr)
            return 2
        keep = listed & live
        gone = sorted(listed - live)
        text = allow_path.read_text()
        head = "".join(ln for ln in text.splitlines(keepends=True) if ln.lstrip().startswith("#"))
        nt, t = counts(keep)
        gate = root / GATE_REL
        new_gate = _rewrite_frozen_counts(gate.read_text(), nt, t)      # may raise: BEFORE anything is written
        allow_path.write_text(head + "\n".join(sorted(keep, key=lambda x: (is_test_path(x), x))) + "\n")
        gate.write_text(new_gate)
        print(f"removed {len(gone)} stale entr{'y' if len(gone) == 1 else 'ies'}; {len(keep)} remain "
              f"(non-test {nt}, test {t}); {GATE_REL} counts updated")
        for p in gone:
            print(f"  - {p}")
        return 0

    print(_summary(inv))
    for p, i in sorted(inv.importers.items()):
        print(f"{'T' if i.is_test else 'N'} {i.scope:13s} {p}  [{', '.join(i.modules)}]")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
