"""Static-token screen LOOK 1: the registered read (design_static_tokens.md §8.1 + §8.2), at P_st 6c6d2e09.

Reads the look-1 request ``st_look1_steps`` of family ``st_screen_strength_steps`` from the eval COUNT ledger through
``main.h2h.cross``'s declared family read, builds the 3 × 3 matrix (rows = static seeds 1001-1003, columns = legacy
seeds 1001-1003, keyed by each final's sha256), and writes ``result.json`` + ``result.md`` beside this file.

    PYTHONPATH=<6c6d2e09 checkout>/src python read_look1.py [--root <ledger root>] [--progress]

THE PIN: the estimator and the ledger reader are imported from the checkout on PYTHONPATH; this script REFUSES (exit
5) unless that checkout's ``git rev-parse HEAD`` is 6c6d2e09 (§8.2: every cross and read at P_st, never at HEAD).

THE STATISTIC (§8.1, X5 §7.4's): ``main.h2h.cross.cross_stat`` — Δ̂ = mean(h) − 50, V̂ = (s²_R + s²_C)/3, df = 4;
t_NI = (Δ̂ + 3.5)/√V̂ (cross_stat's ``t``) and t_SUP = Δ̂/√V̂.

THE OUTCOME TABLE AT LOOK 1 (§8.1's table with §8.2's look-1 boundary b = 5.761 in place of 2.132; rule 8 on every
comparison; INCONCLUSIVE on any invalid input), DECLARED HERE BEFORE THE READ:
  BETTER        t_SUP ≥ b
  EQUIVALENT    the look's interval Δ̂ ± b·√V̂ lies inside (−δ, +δ)
  NON-INFERIOR  t_NI ≥ b, neither of the above
  INFERIOR      Δ̂ + b·√V̂ < −δ
  FUTILITY STOP (X5's futility rule, which §8.2 adopts; non-binding) Δ̂ ≤ −δ
  CONTINUE      none of the above (§8.2: a look that crosses no boundary continues to look 2)
§8.2 says "the draft's single-look critical value 2.132 is REPLACED by these boundaries", so the EQUIVALENT interval
and the INFERIOR bound use b at look 1 (a repeated-confidence-interval reading). The fixed-sample 90 % interval
Δ̂ ± 2.132·√V̂ (§8.1's TOST interval) and X5's ``cross.decide`` verdict (whose INFERIOR label uses t_{0.95,4} =
2.132) are REPORTED beside it, and the read records whether the two readings would give a different outcome."""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Tuple

sys.path.insert(0, str(Path(__file__).resolve().parent))
from agents.training import eval_ledger as L  # noqa: E402
from main.h2h import cross as X  # noqa: E402
import plan_look1 as PLAN  # noqa: E402

HERE = Path(__file__).resolve().parent
LOOK = 1
FAMILY = "st_screen_strength_steps"
REQUEST = "st_look1_steps"
PROTOCOL = "gen3_eval_protocol_v1_h2h"
DELTA = 3.5
T95_DF4 = 2.132  # §8.1's single-look critical value (t_{0.95, 4} = 2.1318…)


def code_head() -> str:
    src = Path(X.__file__).resolve().parents[2]
    return subprocess.run(["git", "rev-parse", "HEAD"], cwd=src.parent, capture_output=True, text=True,
                          check=True).stdout.strip()


def _cmp(stat: float, bound: float, above: bool, what: str, near: List[str]) -> bool:
    if abs(stat - bound) <= X.RULE8_EPS:
        near.append(f"{what}: {stat!r} within {X.RULE8_EPS} of {bound}")
        return False
    return stat > bound if above else stat < bound


def outcome(dhat: float, se: float, b: float) -> Tuple[str, Dict[str, Any]]:
    near: List[str] = []
    t_ni, t_sup = (dhat + DELTA) / se, dhat / se
    lo, hi = dhat - b * se, dhat + b * se
    better = _cmp(t_sup, b, True, "t_SUP vs b", near)
    equiv = _cmp(lo, -DELTA, True, "interval low vs -δ", near) and _cmp(hi, DELTA, False, "interval high vs +δ", near)
    ni = _cmp(t_ni, b, True, "t_NI vs b", near)
    inferior = _cmp(hi, -DELTA, False, "upper bound vs -δ", near)
    futile = _cmp(dhat, -DELTA, False, "Δ̂ vs -δ", near)
    if better:
        o = "BETTER"
    elif equiv:
        o = "EQUIVALENT"
    elif ni:
        o = "NON-INFERIOR"
    elif inferior:
        o = "INFERIOR"
    elif futile:
        o = "FUTILITY STOP (verdict NOT DETECTED)"
    else:
        o = "CONTINUE"
    return o, {"multiplier": b, "t_NI": t_ni, "t_SUP": t_sup, "interval": [lo, hi], "near_boundary": near,
               "crossed": {"BETTER": better, "EQUIVALENT": equiv, "NON-INFERIOR": ni, "INFERIOR": inferior,
                           "FUTILITY": futile}}


def _matrix_md(st: Dict[str, Any], rows: List[str], cols: List[str]) -> List[str]:
    out = ["| static \\ legacy | " + " | ".join(cols) + " | row mean R_i |", "|---" * (len(cols) + 2) + "|"]
    for r, line, rm in zip(rows, st["h_pp"], st["row_means_pp"]):
        out.append(f"| {r} | " + " | ".join(f"{x:.2f}" for x in line) + f" | {rm:.2f} |")
    out.append("| column mean C_j | " + " | ".join(f"{x:.2f}" for x in st["col_means_pp"]) + " | |")
    return out


def render_md(out: Dict[str, Any]) -> str:
    L_ = ["# Static-token screen look 1 — the read (generated by read_look1.py)", "",
          f"Estimator and ledger reader imported from the checkout at `{out['code_head']}` (P_st 6c6d2e09). "
          f"Family `{FAMILY}`, request `{REQUEST}`, regime `{out['regime_id']}`.", ""]
    st = out["stat"]
    if out["inconclusive"]:
        L_ += [f"## INCONCLUSIVE: {out['inconclusive']}", ""]
    if st:
        p, f = out["primary"], out["fixed_sample"]
        L_ += [f"## Outcome at look 1 (b = {X.LOOK_BOUNDARIES[LOOK]}): **{out['outcome']}**", "",
               f"- Δ̂ = **{st['delta_hat_pp']:+.2f} pp**; V̂ = {st['v_hat']:.4f} (s²_R {st['s2_rows']:.4f}, "
               f"s²_C {st['s2_cols']:.4f}), √V̂ = {st['se_pp']:.3f} pp, df {st['df']}",
               f"- t_NI = (Δ̂ + 3.5)/√V̂ = **{p['t_NI']:.3f}**, t_SUP = Δ̂/√V̂ = **{p['t_SUP']:.3f}**, "
               f"both vs **5.761**",
               f"- 90 % interval, fixed-sample (Δ̂ ± 2.132·√V̂, §8.1's TOST interval): "
               f"**[{f['interval'][0]:+.2f}, {f['interval'][1]:+.2f}] pp**",
               f"- look-1 interval (Δ̂ ± 5.761·√V̂, the boundary in place of 2.132, §8.2): "
               f"[{p['interval'][0]:+.2f}, {p['interval'][1]:+.2f}] pp",
               f"- the fixed-sample reading's outcome would be: {out['fixed_sample_outcome']} "
               f"({'same' if out['readings_agree'] else 'DIFFERENT — a FINDING'})",
               f"- X5's estimator (`main.h2h.cross.decide`, look 1): {out['x5_verdict']}",
               f"- rule 8 near-boundary: {p['near_boundary'] + f['near_boundary'] or 'none'}", "",
               "h_ij = static seed i's score (pp, a draw = ½) against legacy seed j, 1,000 mirrored pairs per cell:", ""]
        L_ += _matrix_md(st, [f"static s{s}" for s in PLAN.SEEDS], [f"legacy s{s}" for s in PLAN.SEEDS]) + [""]
        L_ += ["| cell | pairs | W | L | D | aborted | score (pp) |", "|---|---|---|---|---|---|---|"]
        for c in out["cells"]:
            L_.append(f"| {c['player']} vs {c['opponent']} | {c['n_pairs']} | {c['w']} | {c['l']} | {c['d']} | "
                      f"{c['aborted']} | {c['score_pp']:.2f} |")
        L_.append("")
    L_ += ["## Preconditions", "", f"- failures: {out['preconditions'] or 'none'}",
           f"- S3 amendment-2 check: {out['s3_check']}"]
    return "\n".join(L_) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=None)
    ap.add_argument("--progress", action="store_true")
    ap.add_argument("--out-dir", default=str(HERE))
    a = ap.parse_args()
    head = code_head()
    print(f"[read] estimator checkout HEAD {head}", file=sys.stderr)
    if head != PLAN.PIN:
        print(f"REFUSED: the estimator is imported from {head}, not P_st {PLAN.PIN}", file=sys.stderr)
        return 5
    root = Path(a.root) if a.root else L.archive_ledger_root()
    cells = X.look_cells(root, FAMILY, REQUEST, PROTOCOL)
    if a.progress:
        done = sum(1 for c in cells if c.n_pairs >= X.MIN_PAIRS)
        print(f"{REQUEST}: {len(cells)} cells, {done} at >= {X.MIN_PAIRS} pairs, {sum(c.n_pairs for c in cells)} "
              f"pairs, aborted {sum(c.aborted for c in cells)}")
        return 0
    got, fails, facts = PLAN.resolve(PLAN.ARCHIVE_MODELS)
    ok, s3line = PLAN.s3_valid()
    if not ok:
        fails.append(f"S3 amendment-2 check not VALID: {s3line}")
    rs = [PLAN.sha(got["static"][s]) for s in PLAN.SEEDS if s in got["static"]]
    cs = [PLAN.sha(got["legacy"][s]) for s in PLAN.SEEDS if s in got["legacy"]]
    regime = L.read(X.FAMILY_READ_OFF, root=root, family=FAMILY).regime_id
    m = X.matrix_from_cells(cells, rs, cs)
    reasons = list(m.inconclusive) + fails
    d = X.summarize(LOOK, m, fails)
    out: Dict[str, Any] = {"look": LOOK, "family": FAMILY, "request": REQUEST, "regime_id": regime,
                           "code_head": head, "preconditions": fails, "s3_check": s3line, "seed_facts": facts,
                           "row_sha256": rs, "col_sha256": cs, "cells": list(m.cells), "inconclusive": reasons,
                           "x5_decision": d.as_dict(), "x5_verdict": X.verdict_text(d), "stat": None}
    if m.h is not None and not reasons:
        st = X.cross_stat(m.h)
        out["stat"] = st.as_dict()
        o, prim = outcome(st.delta_hat, st.se, X.LOOK_BOUNDARIES[LOOK])
        of, fixed = outcome(st.delta_hat, st.se, T95_DF4)
        # ``fixed`` is the whole table at 2.132 (its "crossed" flags included, REPORTED); the fixed-sample OUTCOME
        # below changes only the interval rows (EQUIVALENT / INFERIOR), as §8.2 leaves the t tests at the boundary
        fo = o
        if o in ("CONTINUE", "FUTILITY STOP (verdict NOT DETECTED)"):
            if fixed["crossed"]["EQUIVALENT"]:
                fo = "EQUIVALENT"
            elif fixed["crossed"]["INFERIOR"]:
                fo = "INFERIOR"
        out.update({"outcome": o, "primary": prim, "fixed_sample": fixed, "fixed_sample_outcome": fo,
                    "readings_agree": fo == o,
                    "t_exact_95_df4": X.t_ppf(0.95, 4), "t_exact_975_df4": X.t_ppf(0.975, 4)})
    else:
        out["outcome"] = "INCONCLUSIVE"
    od = Path(a.out_dir)
    od.mkdir(parents=True, exist_ok=True)
    (od / "result.json").write_text(json.dumps(out, indent=1, sort_keys=True, default=str) + "\n")
    (od / "result.md").write_text(render_md(out))
    print(json.dumps({"outcome": out["outcome"], "x5_verdict": out["x5_verdict"],
                      "delta_hat": (out["stat"] or {}).get("delta_hat_pp")}, indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
