#!/usr/bin/env bash
# THE REGISTERED CRITIC-ROW REPORT for the FLOOR PAIR — W_b as ARM, arm W as CONTROL.
#
# 🚨 This is the first LIKE-FOR-LIKE critic pair in the campaign. The flywheel pair's report
# (`flywheel_pair_read_2026-09-15/scripts/harness/run_critic_read_pair.sh`) put arm W's CRITIC
# against arm S's AUXILIARY win-prob head, because arm S's real critic is a distributional E[Z]
# on a shaped-return scale where the calibration family is not defined. Here BOTH sides are
# `--critic winprob` runs, so `values` and `win_probs` are the SAME TENSOR on both and every row
# -- the whole gate.* family included -- is a critic-vs-critic contrast.
#
# Comparable by construction, exactly as the pair was: both frames are offline full-capture draws
# of 800 games x 12 opponents, both at the RECORDED greedy sentinel regime, both from the
# bit-exact eval_traces/step_74000016/snapshot.zip of a completed 75,005,952-step run, both
# generated by the same script with the same two seeds (20260910 / 20260911).
#
# One invocation is enough: --v-column values would read the same tensor.
set -u
export PYTHONPATH=/home/goodlad/dev/gen3ai/src
export POKESIM_SIM_BRIDGE_BIN=/home/goodlad/dev/gen3ai/src/rust_sim/target/release/sim_bridge
export CUDA_VISIBLE_DEVICES=""
P=/home/goodlad/miniconda3/envs/gen3ai_stable/bin/python3
TMP=/home/goodlad/.claude/jobs/9ab51de6/tmp
DRAW=${1:-draw1}
cd /home/goodlad/dev/gen3ai
nice -n 15 $P -m main.ops.critic_read ai_v13_04_flywheel_winprob_b \
  --control ai_v13_02_flywheel_winprob \
  --arm-traces     "$TMP/wb_read/traces/$DRAW/eval_traces/step_74000016" \
  --control-traces "$TMP/pair_read/traces/$DRAW/eval_traces/step_74000016" \
  --step 74000016 \
  --v-column win_probs \
  --floor-json "$TMP/wb_read/critic/floors_v6_max_imported.json" \
  --nice 15 \
  --out "$TMP/wb_read/critic/read_${DRAW}_Wb_vs_W" 2>&1
echo "=== EXIT $? $DRAW $(date -Is) ==="
