"""Static-token screen LOOK 2: the registered read (design_static_tokens.md §8.1 + §8.2), at P_st 6c6d2e09.

Reads look 1's request ``st_look1_steps`` (9 cells, REUSED) and look 2's ``st_look2_steps`` (16 new cells) of family
``st_screen_strength_steps`` from the eval COUNT ledger through ``main.h2h.cross``'s declared family read, builds the
FULL 5 × 5 matrix (rows = static seeds 1001-1005, columns = legacy seeds 1001-1005, keyed by each final's sha256), and
writes ``result.json`` + ``result.md`` beside this file.

    bash at_pin.sh read_look2.py [--root <ledger root>] [--progress]

THE PIN: the estimator and the ledger reader are imported from the checkout on PYTHONPATH; this script REFUSES (exit
5) unless that checkout's ``git rev-parse HEAD`` is 6c6d2e09 (§8.2: every cross and read at P_st, never at HEAD).

THE STATISTIC (§8.1, X5 §7.4's, at n = 5): ``main.h2h.cross.cross_stat`` — Δ̂ = mean(h) − 50, V̂ = (s²_R + s²_C)/5,
df = 2(n − 1) = 8; t_NI = (Δ̂ + 3.5)/√V̂ (cross_stat's ``t``) and t_SUP = Δ̂/√V̂.

THE OUTCOME TABLE AT LOOK 2 (§8.1's table with §8.2's look-2 boundary b = 2.683 in place of 2.132; rule 8 on every
comparison; INCONCLUSIVE on any invalid input) — look 1's declared table (``read_look1.outcome``), unchanged but for
b, DECLARED HERE BEFORE THE READ:
  BETTER        t_SUP ≥ b
  EQUIVALENT    the look's interval Δ̂ ± b·√V̂ lies inside (−δ, +δ)
  NON-INFERIOR  t_NI ≥ b, neither of the above
  INFERIOR      Δ̂ + b·√V̂ < −δ
  FUTILITY STOP (X5's futility rule, which §8.2 adopts; non-binding) Δ̂ ≤ −δ
  CONTINUE      none of the above (§8.2: a look that crosses no boundary continues to look 3)
The orchestrator ruled after look 1 that §8.2's sequential boundaries govern at an interim look, never the fixed-sample
interval; the fixed-sample 90 % interval Δ̂ ± t_{0.95,8}·√V̂ (t_{0.95,8} = 1.860) and X5's ``cross.decide`` verdict are
REPORTED beside it only."""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(1, str(HERE.parent / "static_screen_look1_2026-10-08"))
from agents.training import eval_ledger as L  # noqa: E402
from main.h2h import cross as X  # noqa: E402
import plan_look2 as PLAN  # noqa: E402
import read_look1 as R1  # noqa: E402  (look 1's declared outcome table)

LOOK = 2
DELTA = R1.DELTA


def code_head() -> str:
    src = Path(X.__file__).resolve().parents[2]
    return subprocess.run(["git", "rev-parse", "HEAD"], cwd=src.parent, capture_output=True, text=True,
                          check=True).stdout.strip()


def _matrix_md(st: Dict[str, Any], rows: List[str], cols: List[str], n1: int) -> List[str]:
    out = ["| static \\ legacy | " + " | ".join(cols) + " | row mean R_i |", "|---" * (len(cols) + 2) + "|"]
    for i, (r, line, rm) in enumerate(zip(rows, st["h_pp"], st["row_means_pp"])):
        cells = [f"{x:.2f}" if (i < n1 and j < n1) else f"**{x:.2f}**" for j, x in enumerate(line)]
        out.append(f"| {r} | " + " | ".join(cells) + f" | {rm:.2f} |")
    out.append("| column mean C_j | " + " | ".join(f"{x:.2f}" for x in st["col_means_pp"]) + " | |")
    return out


def render_md(out: Dict[str, Any]) -> str:
    b = X.LOOK_BOUNDARIES[LOOK]
    L_ = ["# Static-token screen look 2 — the read (generated by read_look2.py)", "",
          f"Estimator and ledger reader imported from the checkout at `{out['code_head']}` (P_st 6c6d2e09). "
          f"Family `{PLAN.FAMILY}`, requests `{PLAN.REQ1}` ({out['n_cells_look1']} cells, reused) + `{PLAN.REQ2}` "
          f"({out['n_cells_look2']} cells, new), regime `{out['regime_id']}`.", ""]
    st = out["stat"]
    if out["inconclusive"]:
        L_ += [f"## INCONCLUSIVE: {out['inconclusive']}", ""]
    if st:
        p, f = out["primary"], out["fixed_sample"]
        L_ += [f"## Outcome at look 2 (b = {b}): **{out['outcome']}**", "",
               f"- Δ̂ = **{st['delta_hat_pp']:+.2f} pp**; V̂ = {st['v_hat']:.4f} (s²_R {st['s2_rows']:.4f}, "
               f"s²_C {st['s2_cols']:.4f}), √V̂ = {st['se_pp']:.3f} pp, df {st['df']}",
               f"- t_NI = (Δ̂ + 3.5)/√V̂ = **{p['t_NI']:.3f}**, t_SUP = Δ̂/√V̂ = **{p['t_SUP']:.3f}**, both vs **{b}**",
               f"- look-2 interval (Δ̂ ± {b}·√V̂, the boundary, §8.2 — the registered reading): "
               f"**[{p['interval'][0]:+.2f}, {p['interval'][1]:+.2f}] pp**",
               f"- 90 % interval, fixed-sample (Δ̂ ± {out['t_exact_95_df8']:.3f}·√V̂; REPORTED only): "
               f"[{f['interval'][0]:+.2f}, {f['interval'][1]:+.2f}] pp",
               f"- 95 % two-sided (cross.py's reported interval): [{st['ci95_pp'][0]:+.2f}, {st['ci95_pp'][1]:+.2f}] pp",
               f"- the fixed-sample reading's outcome would be: {out['fixed_sample_outcome']} "
               f"({'same' if out['readings_agree'] else 'DIFFERENT — reported, not the outcome'})",
               f"- X5's estimator (`main.h2h.cross.decide`, look 2): {out['x5_verdict']}",
               f"- rule 8 near-boundary: {p['near_boundary'] + f['near_boundary'] or 'none'}", "",
               "h_ij = static seed i's score (pp, a draw = ½) against legacy seed j, 1,000 mirrored pairs per cell "
               "(look-2 cells in bold):", ""]
        L_ += _matrix_md(st, [f"static s{s}" for s in PLAN.SEEDS], [f"legacy s{s}" for s in PLAN.SEEDS],
                         len(PLAN.LOOK1_SEEDS)) + [""]
        L_ += ["| cell | pairs | W | L | D | aborted | score (pp) |", "|---|---|---|---|---|---|---|"]
        for c in out["cells"]:
            L_.append(f"| {c['player']} vs {c['opponent']} | {c['n_pairs']} | {c['w']} | {c['l']} | {c['d']} | "
                      f"{c['aborted']} | {c['score_pp']:.2f} |")
        L_.append("")
    L_ += ["## Preconditions", "", f"- failures: {out['preconditions'] or 'none'}",
           f"- S3 amendment-2 check: {out['s3_check']}"]
    return "\n".join(L_) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=None)
    ap.add_argument("--progress", action="store_true")
    ap.add_argument("--out-dir", default=str(HERE))
    a = ap.parse_args()
    head = code_head()
    print(f"[read] estimator checkout HEAD {head}", file=sys.stderr)
    if head != PLAN.PIN:
        print(f"REFUSED: the estimator is imported from {head}, not P_st {PLAN.PIN}", file=sys.stderr)
        return 5
    root = Path(a.root) if a.root else L.archive_ledger_root()
    c1, c2 = PLAN.look_cells(root, PLAN.REQ1), PLAN.look_cells(root, PLAN.REQ2)
    if a.progress:
        for req, cs in ((PLAN.REQ1, c1), (PLAN.REQ2, c2)):
            done = sum(1 for c in cs if c.n_pairs >= X.MIN_PAIRS)
            print(f"{req}: {len(cs)} cells, {done} at >= {X.MIN_PAIRS} pairs, {sum(c.n_pairs for c in cs)} pairs, "
                  f"aborted {sum(c.aborted for c in cs)}")
        return 0
    got, fails, facts = PLAN.resolve(PLAN.ARCHIVE_MODELS)
    ok, s3line = PLAN.P1.s3_valid()
    if not ok:
        fails.append(f"S3 amendment-2 check not VALID: {s3line}")
    rs = [PLAN.P1.sha(got["static"][s]) for s in PLAN.SEEDS if s in got["static"]]
    cs = [PLAN.P1.sha(got["legacy"][s]) for s in PLAN.SEEDS if s in got["legacy"]]
    reasons: List[str] = list(fails)
    # the uniqueness guard, read side: look 2 holds no look-1 cell, and look 1 holds exactly its registered cells
    k1 = {(c.player, c.opponent) for c in c1}
    n1 = len(PLAN.LOOK1_SEEDS)
    old = {(rs[i], cs[j]) for i in range(min(n1, len(rs))) for j in range(min(n1, len(cs)))}
    dup = [f"{c.player_id} vs {c.opponent_id}" for c in c2 if (c.player, c.opponent) in k1]
    if dup:
        reasons.append(f"{PLAN.REQ2} replays look-1 cell(s): {dup}")
    if k1 != old:
        reasons.append(f"{PLAN.REQ1} holds {len(k1)} cell(s), not exactly the registered {len(old)} look-1 cells")
    regime = L.read(X.FAMILY_READ_OFF, root=root, family=PLAN.FAMILY).regime_id
    m = X.matrix_from_cells(list(c1) + list(c2), rs, cs)
    reasons = list(m.inconclusive) + reasons
    d = X.summarize(LOOK, m, reasons)
    out: Dict[str, Any] = {"look": LOOK, "family": PLAN.FAMILY, "requests": [PLAN.REQ1, PLAN.REQ2],
                           "n_cells_look1": len(c1), "n_cells_look2": len(c2), "regime_id": regime,
                           "code_head": head, "preconditions": fails, "s3_check": s3line, "seed_facts": facts,
                           "row_sha256": rs, "col_sha256": cs, "cells": list(m.cells), "inconclusive": reasons,
                           "x5_decision": d.as_dict(), "x5_verdict": X.verdict_text(d), "stat": None}
    if m.h is not None and not reasons:
        st = X.cross_stat(m.h)
        out["stat"] = st.as_dict()
        b = X.LOOK_BOUNDARIES[LOOK]
        t95 = X.t_ppf(0.95, st.df)
        o, prim = R1.outcome(st.delta_hat, st.se, b)
        _, fixed = R1.outcome(st.delta_hat, st.se, t95)
        # the fixed-sample OUTCOME changes only the interval rows (EQUIVALENT / INFERIOR) — REPORTED, never the outcome
        fo = o
        if o in ("CONTINUE", "FUTILITY STOP (verdict NOT DETECTED)"):
            if fixed["crossed"]["EQUIVALENT"]:
                fo = "EQUIVALENT"
            elif fixed["crossed"]["INFERIOR"]:
                fo = "INFERIOR"
        out.update({"outcome": o, "primary": prim, "fixed_sample": fixed, "fixed_sample_outcome": fo,
                    "readings_agree": fo == o, "t_exact_95_df8": t95, "t_exact_975_df8": X.t_ppf(0.975, st.df)})
    else:
        out["outcome"] = "INCONCLUSIVE"
    od = Path(a.out_dir)
    od.mkdir(parents=True, exist_ok=True)
    (od / "result.json").write_text(json.dumps(out, indent=1, sort_keys=True, default=str) + "\n")
    (od / "result.md").write_text(render_md(out))
    print(json.dumps({"outcome": out["outcome"], "x5_verdict": out["x5_verdict"],
                      "delta_hat": (out["stat"] or {}).get("delta_hat_pp")}, indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
